<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSAlert\NSAlert as ExtNSAlert;
use Jovian\Bindings\AppKit\Enums\NSAlertStyle;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSAlert extends ObjCObject
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSAlert::init());
    }

    public static function alertWithError(int $error): ?ObjCObject
    {
        return ObjCObject::box(ExtNSAlert::alertWithError($error));
    }

    public function messageText(): ?string
    {
        return ExtNSAlert::messageText($this->handle);
    }

    public function setMessageText(string $messageText): static
    {
        ExtNSAlert::setMessageText($this->handle, $messageText);

        return $this;
    }

    public function informativeText(): ?string
    {
        return ExtNSAlert::informativeText($this->handle);
    }

    public function setInformativeText(string $informativeText): static
    {
        ExtNSAlert::setInformativeText($this->handle, $informativeText);

        return $this;
    }

    public function icon(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSAlert::icon($this->handle));
    }

    public function setIcon(int $icon): static
    {
        ExtNSAlert::setIcon($this->handle, $icon);

        return $this;
    }

    public function addButtonWithTitle(string $title): ?ObjCObject
    {
        return ObjCObject::box(ExtNSAlert::addButtonWithTitle($this->handle, $title));
    }

    public function buttons(): array
    {
        return ExtNSAlert::buttons($this->handle);
    }

    public function alertStyle(): NSAlertStyle|int
    {
        return ExtNSAlert::alertStyle($this->handle);
    }

    public function setAlertStyle(NSAlertStyle|int $alertStyle): static
    {
        ExtNSAlert::setAlertStyle($this->handle, $alertStyle instanceof \BackedEnum ? $alertStyle->value : $alertStyle);

        return $this;
    }

    public function showsHelp(): bool
    {
        return ExtNSAlert::showsHelp($this->handle);
    }

    public function setShowsHelp(bool $showsHelp): static
    {
        ExtNSAlert::setShowsHelp($this->handle, $showsHelp);

        return $this;
    }

    public function helpAnchor(): mixed
    {
        return ExtNSAlert::helpAnchor($this->handle);
    }

    public function setHelpAnchor(string $helpAnchor): static
    {
        ExtNSAlert::setHelpAnchor($this->handle, $helpAnchor);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSAlert::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSAlert::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function accessoryView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSAlert::accessoryView($this->handle));
    }

    public function setAccessoryView(int $accessoryView): static
    {
        ExtNSAlert::setAccessoryView($this->handle, $accessoryView);

        return $this;
    }

    public function layout(): static
    {
        ExtNSAlert::layout($this->handle);

        return $this;
    }

    public function runModal(): int
    {
        return ExtNSAlert::runModal($this->handle);
    }

    public function showsSuppressionButton(): bool
    {
        return ExtNSAlert::showsSuppressionButton($this->handle);
    }

    public function setShowsSuppressionButton(bool $showsSuppressionButton): static
    {
        ExtNSAlert::setShowsSuppressionButton($this->handle, $showsSuppressionButton);

        return $this;
    }

    public function suppressionButton(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSAlert::suppressionButton($this->handle));
    }

    public function window(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSAlert::window($this->handle));
    }
}
