<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSBox\NSBox as ExtNSBox;
use Jovian\Bindings\AppKit\Enums\NSBoxType;
use Jovian\Bindings\AppKit\Enums\NSTitlePosition;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSBox extends NSView
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSBox::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function boxType(): NSBoxType|int
    {
        return ExtNSBox::boxType($this->handle);
    }

    public function setBoxType(NSBoxType|int $boxType): static
    {
        ExtNSBox::setBoxType($this->handle, $boxType instanceof \BackedEnum ? $boxType->value : $boxType);

        return $this;
    }

    public function titlePosition(): NSTitlePosition|int
    {
        return ExtNSBox::titlePosition($this->handle);
    }

    public function setTitlePosition(NSTitlePosition|int $titlePosition): static
    {
        ExtNSBox::setTitlePosition($this->handle, $titlePosition instanceof \BackedEnum ? $titlePosition->value : $titlePosition);

        return $this;
    }

    public function title(): ?string
    {
        return ExtNSBox::title($this->handle);
    }

    public function setTitle(string $title): static
    {
        ExtNSBox::setTitle($this->handle, $title);

        return $this;
    }

    public function titleFont(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSBox::titleFont($this->handle));
    }

    public function setTitleFont(int $titleFont): static
    {
        ExtNSBox::setTitleFont($this->handle, $titleFont);

        return $this;
    }

    public function borderRect(): NSRect
    {
        return NSRect::fromArray(ExtNSBox::borderRect($this->handle));
    }

    public function titleRect(): NSRect
    {
        return NSRect::fromArray(ExtNSBox::titleRect($this->handle));
    }

    public function titleCell(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSBox::titleCell($this->handle));
    }

    public function contentViewMargins(): NSSize
    {
        return NSSize::fromArray(ExtNSBox::contentViewMargins($this->handle));
    }

    public function setContentViewMargins(NSSize $contentViewMargins): static
    {
        ExtNSBox::setContentViewMargins(...[$this->handle, ...$contentViewMargins->toArgs()]);

        return $this;
    }

    public function sizeToFit(): static
    {
        ExtNSBox::sizeToFit($this->handle);

        return $this;
    }

    public function setFrameFromContentFrame(NSRect $contentFrame): static
    {
        ExtNSBox::setFrameFromContentFrame(...[$this->handle, ...$contentFrame->toArgs()]);

        return $this;
    }

    public function contentView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSBox::contentView($this->handle));
    }

    public function setContentView(int $contentView): static
    {
        ExtNSBox::setContentView($this->handle, $contentView);

        return $this;
    }

    public function isTransparent(): bool
    {
        return ExtNSBox::isTransparent($this->handle);
    }

    public function setTransparent(bool $transparent): static
    {
        ExtNSBox::setTransparent($this->handle, $transparent);

        return $this;
    }

    public function borderWidth(): float
    {
        return ExtNSBox::borderWidth($this->handle);
    }

    public function setBorderWidth(float $borderWidth): static
    {
        ExtNSBox::setBorderWidth($this->handle, $borderWidth);

        return $this;
    }

    public function cornerRadius(): float
    {
        return ExtNSBox::cornerRadius($this->handle);
    }

    public function setCornerRadius(float $cornerRadius): static
    {
        ExtNSBox::setCornerRadius($this->handle, $cornerRadius);

        return $this;
    }

    public function borderColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSBox::borderColor($this->handle));
    }

    public function setBorderColor(int $borderColor): static
    {
        ExtNSBox::setBorderColor($this->handle, $borderColor);

        return $this;
    }

    public function fillColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSBox::fillColor($this->handle));
    }

    public function setFillColor(int $fillColor): static
    {
        ExtNSBox::setFillColor($this->handle, $fillColor);

        return $this;
    }
}
