<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSClipView\NSClipView as ExtNSClipView;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSClipView extends NSView
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSClipView::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function backgroundColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSClipView::backgroundColor($this->handle));
    }

    public function setBackgroundColor(int $backgroundColor): static
    {
        ExtNSClipView::setBackgroundColor($this->handle, $backgroundColor);

        return $this;
    }

    public function drawsBackground(): bool
    {
        return ExtNSClipView::drawsBackground($this->handle);
    }

    public function setDrawsBackground(bool $drawsBackground): static
    {
        ExtNSClipView::setDrawsBackground($this->handle, $drawsBackground);

        return $this;
    }

    public function documentView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSClipView::documentView($this->handle));
    }

    public function setDocumentView(int $documentView): static
    {
        ExtNSClipView::setDocumentView($this->handle, $documentView);

        return $this;
    }

    public function documentRect(): NSRect
    {
        return NSRect::fromArray(ExtNSClipView::documentRect($this->handle));
    }

    public function documentCursor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSClipView::documentCursor($this->handle));
    }

    public function setDocumentCursor(int $documentCursor): static
    {
        ExtNSClipView::setDocumentCursor($this->handle, $documentCursor);

        return $this;
    }

    public function documentVisibleRect(): NSRect
    {
        return NSRect::fromArray(ExtNSClipView::documentVisibleRect($this->handle));
    }

    public function viewFrameChanged(int $notification): static
    {
        ExtNSClipView::viewFrameChanged($this->handle, $notification);

        return $this;
    }

    public function viewBoundsChanged(int $notification): static
    {
        ExtNSClipView::viewBoundsChanged($this->handle, $notification);

        return $this;
    }

    public function autoscroll(int $event): bool
    {
        return ExtNSClipView::autoscroll($this->handle, $event);
    }

    public function scrollToPoint(NSPoint $newOrigin): static
    {
        ExtNSClipView::scrollToPoint(...[$this->handle, ...$newOrigin->toArgs()]);

        return $this;
    }

    public function constrainBoundsRect(NSRect $proposedBounds): NSRect
    {
        return NSRect::fromArray(ExtNSClipView::constrainBoundsRect(...[$this->handle, ...$proposedBounds->toArgs()]));
    }

    public function contentInsets(): NSEdgeInsets
    {
        return NSEdgeInsets::fromArray(ExtNSClipView::contentInsets($this->handle));
    }

    public function setContentInsets(NSEdgeInsets $contentInsets): static
    {
        ExtNSClipView::setContentInsets(...[$this->handle, ...$contentInsets->toArgs()]);

        return $this;
    }

    public function automaticallyAdjustsContentInsets(): bool
    {
        return ExtNSClipView::automaticallyAdjustsContentInsets($this->handle);
    }

    public function setAutomaticallyAdjustsContentInsets(bool $automaticallyAdjustsContentInsets): static
    {
        ExtNSClipView::setAutomaticallyAdjustsContentInsets($this->handle, $automaticallyAdjustsContentInsets);

        return $this;
    }
}
