<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSCollectionViewFlowLayout\NSCollectionViewFlowLayout as ExtNSCollectionViewFlowLayout;
use Jovian\Bindings\AppKit\Enums\NSCollectionViewScrollDirection;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSCollectionViewFlowLayout extends NSCollectionViewLayout
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewFlowLayout::init());
    }

    public function minimumLineSpacing(): float
    {
        return ExtNSCollectionViewFlowLayout::minimumLineSpacing($this->handle);
    }

    public function setMinimumLineSpacing(float $minimumLineSpacing): static
    {
        ExtNSCollectionViewFlowLayout::setMinimumLineSpacing($this->handle, $minimumLineSpacing);

        return $this;
    }

    public function minimumInteritemSpacing(): float
    {
        return ExtNSCollectionViewFlowLayout::minimumInteritemSpacing($this->handle);
    }

    public function setMinimumInteritemSpacing(float $minimumInteritemSpacing): static
    {
        ExtNSCollectionViewFlowLayout::setMinimumInteritemSpacing($this->handle, $minimumInteritemSpacing);

        return $this;
    }

    public function itemSize(): NSSize
    {
        return NSSize::fromArray(ExtNSCollectionViewFlowLayout::itemSize($this->handle));
    }

    public function setItemSize(NSSize $itemSize): static
    {
        ExtNSCollectionViewFlowLayout::setItemSize(...[$this->handle, ...$itemSize->toArgs()]);

        return $this;
    }

    public function estimatedItemSize(): NSSize
    {
        return NSSize::fromArray(ExtNSCollectionViewFlowLayout::estimatedItemSize($this->handle));
    }

    public function setEstimatedItemSize(NSSize $estimatedItemSize): static
    {
        ExtNSCollectionViewFlowLayout::setEstimatedItemSize(...[$this->handle, ...$estimatedItemSize->toArgs()]);

        return $this;
    }

    public function scrollDirection(): NSCollectionViewScrollDirection|int
    {
        return ExtNSCollectionViewFlowLayout::scrollDirection($this->handle);
    }

    public function setScrollDirection(NSCollectionViewScrollDirection|int $scrollDirection): static
    {
        ExtNSCollectionViewFlowLayout::setScrollDirection($this->handle, $scrollDirection instanceof \BackedEnum ? $scrollDirection->value : $scrollDirection);

        return $this;
    }

    public function headerReferenceSize(): NSSize
    {
        return NSSize::fromArray(ExtNSCollectionViewFlowLayout::headerReferenceSize($this->handle));
    }

    public function setHeaderReferenceSize(NSSize $headerReferenceSize): static
    {
        ExtNSCollectionViewFlowLayout::setHeaderReferenceSize(...[$this->handle, ...$headerReferenceSize->toArgs()]);

        return $this;
    }

    public function footerReferenceSize(): NSSize
    {
        return NSSize::fromArray(ExtNSCollectionViewFlowLayout::footerReferenceSize($this->handle));
    }

    public function setFooterReferenceSize(NSSize $footerReferenceSize): static
    {
        ExtNSCollectionViewFlowLayout::setFooterReferenceSize(...[$this->handle, ...$footerReferenceSize->toArgs()]);

        return $this;
    }

    public function sectionInset(): NSEdgeInsets
    {
        return NSEdgeInsets::fromArray(ExtNSCollectionViewFlowLayout::sectionInset($this->handle));
    }

    public function setSectionInset(NSEdgeInsets $sectionInset): static
    {
        ExtNSCollectionViewFlowLayout::setSectionInset(...[$this->handle, ...$sectionInset->toArgs()]);

        return $this;
    }

    public function sectionHeadersPinToVisibleBounds(): bool
    {
        return ExtNSCollectionViewFlowLayout::sectionHeadersPinToVisibleBounds($this->handle);
    }

    public function setSectionHeadersPinToVisibleBounds(bool $sectionHeadersPinToVisibleBounds): static
    {
        ExtNSCollectionViewFlowLayout::setSectionHeadersPinToVisibleBounds($this->handle, $sectionHeadersPinToVisibleBounds);

        return $this;
    }

    public function sectionFootersPinToVisibleBounds(): bool
    {
        return ExtNSCollectionViewFlowLayout::sectionFootersPinToVisibleBounds($this->handle);
    }

    public function setSectionFootersPinToVisibleBounds(bool $sectionFootersPinToVisibleBounds): static
    {
        ExtNSCollectionViewFlowLayout::setSectionFootersPinToVisibleBounds($this->handle, $sectionFootersPinToVisibleBounds);

        return $this;
    }

    public function sectionAtIndexIsCollapsed(int $sectionIndex): bool
    {
        return ExtNSCollectionViewFlowLayout::sectionAtIndexIsCollapsed($this->handle, $sectionIndex);
    }

    public function collapseSectionAtIndex(int $sectionIndex): static
    {
        ExtNSCollectionViewFlowLayout::collapseSectionAtIndex($this->handle, $sectionIndex);

        return $this;
    }

    public function expandSectionAtIndex(int $sectionIndex): static
    {
        ExtNSCollectionViewFlowLayout::expandSectionAtIndex($this->handle, $sectionIndex);

        return $this;
    }
}
