<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSComboBox\NSComboBox as ExtNSComboBox;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSComboBox extends NSTextField
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSComboBox::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function hasVerticalScroller(): bool
    {
        return ExtNSComboBox::hasVerticalScroller($this->handle);
    }

    public function setHasVerticalScroller(bool $hasVerticalScroller): static
    {
        ExtNSComboBox::setHasVerticalScroller($this->handle, $hasVerticalScroller);

        return $this;
    }

    public function intercellSpacing(): NSSize
    {
        return NSSize::fromArray(ExtNSComboBox::intercellSpacing($this->handle));
    }

    public function setIntercellSpacing(NSSize $intercellSpacing): static
    {
        ExtNSComboBox::setIntercellSpacing(...[$this->handle, ...$intercellSpacing->toArgs()]);

        return $this;
    }

    public function itemHeight(): float
    {
        return ExtNSComboBox::itemHeight($this->handle);
    }

    public function setItemHeight(float $itemHeight): static
    {
        ExtNSComboBox::setItemHeight($this->handle, $itemHeight);

        return $this;
    }

    public function numberOfVisibleItems(): int
    {
        return ExtNSComboBox::numberOfVisibleItems($this->handle);
    }

    public function setNumberOfVisibleItems(int $numberOfVisibleItems): static
    {
        ExtNSComboBox::setNumberOfVisibleItems($this->handle, $numberOfVisibleItems);

        return $this;
    }

    public function isButtonBordered(): bool
    {
        return ExtNSComboBox::isButtonBordered($this->handle);
    }

    public function setButtonBordered(bool $buttonBordered): static
    {
        ExtNSComboBox::setButtonBordered($this->handle, $buttonBordered);

        return $this;
    }

    public function reloadData(): static
    {
        ExtNSComboBox::reloadData($this->handle);

        return $this;
    }

    public function noteNumberOfItemsChanged(): static
    {
        ExtNSComboBox::noteNumberOfItemsChanged($this->handle);

        return $this;
    }

    public function usesDataSource(): bool
    {
        return ExtNSComboBox::usesDataSource($this->handle);
    }

    public function setUsesDataSource(bool $usesDataSource): static
    {
        ExtNSComboBox::setUsesDataSource($this->handle, $usesDataSource);

        return $this;
    }

    public function scrollItemAtIndexToTop(int $index): static
    {
        ExtNSComboBox::scrollItemAtIndexToTop($this->handle, $index);

        return $this;
    }

    public function scrollItemAtIndexToVisible(int $index): static
    {
        ExtNSComboBox::scrollItemAtIndexToVisible($this->handle, $index);

        return $this;
    }

    public function selectItemAtIndex(int $index): static
    {
        ExtNSComboBox::selectItemAtIndex($this->handle, $index);

        return $this;
    }

    public function deselectItemAtIndex(int $index): static
    {
        ExtNSComboBox::deselectItemAtIndex($this->handle, $index);

        return $this;
    }

    public function indexOfSelectedItem(): int
    {
        return ExtNSComboBox::indexOfSelectedItem($this->handle);
    }

    public function numberOfItems(): int
    {
        return ExtNSComboBox::numberOfItems($this->handle);
    }

    public function completes(): bool
    {
        return ExtNSComboBox::completes($this->handle);
    }

    public function setCompletes(bool $completes): static
    {
        ExtNSComboBox::setCompletes($this->handle, $completes);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSComboBox::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSComboBox::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function dataSource(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSComboBox::dataSource($this->handle));
    }

    public function setDataSource(int $dataSource): static
    {
        ExtNSComboBox::setDataSource($this->handle, $dataSource);

        return $this;
    }

    public function addItemWithObjectValue(int $object): static
    {
        ExtNSComboBox::addItemWithObjectValue($this->handle, $object);

        return $this;
    }

    public function addItemsWithObjectValues(array $objects): static
    {
        ExtNSComboBox::addItemsWithObjectValues($this->handle, $objects);

        return $this;
    }

    public function insertItemWithObjectValueAtIndex(int $object, int $index): static
    {
        ExtNSComboBox::insertItemWithObjectValueAtIndex($this->handle, $object, $index);

        return $this;
    }

    public function removeItemWithObjectValue(int $object): static
    {
        ExtNSComboBox::removeItemWithObjectValue($this->handle, $object);

        return $this;
    }

    public function removeItemAtIndex(int $index): static
    {
        ExtNSComboBox::removeItemAtIndex($this->handle, $index);

        return $this;
    }

    public function removeAllItems(): static
    {
        ExtNSComboBox::removeAllItems($this->handle);

        return $this;
    }

    public function selectItemWithObjectValue(int $object): static
    {
        ExtNSComboBox::selectItemWithObjectValue($this->handle, $object);

        return $this;
    }

    public function itemObjectValueAtIndex(int $index): ?ObjCObject
    {
        return ObjCObject::box(ExtNSComboBox::itemObjectValueAtIndex($this->handle, $index));
    }

    public function objectValueOfSelectedItem(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSComboBox::objectValueOfSelectedItem($this->handle));
    }

    public function indexOfItemWithObjectValue(int $object): int
    {
        return ExtNSComboBox::indexOfItemWithObjectValue($this->handle, $object);
    }

    public function objectValues(): array
    {
        return ExtNSComboBox::objectValues($this->handle);
    }
}
