<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSCollectionViewFlowLayoutInvalidationContext\NSCollectionViewFlowLayoutInvalidationContext as ExtNSCollectionViewFlowLayoutInvalidationContext;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSCollectionViewFlowLayoutInvalidationContext extends NSCollectionViewLayoutInvalidationContext
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewFlowLayoutInvalidationContext::init());
    }

    public function invalidateFlowLayoutDelegateMetrics(): bool
    {
        return ExtNSCollectionViewFlowLayoutInvalidationContext::invalidateFlowLayoutDelegateMetrics($this->handle);
    }

    public function setInvalidateFlowLayoutDelegateMetrics(bool $invalidateFlowLayoutDelegateMetrics): static
    {
        ExtNSCollectionViewFlowLayoutInvalidationContext::setInvalidateFlowLayoutDelegateMetrics($this->handle, $invalidateFlowLayoutDelegateMetrics);

        return $this;
    }

    public function invalidateFlowLayoutAttributes(): bool
    {
        return ExtNSCollectionViewFlowLayoutInvalidationContext::invalidateFlowLayoutAttributes($this->handle);
    }

    public function setInvalidateFlowLayoutAttributes(bool $invalidateFlowLayoutAttributes): static
    {
        ExtNSCollectionViewFlowLayoutInvalidationContext::setInvalidateFlowLayoutAttributes($this->handle, $invalidateFlowLayoutAttributes);

        return $this;
    }
}
