<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSCollectionViewLayout\NSCollectionViewLayout as ExtNSCollectionViewLayout;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSCollectionViewLayout extends ObjCObject
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::init());
    }

    public function collectionView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::collectionView($this->handle));
    }

    public function invalidateLayout(): static
    {
        ExtNSCollectionViewLayout::invalidateLayout($this->handle);

        return $this;
    }

    public function invalidateLayoutWithContext(int $context): static
    {
        ExtNSCollectionViewLayout::invalidateLayoutWithContext($this->handle, $context);

        return $this;
    }

    public function registerNibForDecorationViewOfKind(int $nib, string $elementKind): static
    {
        ExtNSCollectionViewLayout::registerNibForDecorationViewOfKind($this->handle, $nib, $elementKind);

        return $this;
    }

    public function prepareLayout(): static
    {
        ExtNSCollectionViewLayout::prepareLayout($this->handle);

        return $this;
    }

    public function layoutAttributesForElementsInRect(NSRect $rect): array
    {
        return ExtNSCollectionViewLayout::layoutAttributesForElementsInRect(...[$this->handle, ...$rect->toArgs()]);
    }

    public function layoutAttributesForItemAtIndexPath(int $indexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::layoutAttributesForItemAtIndexPath($this->handle, $indexPath));
    }

    public function layoutAttributesForSupplementaryViewOfKindAtIndexPath(string $elementKind, int $indexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::layoutAttributesForSupplementaryViewOfKindAtIndexPath($this->handle, $elementKind, $indexPath));
    }

    public function layoutAttributesForDecorationViewOfKindAtIndexPath(string $elementKind, int $indexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::layoutAttributesForDecorationViewOfKindAtIndexPath($this->handle, $elementKind, $indexPath));
    }

    public function layoutAttributesForDropTargetAtPoint(NSPoint $pointInCollectionView): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::layoutAttributesForDropTargetAtPoint(...[$this->handle, ...$pointInCollectionView->toArgs()]));
    }

    public function layoutAttributesForInterItemGapBeforeIndexPath(int $indexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::layoutAttributesForInterItemGapBeforeIndexPath($this->handle, $indexPath));
    }

    public function shouldInvalidateLayoutForBoundsChange(NSRect $newBounds): bool
    {
        return ExtNSCollectionViewLayout::shouldInvalidateLayoutForBoundsChange(...[$this->handle, ...$newBounds->toArgs()]);
    }

    public function invalidationContextForBoundsChange(NSRect $newBounds): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::invalidationContextForBoundsChange(...[$this->handle, ...$newBounds->toArgs()]));
    }

    public function shouldInvalidateLayoutForPreferredLayoutAttributesWithOriginalAttributes(int $preferredAttributes, int $originalAttributes): bool
    {
        return ExtNSCollectionViewLayout::shouldInvalidateLayoutForPreferredLayoutAttributesWithOriginalAttributes($this->handle, $preferredAttributes, $originalAttributes);
    }

    public function invalidationContextForPreferredLayoutAttributesWithOriginalAttributes(int $preferredAttributes, int $originalAttributes): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::invalidationContextForPreferredLayoutAttributesWithOriginalAttributes($this->handle, $preferredAttributes, $originalAttributes));
    }

    public function targetContentOffsetForProposedContentOffsetWithScrollingVelocity(NSPoint $proposedContentOffset, NSPoint $velocity): NSPoint
    {
        return NSPoint::fromArray(ExtNSCollectionViewLayout::targetContentOffsetForProposedContentOffsetWithScrollingVelocity(...[$this->handle, ...$proposedContentOffset->toArgs(), ...$velocity->toArgs()]));
    }

    public function targetContentOffsetForProposedContentOffset(NSPoint $proposedContentOffset): NSPoint
    {
        return NSPoint::fromArray(ExtNSCollectionViewLayout::targetContentOffsetForProposedContentOffset(...[$this->handle, ...$proposedContentOffset->toArgs()]));
    }

    public function collectionViewContentSize(): NSSize
    {
        return NSSize::fromArray(ExtNSCollectionViewLayout::collectionViewContentSize($this->handle));
    }

    public function prepareForCollectionViewUpdates(array $updateItems): static
    {
        ExtNSCollectionViewLayout::prepareForCollectionViewUpdates($this->handle, $updateItems);

        return $this;
    }

    public function finalizeCollectionViewUpdates(): static
    {
        ExtNSCollectionViewLayout::finalizeCollectionViewUpdates($this->handle);

        return $this;
    }

    public function prepareForAnimatedBoundsChange(NSRect $oldBounds): static
    {
        ExtNSCollectionViewLayout::prepareForAnimatedBoundsChange(...[$this->handle, ...$oldBounds->toArgs()]);

        return $this;
    }

    public function finalizeAnimatedBoundsChange(): static
    {
        ExtNSCollectionViewLayout::finalizeAnimatedBoundsChange($this->handle);

        return $this;
    }

    public function prepareForTransitionToLayout(int $newLayout): static
    {
        ExtNSCollectionViewLayout::prepareForTransitionToLayout($this->handle, $newLayout);

        return $this;
    }

    public function prepareForTransitionFromLayout(int $oldLayout): static
    {
        ExtNSCollectionViewLayout::prepareForTransitionFromLayout($this->handle, $oldLayout);

        return $this;
    }

    public function finalizeLayoutTransition(): static
    {
        ExtNSCollectionViewLayout::finalizeLayoutTransition($this->handle);

        return $this;
    }

    public function initialLayoutAttributesForAppearingItemAtIndexPath(int $itemIndexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::initialLayoutAttributesForAppearingItemAtIndexPath($this->handle, $itemIndexPath));
    }

    public function finalLayoutAttributesForDisappearingItemAtIndexPath(int $itemIndexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::finalLayoutAttributesForDisappearingItemAtIndexPath($this->handle, $itemIndexPath));
    }

    public function initialLayoutAttributesForAppearingSupplementaryElementOfKindAtIndexPath(string $elementKind, int $elementIndexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::initialLayoutAttributesForAppearingSupplementaryElementOfKindAtIndexPath($this->handle, $elementKind, $elementIndexPath));
    }

    public function finalLayoutAttributesForDisappearingSupplementaryElementOfKindAtIndexPath(string $elementKind, int $elementIndexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::finalLayoutAttributesForDisappearingSupplementaryElementOfKindAtIndexPath($this->handle, $elementKind, $elementIndexPath));
    }

    public function initialLayoutAttributesForAppearingDecorationElementOfKindAtIndexPath(string $elementKind, int $decorationIndexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::initialLayoutAttributesForAppearingDecorationElementOfKindAtIndexPath($this->handle, $elementKind, $decorationIndexPath));
    }

    public function finalLayoutAttributesForDisappearingDecorationElementOfKindAtIndexPath(string $elementKind, int $decorationIndexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayout::finalLayoutAttributesForDisappearingDecorationElementOfKindAtIndexPath($this->handle, $elementKind, $decorationIndexPath));
    }

    public function indexPathsToDeleteForSupplementaryViewOfKind(string $elementKind): array
    {
        return ExtNSCollectionViewLayout::indexPathsToDeleteForSupplementaryViewOfKind($this->handle, $elementKind);
    }

    public function indexPathsToDeleteForDecorationViewOfKind(string $elementKind): array
    {
        return ExtNSCollectionViewLayout::indexPathsToDeleteForDecorationViewOfKind($this->handle, $elementKind);
    }

    public function indexPathsToInsertForSupplementaryViewOfKind(string $elementKind): array
    {
        return ExtNSCollectionViewLayout::indexPathsToInsertForSupplementaryViewOfKind($this->handle, $elementKind);
    }

    public function indexPathsToInsertForDecorationViewOfKind(string $elementKind): array
    {
        return ExtNSCollectionViewLayout::indexPathsToInsertForDecorationViewOfKind($this->handle, $elementKind);
    }
}
