<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSCollectionViewLayoutInvalidationContext\NSCollectionViewLayoutInvalidationContext as ExtNSCollectionViewLayoutInvalidationContext;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSCollectionViewLayoutInvalidationContext extends ObjCObject
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewLayoutInvalidationContext::init());
    }

    public function invalidateEverything(): bool
    {
        return ExtNSCollectionViewLayoutInvalidationContext::invalidateEverything($this->handle);
    }

    public function invalidateDataSourceCounts(): bool
    {
        return ExtNSCollectionViewLayoutInvalidationContext::invalidateDataSourceCounts($this->handle);
    }

    public function invalidateItemsAtIndexPaths(array $indexPaths): static
    {
        ExtNSCollectionViewLayoutInvalidationContext::invalidateItemsAtIndexPaths($this->handle, $indexPaths);

        return $this;
    }

    public function invalidateSupplementaryElementsOfKindAtIndexPaths(string $elementKind, array $indexPaths): static
    {
        ExtNSCollectionViewLayoutInvalidationContext::invalidateSupplementaryElementsOfKindAtIndexPaths($this->handle, $elementKind, $indexPaths);

        return $this;
    }

    public function invalidateDecorationElementsOfKindAtIndexPaths(string $elementKind, array $indexPaths): static
    {
        ExtNSCollectionViewLayoutInvalidationContext::invalidateDecorationElementsOfKindAtIndexPaths($this->handle, $elementKind, $indexPaths);

        return $this;
    }

    public function invalidatedItemIndexPaths(): array
    {
        return ExtNSCollectionViewLayoutInvalidationContext::invalidatedItemIndexPaths($this->handle);
    }

    public function invalidatedSupplementaryIndexPaths(): int
    {
        return ExtNSCollectionViewLayoutInvalidationContext::invalidatedSupplementaryIndexPaths($this->handle);
    }

    public function invalidatedDecorationIndexPaths(): int
    {
        return ExtNSCollectionViewLayoutInvalidationContext::invalidatedDecorationIndexPaths($this->handle);
    }

    public function contentOffsetAdjustment(): NSPoint
    {
        return NSPoint::fromArray(ExtNSCollectionViewLayoutInvalidationContext::contentOffsetAdjustment($this->handle));
    }

    public function setContentOffsetAdjustment(NSPoint $contentOffsetAdjustment): static
    {
        ExtNSCollectionViewLayoutInvalidationContext::setContentOffsetAdjustment(...[$this->handle, ...$contentOffsetAdjustment->toArgs()]);

        return $this;
    }

    public function contentSizeAdjustment(): NSSize
    {
        return NSSize::fromArray(ExtNSCollectionViewLayoutInvalidationContext::contentSizeAdjustment($this->handle));
    }

    public function setContentSizeAdjustment(NSSize $contentSizeAdjustment): static
    {
        ExtNSCollectionViewLayoutInvalidationContext::setContentSizeAdjustment(...[$this->handle, ...$contentSizeAdjustment->toArgs()]);

        return $this;
    }
}
