<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSCollectionViewGridLayout\NSCollectionViewGridLayout as ExtNSCollectionViewGridLayout;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSCollectionViewGridLayout extends NSCollectionViewLayout
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewGridLayout::init());
    }

    public function margins(): NSEdgeInsets
    {
        return NSEdgeInsets::fromArray(ExtNSCollectionViewGridLayout::margins($this->handle));
    }

    public function setMargins(NSEdgeInsets $margins): static
    {
        ExtNSCollectionViewGridLayout::setMargins(...[$this->handle, ...$margins->toArgs()]);

        return $this;
    }

    public function minimumInteritemSpacing(): float
    {
        return ExtNSCollectionViewGridLayout::minimumInteritemSpacing($this->handle);
    }

    public function setMinimumInteritemSpacing(float $minimumInteritemSpacing): static
    {
        ExtNSCollectionViewGridLayout::setMinimumInteritemSpacing($this->handle, $minimumInteritemSpacing);

        return $this;
    }

    public function minimumLineSpacing(): float
    {
        return ExtNSCollectionViewGridLayout::minimumLineSpacing($this->handle);
    }

    public function setMinimumLineSpacing(float $minimumLineSpacing): static
    {
        ExtNSCollectionViewGridLayout::setMinimumLineSpacing($this->handle, $minimumLineSpacing);

        return $this;
    }

    public function maximumNumberOfRows(): int
    {
        return ExtNSCollectionViewGridLayout::maximumNumberOfRows($this->handle);
    }

    public function setMaximumNumberOfRows(int $maximumNumberOfRows): static
    {
        ExtNSCollectionViewGridLayout::setMaximumNumberOfRows($this->handle, $maximumNumberOfRows);

        return $this;
    }

    public function maximumNumberOfColumns(): int
    {
        return ExtNSCollectionViewGridLayout::maximumNumberOfColumns($this->handle);
    }

    public function setMaximumNumberOfColumns(int $maximumNumberOfColumns): static
    {
        ExtNSCollectionViewGridLayout::setMaximumNumberOfColumns($this->handle, $maximumNumberOfColumns);

        return $this;
    }

    public function minimumItemSize(): NSSize
    {
        return NSSize::fromArray(ExtNSCollectionViewGridLayout::minimumItemSize($this->handle));
    }

    public function setMinimumItemSize(NSSize $minimumItemSize): static
    {
        ExtNSCollectionViewGridLayout::setMinimumItemSize(...[$this->handle, ...$minimumItemSize->toArgs()]);

        return $this;
    }

    public function maximumItemSize(): NSSize
    {
        return NSSize::fromArray(ExtNSCollectionViewGridLayout::maximumItemSize($this->handle));
    }

    public function setMaximumItemSize(NSSize $maximumItemSize): static
    {
        ExtNSCollectionViewGridLayout::setMaximumItemSize(...[$this->handle, ...$maximumItemSize->toArgs()]);

        return $this;
    }

    public function backgroundColors(): array
    {
        return ExtNSCollectionViewGridLayout::backgroundColors($this->handle);
    }

    public function setBackgroundColors(array $backgroundColors): static
    {
        ExtNSCollectionViewGridLayout::setBackgroundColors($this->handle, $backgroundColors);

        return $this;
    }
}
