<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSControl\NSControl as ExtNSControl;
use Jovian\Bindings\AppKit\Enums\NSControlSize;
use Jovian\Bindings\AppKit\Enums\NSLineBreakMode;
use Jovian\Bindings\AppKit\Enums\NSTextAlignment;
use Jovian\Bindings\AppKit\Enums\NSWritingDirection;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSControl extends NSView
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSControl::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function target(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSControl::target($this->handle));
    }

    public function setTarget(int $target): static
    {
        ExtNSControl::setTarget($this->handle, $target);

        return $this;
    }

    public function action(): mixed
    {
        return ExtNSControl::action($this->handle);
    }

    public function setAction(string $action): static
    {
        ExtNSControl::setAction($this->handle, $action);

        return $this;
    }

    public function tag(): int
    {
        return ExtNSControl::tag($this->handle);
    }

    public function setTag(int $tag): static
    {
        ExtNSControl::setTag($this->handle, $tag);

        return $this;
    }

    public function ignoresMultiClick(): bool
    {
        return ExtNSControl::ignoresMultiClick($this->handle);
    }

    public function setIgnoresMultiClick(bool $ignoresMultiClick): static
    {
        ExtNSControl::setIgnoresMultiClick($this->handle, $ignoresMultiClick);

        return $this;
    }

    public function isContinuous(): bool
    {
        return ExtNSControl::isContinuous($this->handle);
    }

    public function setContinuous(bool $continuous): static
    {
        ExtNSControl::setContinuous($this->handle, $continuous);

        return $this;
    }

    public function isEnabled(): bool
    {
        return ExtNSControl::isEnabled($this->handle);
    }

    public function setEnabled(bool $enabled): static
    {
        ExtNSControl::setEnabled($this->handle, $enabled);

        return $this;
    }

    public function refusesFirstResponder(): bool
    {
        return ExtNSControl::refusesFirstResponder($this->handle);
    }

    public function setRefusesFirstResponder(bool $refusesFirstResponder): static
    {
        ExtNSControl::setRefusesFirstResponder($this->handle, $refusesFirstResponder);

        return $this;
    }

    public function isHighlighted(): bool
    {
        return ExtNSControl::isHighlighted($this->handle);
    }

    public function setHighlighted(bool $highlighted): static
    {
        ExtNSControl::setHighlighted($this->handle, $highlighted);

        return $this;
    }

    public function controlSize(): NSControlSize|int
    {
        return ExtNSControl::controlSize($this->handle);
    }

    public function setControlSize(NSControlSize|int $controlSize): static
    {
        ExtNSControl::setControlSize($this->handle, $controlSize instanceof \BackedEnum ? $controlSize->value : $controlSize);

        return $this;
    }

    public function formatter(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSControl::formatter($this->handle));
    }

    public function setFormatter(int $formatter): static
    {
        ExtNSControl::setFormatter($this->handle, $formatter);

        return $this;
    }

    public function objectValue(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSControl::objectValue($this->handle));
    }

    public function setObjectValue(int $objectValue): static
    {
        ExtNSControl::setObjectValue($this->handle, $objectValue);

        return $this;
    }

    public function stringValue(): ?string
    {
        return ExtNSControl::stringValue($this->handle);
    }

    public function setStringValue(string $stringValue): static
    {
        ExtNSControl::setStringValue($this->handle, $stringValue);

        return $this;
    }

    public function intValue(): int
    {
        return ExtNSControl::intValue($this->handle);
    }

    public function setIntValue(int $intValue): static
    {
        ExtNSControl::setIntValue($this->handle, $intValue);

        return $this;
    }

    public function integerValue(): int
    {
        return ExtNSControl::integerValue($this->handle);
    }

    public function setIntegerValue(int $integerValue): static
    {
        ExtNSControl::setIntegerValue($this->handle, $integerValue);

        return $this;
    }

    public function floatValue(): float
    {
        return ExtNSControl::floatValue($this->handle);
    }

    public function setFloatValue(float $floatValue): static
    {
        ExtNSControl::setFloatValue($this->handle, $floatValue);

        return $this;
    }

    public function doubleValue(): float
    {
        return ExtNSControl::doubleValue($this->handle);
    }

    public function setDoubleValue(float $doubleValue): static
    {
        ExtNSControl::setDoubleValue($this->handle, $doubleValue);

        return $this;
    }

    public function sizeThatFits(NSSize $size): NSSize
    {
        return NSSize::fromArray(ExtNSControl::sizeThatFits(...[$this->handle, ...$size->toArgs()]));
    }

    public function sizeToFit(): static
    {
        ExtNSControl::sizeToFit($this->handle);

        return $this;
    }

    public function sendActionOn(int $mask): int
    {
        return ExtNSControl::sendActionOn($this->handle, $mask);
    }

    public function sendActionTo(string $action, int $target): bool
    {
        return ExtNSControl::sendActionTo($this->handle, $action, $target);
    }

    public function takeIntValueFrom(int $sender): static
    {
        ExtNSControl::takeIntValueFrom($this->handle, $sender);

        return $this;
    }

    public function takeFloatValueFrom(int $sender): static
    {
        ExtNSControl::takeFloatValueFrom($this->handle, $sender);

        return $this;
    }

    public function takeDoubleValueFrom(int $sender): static
    {
        ExtNSControl::takeDoubleValueFrom($this->handle, $sender);

        return $this;
    }

    public function takeStringValueFrom(int $sender): static
    {
        ExtNSControl::takeStringValueFrom($this->handle, $sender);

        return $this;
    }

    public function takeObjectValueFrom(int $sender): static
    {
        ExtNSControl::takeObjectValueFrom($this->handle, $sender);

        return $this;
    }

    public function takeIntegerValueFrom(int $sender): static
    {
        ExtNSControl::takeIntegerValueFrom($this->handle, $sender);

        return $this;
    }

    public function mouseDown(int $event): static
    {
        ExtNSControl::mouseDown($this->handle, $event);

        return $this;
    }

    public function performClick(int $sender): static
    {
        ExtNSControl::performClick($this->handle, $sender);

        return $this;
    }

    public function font(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSControl::font($this->handle));
    }

    public function setFont(int $font): static
    {
        ExtNSControl::setFont($this->handle, $font);

        return $this;
    }

    public function usesSingleLineMode(): bool
    {
        return ExtNSControl::usesSingleLineMode($this->handle);
    }

    public function setUsesSingleLineMode(bool $usesSingleLineMode): static
    {
        ExtNSControl::setUsesSingleLineMode($this->handle, $usesSingleLineMode);

        return $this;
    }

    public function lineBreakMode(): NSLineBreakMode|int
    {
        return ExtNSControl::lineBreakMode($this->handle);
    }

    public function setLineBreakMode(NSLineBreakMode|int $lineBreakMode): static
    {
        ExtNSControl::setLineBreakMode($this->handle, $lineBreakMode instanceof \BackedEnum ? $lineBreakMode->value : $lineBreakMode);

        return $this;
    }

    public function alignment(): NSTextAlignment|int
    {
        return ExtNSControl::alignment($this->handle);
    }

    public function setAlignment(NSTextAlignment|int $alignment): static
    {
        ExtNSControl::setAlignment($this->handle, $alignment instanceof \BackedEnum ? $alignment->value : $alignment);

        return $this;
    }

    public function baseWritingDirection(): NSWritingDirection|int
    {
        return ExtNSControl::baseWritingDirection($this->handle);
    }

    public function setBaseWritingDirection(NSWritingDirection|int $baseWritingDirection): static
    {
        ExtNSControl::setBaseWritingDirection($this->handle, $baseWritingDirection instanceof \BackedEnum ? $baseWritingDirection->value : $baseWritingDirection);

        return $this;
    }

    public function allowsExpansionToolTips(): bool
    {
        return ExtNSControl::allowsExpansionToolTips($this->handle);
    }

    public function setAllowsExpansionToolTips(bool $allowsExpansionToolTips): static
    {
        ExtNSControl::setAllowsExpansionToolTips($this->handle, $allowsExpansionToolTips);

        return $this;
    }

    public function expansionFrameWithFrame(NSRect $contentFrame): NSRect
    {
        return NSRect::fromArray(ExtNSControl::expansionFrameWithFrame(...[$this->handle, ...$contentFrame->toArgs()]));
    }

    public function drawWithExpansionFrameInView(NSRect $contentFrame, int $view): static
    {
        ExtNSControl::drawWithExpansionFrameInView(...[$this->handle, ...$contentFrame->toArgs(), $view]);

        return $this;
    }

    public function currentEditor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSControl::currentEditor($this->handle));
    }

    public function abortEditing(): bool
    {
        return ExtNSControl::abortEditing($this->handle);
    }

    public function validateEditing(): static
    {
        ExtNSControl::validateEditing($this->handle);

        return $this;
    }

    public function editWithFrameEditorDelegateEvent(NSRect $rect, int $textObj, int $delegate, int $event): static
    {
        ExtNSControl::editWithFrameEditorDelegateEvent(...[$this->handle, ...$rect->toArgs(), $textObj, $delegate, $event]);

        return $this;
    }

    public function selectWithFrameEditorDelegateStartLength(NSRect $rect, int $textObj, int $delegate, int $selStart, int $selLength): static
    {
        ExtNSControl::selectWithFrameEditorDelegateStartLength(...[$this->handle, ...$rect->toArgs(), $textObj, $delegate, $selStart, $selLength]);

        return $this;
    }

    public function endEditing(int $textObj): static
    {
        ExtNSControl::endEditing($this->handle, $textObj);

        return $this;
    }

    public function cell(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSControl::cell($this->handle));
    }

    public function setCell(int $cell): static
    {
        ExtNSControl::setCell($this->handle, $cell);

        return $this;
    }

    public function selectedCell(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSControl::selectedCell($this->handle));
    }

    public function selectedTag(): int
    {
        return ExtNSControl::selectedTag($this->handle);
    }

    public function updateCell(int $cell): static
    {
        ExtNSControl::updateCell($this->handle, $cell);

        return $this;
    }

    public function updateCellInside(int $cell): static
    {
        ExtNSControl::updateCellInside($this->handle, $cell);

        return $this;
    }

    public function drawCellInside(int $cell): static
    {
        ExtNSControl::drawCellInside($this->handle, $cell);

        return $this;
    }

    public function drawCell(int $cell): static
    {
        ExtNSControl::drawCell($this->handle, $cell);

        return $this;
    }

    public function selectCell(int $cell): static
    {
        ExtNSControl::selectCell($this->handle, $cell);

        return $this;
    }
}
