<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSCollectionView\NSCollectionView as ExtNSCollectionView;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSCollectionView extends NSView
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function dataSource(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::dataSource($this->handle));
    }

    public function setDataSource(int $dataSource): static
    {
        ExtNSCollectionView::setDataSource($this->handle, $dataSource);

        return $this;
    }

    public function prefetchDataSource(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::prefetchDataSource($this->handle));
    }

    public function setPrefetchDataSource(int $prefetchDataSource): static
    {
        ExtNSCollectionView::setPrefetchDataSource($this->handle, $prefetchDataSource);

        return $this;
    }

    public function content(): array
    {
        return ExtNSCollectionView::content($this->handle);
    }

    public function setContent(array $content): static
    {
        ExtNSCollectionView::setContent($this->handle, $content);

        return $this;
    }

    public function reloadData(): static
    {
        ExtNSCollectionView::reloadData($this->handle);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSCollectionView::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function backgroundView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::backgroundView($this->handle));
    }

    public function setBackgroundView(int $backgroundView): static
    {
        ExtNSCollectionView::setBackgroundView($this->handle, $backgroundView);

        return $this;
    }

    public function backgroundViewScrollsWithContent(): bool
    {
        return ExtNSCollectionView::backgroundViewScrollsWithContent($this->handle);
    }

    public function setBackgroundViewScrollsWithContent(bool $backgroundViewScrollsWithContent): static
    {
        ExtNSCollectionView::setBackgroundViewScrollsWithContent($this->handle, $backgroundViewScrollsWithContent);

        return $this;
    }

    public function collectionViewLayout(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::collectionViewLayout($this->handle));
    }

    public function setCollectionViewLayout(int $collectionViewLayout): static
    {
        ExtNSCollectionView::setCollectionViewLayout($this->handle, $collectionViewLayout);

        return $this;
    }

    public function layoutAttributesForItemAtIndexPath(int $indexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::layoutAttributesForItemAtIndexPath($this->handle, $indexPath));
    }

    public function layoutAttributesForSupplementaryElementOfKindAtIndexPath(int $kind, int $indexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::layoutAttributesForSupplementaryElementOfKindAtIndexPath($this->handle, $kind, $indexPath));
    }

    public function frameForItemAtIndex(int $index): NSRect
    {
        return NSRect::fromArray(ExtNSCollectionView::frameForItemAtIndex($this->handle, $index));
    }

    public function frameForItemAtIndexWithNumberOfItems(int $index, int $numberOfItems): NSRect
    {
        return NSRect::fromArray(ExtNSCollectionView::frameForItemAtIndexWithNumberOfItems($this->handle, $index, $numberOfItems));
    }

    public function backgroundColors(): array
    {
        return ExtNSCollectionView::backgroundColors($this->handle);
    }

    public function setBackgroundColors(array $backgroundColors): static
    {
        ExtNSCollectionView::setBackgroundColors($this->handle, $backgroundColors);

        return $this;
    }

    public function numberOfSections(): int
    {
        return ExtNSCollectionView::numberOfSections($this->handle);
    }

    public function numberOfItemsInSection(int $section): int
    {
        return ExtNSCollectionView::numberOfItemsInSection($this->handle, $section);
    }

    public function isFirstResponder(): bool
    {
        return ExtNSCollectionView::isFirstResponder($this->handle);
    }

    public function isSelectable(): bool
    {
        return ExtNSCollectionView::isSelectable($this->handle);
    }

    public function setSelectable(bool $selectable): static
    {
        ExtNSCollectionView::setSelectable($this->handle, $selectable);

        return $this;
    }

    public function allowsEmptySelection(): bool
    {
        return ExtNSCollectionView::allowsEmptySelection($this->handle);
    }

    public function setAllowsEmptySelection(bool $allowsEmptySelection): static
    {
        ExtNSCollectionView::setAllowsEmptySelection($this->handle, $allowsEmptySelection);

        return $this;
    }

    public function allowsMultipleSelection(): bool
    {
        return ExtNSCollectionView::allowsMultipleSelection($this->handle);
    }

    public function setAllowsMultipleSelection(bool $allowsMultipleSelection): static
    {
        ExtNSCollectionView::setAllowsMultipleSelection($this->handle, $allowsMultipleSelection);

        return $this;
    }

    public function selectionIndexes(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::selectionIndexes($this->handle));
    }

    public function setSelectionIndexes(int $selectionIndexes): static
    {
        ExtNSCollectionView::setSelectionIndexes($this->handle, $selectionIndexes);

        return $this;
    }

    public function selectionIndexPaths(): array
    {
        return ExtNSCollectionView::selectionIndexPaths($this->handle);
    }

    public function setSelectionIndexPaths(array $selectionIndexPaths): static
    {
        ExtNSCollectionView::setSelectionIndexPaths($this->handle, $selectionIndexPaths);

        return $this;
    }

    public function selectItemsAtIndexPathsScrollPosition(array $indexPaths, int $scrollPosition): static
    {
        ExtNSCollectionView::selectItemsAtIndexPathsScrollPosition($this->handle, $indexPaths, $scrollPosition);

        return $this;
    }

    public function deselectItemsAtIndexPaths(array $indexPaths): static
    {
        ExtNSCollectionView::deselectItemsAtIndexPaths($this->handle, $indexPaths);

        return $this;
    }

    public function selectAll(int $sender): static
    {
        ExtNSCollectionView::selectAll($this->handle, $sender);

        return $this;
    }

    public function deselectAll(int $sender): static
    {
        ExtNSCollectionView::deselectAll($this->handle, $sender);

        return $this;
    }

    public function registerNibForItemWithIdentifier(int $nib, int $identifier): static
    {
        ExtNSCollectionView::registerNibForItemWithIdentifier($this->handle, $nib, $identifier);

        return $this;
    }

    public function registerNibForSupplementaryViewOfKindWithIdentifier(int $nib, int $kind, int $identifier): static
    {
        ExtNSCollectionView::registerNibForSupplementaryViewOfKindWithIdentifier($this->handle, $nib, $kind, $identifier);

        return $this;
    }

    public function makeItemWithIdentifierForIndexPath(int $identifier, int $indexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::makeItemWithIdentifierForIndexPath($this->handle, $identifier, $indexPath));
    }

    public function makeSupplementaryViewOfKindWithIdentifierForIndexPath(int $elementKind, int $identifier, int $indexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::makeSupplementaryViewOfKindWithIdentifierForIndexPath($this->handle, $elementKind, $identifier, $indexPath));
    }

    public function itemAtIndex(int $index): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::itemAtIndex($this->handle, $index));
    }

    public function itemAtIndexPath(int $indexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::itemAtIndexPath($this->handle, $indexPath));
    }

    public function visibleItems(): array
    {
        return ExtNSCollectionView::visibleItems($this->handle);
    }

    public function indexPathsForVisibleItems(): array
    {
        return ExtNSCollectionView::indexPathsForVisibleItems($this->handle);
    }

    public function indexPathForItem(int $item): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::indexPathForItem($this->handle, $item));
    }

    public function indexPathForItemAtPoint(NSPoint $point): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::indexPathForItemAtPoint(...[$this->handle, ...$point->toArgs()]));
    }

    public function supplementaryViewForElementKindAtIndexPath(int $elementKind, int $indexPath): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionView::supplementaryViewForElementKindAtIndexPath($this->handle, $elementKind, $indexPath));
    }

    public function visibleSupplementaryViewsOfKind(int $elementKind): array
    {
        return ExtNSCollectionView::visibleSupplementaryViewsOfKind($this->handle, $elementKind);
    }

    public function indexPathsForVisibleSupplementaryElementsOfKind(int $elementKind): array
    {
        return ExtNSCollectionView::indexPathsForVisibleSupplementaryElementsOfKind($this->handle, $elementKind);
    }

    public function insertSections(int $sections): static
    {
        ExtNSCollectionView::insertSections($this->handle, $sections);

        return $this;
    }

    public function deleteSections(int $sections): static
    {
        ExtNSCollectionView::deleteSections($this->handle, $sections);

        return $this;
    }

    public function reloadSections(int $sections): static
    {
        ExtNSCollectionView::reloadSections($this->handle, $sections);

        return $this;
    }

    public function moveSectionToSection(int $section, int $newSection): static
    {
        ExtNSCollectionView::moveSectionToSection($this->handle, $section, $newSection);

        return $this;
    }

    public function insertItemsAtIndexPaths(array $indexPaths): static
    {
        ExtNSCollectionView::insertItemsAtIndexPaths($this->handle, $indexPaths);

        return $this;
    }

    public function deleteItemsAtIndexPaths(array $indexPaths): static
    {
        ExtNSCollectionView::deleteItemsAtIndexPaths($this->handle, $indexPaths);

        return $this;
    }

    public function reloadItemsAtIndexPaths(array $indexPaths): static
    {
        ExtNSCollectionView::reloadItemsAtIndexPaths($this->handle, $indexPaths);

        return $this;
    }

    public function moveItemAtIndexPathToIndexPath(int $indexPath, int $newIndexPath): static
    {
        ExtNSCollectionView::moveItemAtIndexPathToIndexPath($this->handle, $indexPath, $newIndexPath);

        return $this;
    }

    public function toggleSectionCollapse(int $sender): static
    {
        ExtNSCollectionView::toggleSectionCollapse($this->handle, $sender);

        return $this;
    }

    public function scrollToItemsAtIndexPathsScrollPosition(array $indexPaths, int $scrollPosition): static
    {
        ExtNSCollectionView::scrollToItemsAtIndexPathsScrollPosition($this->handle, $indexPaths, $scrollPosition);

        return $this;
    }

    public function setDraggingSourceOperationMaskForLocal(int $dragOperationMask, bool $localDestination): static
    {
        ExtNSCollectionView::setDraggingSourceOperationMaskForLocal($this->handle, $dragOperationMask, $localDestination);

        return $this;
    }
}
