<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSColorWell\NSColorWell as ExtNSColorWell;
use Jovian\Bindings\AppKit\Enums\NSColorWellStyle;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSColorWell extends NSControl
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSColorWell::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public static function colorWellWithStyle(NSColorWellStyle|int $style): ?ObjCObject
    {
        return ObjCObject::box(ExtNSColorWell::colorWellWithStyle($style instanceof \BackedEnum ? $style->value : $style));
    }

    public function deactivate(): static
    {
        ExtNSColorWell::deactivate($this->handle);

        return $this;
    }

    public function activate(bool $exclusive): static
    {
        ExtNSColorWell::activate($this->handle, $exclusive);

        return $this;
    }

    public function isActive(): bool
    {
        return ExtNSColorWell::isActive($this->handle);
    }

    public function drawWellInside(NSRect $insideRect): static
    {
        ExtNSColorWell::drawWellInside(...[$this->handle, ...$insideRect->toArgs()]);

        return $this;
    }

    public function takeColorFrom(int $sender): static
    {
        ExtNSColorWell::takeColorFrom($this->handle, $sender);

        return $this;
    }

    public function color(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSColorWell::color($this->handle));
    }

    public function setColor(int $color): static
    {
        ExtNSColorWell::setColor($this->handle, $color);

        return $this;
    }

    public function colorWellStyle(): NSColorWellStyle|int
    {
        return ExtNSColorWell::colorWellStyle($this->handle);
    }

    public function setColorWellStyle(NSColorWellStyle|int $colorWellStyle): static
    {
        ExtNSColorWell::setColorWellStyle($this->handle, $colorWellStyle instanceof \BackedEnum ? $colorWellStyle->value : $colorWellStyle);

        return $this;
    }

    public function image(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSColorWell::image($this->handle));
    }

    public function setImage(int $image): static
    {
        ExtNSColorWell::setImage($this->handle, $image);

        return $this;
    }

    public function pulldownTarget(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSColorWell::pulldownTarget($this->handle));
    }

    public function setPulldownTarget(int $pulldownTarget): static
    {
        ExtNSColorWell::setPulldownTarget($this->handle, $pulldownTarget);

        return $this;
    }

    public function pulldownAction(): mixed
    {
        return ExtNSColorWell::pulldownAction($this->handle);
    }

    public function setPulldownAction(string $pulldownAction): static
    {
        ExtNSColorWell::setPulldownAction($this->handle, $pulldownAction);

        return $this;
    }

    public function supportsAlpha(): bool
    {
        return ExtNSColorWell::supportsAlpha($this->handle);
    }

    public function setSupportsAlpha(bool $supportsAlpha): static
    {
        ExtNSColorWell::setSupportsAlpha($this->handle, $supportsAlpha);

        return $this;
    }
}
