<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSCollectionViewItem\NSCollectionViewItem as ExtNSCollectionViewItem;
use Jovian\Bindings\AppKit\Enums\NSCollectionViewItemHighlightState;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSCollectionViewItem extends NSViewController
{
    public static function initWithNibNameBundle(string $nibNameOrNil, int $nibBundleOrNil): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewItem::initWithNibNameBundle($nibNameOrNil, $nibBundleOrNil));
    }

    public function collectionView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewItem::collectionView($this->handle));
    }

    public function isSelected(): bool
    {
        return ExtNSCollectionViewItem::isSelected($this->handle);
    }

    public function setSelected(bool $selected): static
    {
        ExtNSCollectionViewItem::setSelected($this->handle, $selected);

        return $this;
    }

    public function highlightState(): NSCollectionViewItemHighlightState|int
    {
        return ExtNSCollectionViewItem::highlightState($this->handle);
    }

    public function setHighlightState(NSCollectionViewItemHighlightState|int $highlightState): static
    {
        ExtNSCollectionViewItem::setHighlightState($this->handle, $highlightState instanceof \BackedEnum ? $highlightState->value : $highlightState);

        return $this;
    }

    public function imageView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewItem::imageView($this->handle));
    }

    public function setImageView(int $imageView): static
    {
        ExtNSCollectionViewItem::setImageView($this->handle, $imageView);

        return $this;
    }

    public function textField(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewItem::textField($this->handle));
    }

    public function setTextField(int $textField): static
    {
        ExtNSCollectionViewItem::setTextField($this->handle, $textField);

        return $this;
    }

    public function draggingImageComponents(): array
    {
        return ExtNSCollectionViewItem::draggingImageComponents($this->handle);
    }
}
