<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSCollectionViewUpdateItem\NSCollectionViewUpdateItem as ExtNSCollectionViewUpdateItem;
use Jovian\Bindings\AppKit\Enums\NSCollectionUpdateAction;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSCollectionViewUpdateItem extends ObjCObject
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewUpdateItem::init());
    }

    public function indexPathBeforeUpdate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewUpdateItem::indexPathBeforeUpdate($this->handle));
    }

    public function indexPathAfterUpdate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSCollectionViewUpdateItem::indexPathAfterUpdate($this->handle));
    }

    public function updateAction(): NSCollectionUpdateAction|int
    {
        return ExtNSCollectionViewUpdateItem::updateAction($this->handle);
    }
}
