<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSDatePicker\NSDatePicker as ExtNSDatePicker;
use Jovian\Bindings\AppKit\Enums\NSDatePickerMode;
use Jovian\Bindings\AppKit\Enums\NSDatePickerStyle;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSDatePicker extends NSControl
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePicker::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function datePickerStyle(): NSDatePickerStyle|int
    {
        return ExtNSDatePicker::datePickerStyle($this->handle);
    }

    public function setDatePickerStyle(NSDatePickerStyle|int $datePickerStyle): static
    {
        ExtNSDatePicker::setDatePickerStyle($this->handle, $datePickerStyle instanceof \BackedEnum ? $datePickerStyle->value : $datePickerStyle);

        return $this;
    }

    public function isBezeled(): bool
    {
        return ExtNSDatePicker::isBezeled($this->handle);
    }

    public function setBezeled(bool $bezeled): static
    {
        ExtNSDatePicker::setBezeled($this->handle, $bezeled);

        return $this;
    }

    public function isBordered(): bool
    {
        return ExtNSDatePicker::isBordered($this->handle);
    }

    public function setBordered(bool $bordered): static
    {
        ExtNSDatePicker::setBordered($this->handle, $bordered);

        return $this;
    }

    public function drawsBackground(): bool
    {
        return ExtNSDatePicker::drawsBackground($this->handle);
    }

    public function setDrawsBackground(bool $drawsBackground): static
    {
        ExtNSDatePicker::setDrawsBackground($this->handle, $drawsBackground);

        return $this;
    }

    public function backgroundColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePicker::backgroundColor($this->handle));
    }

    public function setBackgroundColor(int $backgroundColor): static
    {
        ExtNSDatePicker::setBackgroundColor($this->handle, $backgroundColor);

        return $this;
    }

    public function textColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePicker::textColor($this->handle));
    }

    public function setTextColor(int $textColor): static
    {
        ExtNSDatePicker::setTextColor($this->handle, $textColor);

        return $this;
    }

    public function datePickerMode(): NSDatePickerMode|int
    {
        return ExtNSDatePicker::datePickerMode($this->handle);
    }

    public function setDatePickerMode(NSDatePickerMode|int $datePickerMode): static
    {
        ExtNSDatePicker::setDatePickerMode($this->handle, $datePickerMode instanceof \BackedEnum ? $datePickerMode->value : $datePickerMode);

        return $this;
    }

    public function datePickerElements(): int
    {
        return ExtNSDatePicker::datePickerElements($this->handle);
    }

    public function setDatePickerElements(int $datePickerElements): static
    {
        ExtNSDatePicker::setDatePickerElements($this->handle, $datePickerElements);

        return $this;
    }

    public function calendar(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePicker::calendar($this->handle));
    }

    public function setCalendar(int $calendar): static
    {
        ExtNSDatePicker::setCalendar($this->handle, $calendar);

        return $this;
    }

    public function locale(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePicker::locale($this->handle));
    }

    public function setLocale(int $locale): static
    {
        ExtNSDatePicker::setLocale($this->handle, $locale);

        return $this;
    }

    public function timeZone(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePicker::timeZone($this->handle));
    }

    public function setTimeZone(int $timeZone): static
    {
        ExtNSDatePicker::setTimeZone($this->handle, $timeZone);

        return $this;
    }

    public function dateValue(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePicker::dateValue($this->handle));
    }

    public function setDateValue(int $dateValue): static
    {
        ExtNSDatePicker::setDateValue($this->handle, $dateValue);

        return $this;
    }

    public function timeInterval(): float
    {
        return ExtNSDatePicker::timeInterval($this->handle);
    }

    public function setTimeInterval(float $timeInterval): static
    {
        ExtNSDatePicker::setTimeInterval($this->handle, $timeInterval);

        return $this;
    }

    public function minDate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePicker::minDate($this->handle));
    }

    public function setMinDate(int $minDate): static
    {
        ExtNSDatePicker::setMinDate($this->handle, $minDate);

        return $this;
    }

    public function maxDate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePicker::maxDate($this->handle));
    }

    public function setMaxDate(int $maxDate): static
    {
        ExtNSDatePicker::setMaxDate($this->handle, $maxDate);

        return $this;
    }

    public function presentsCalendarOverlay(): bool
    {
        return ExtNSDatePicker::presentsCalendarOverlay($this->handle);
    }

    public function setPresentsCalendarOverlay(bool $presentsCalendarOverlay): static
    {
        ExtNSDatePicker::setPresentsCalendarOverlay($this->handle, $presentsCalendarOverlay);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePicker::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSDatePicker::setDelegate($this->handle, $delegate);

        return $this;
    }
}
