<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSDatePickerCell\NSDatePickerCell as ExtNSDatePickerCell;
use Jovian\Bindings\AppKit\Enums\NSDatePickerMode;
use Jovian\Bindings\AppKit\Enums\NSDatePickerStyle;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSDatePickerCell extends NSCell
{
    public static function initTextCell(string $string): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePickerCell::initTextCell($string));
    }

    public function datePickerStyle(): NSDatePickerStyle|int
    {
        return ExtNSDatePickerCell::datePickerStyle($this->handle);
    }

    public function setDatePickerStyle(NSDatePickerStyle|int $datePickerStyle): static
    {
        ExtNSDatePickerCell::setDatePickerStyle($this->handle, $datePickerStyle instanceof \BackedEnum ? $datePickerStyle->value : $datePickerStyle);

        return $this;
    }

    public function drawsBackground(): bool
    {
        return ExtNSDatePickerCell::drawsBackground($this->handle);
    }

    public function setDrawsBackground(bool $drawsBackground): static
    {
        ExtNSDatePickerCell::setDrawsBackground($this->handle, $drawsBackground);

        return $this;
    }

    public function backgroundColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePickerCell::backgroundColor($this->handle));
    }

    public function setBackgroundColor(int $backgroundColor): static
    {
        ExtNSDatePickerCell::setBackgroundColor($this->handle, $backgroundColor);

        return $this;
    }

    public function textColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePickerCell::textColor($this->handle));
    }

    public function setTextColor(int $textColor): static
    {
        ExtNSDatePickerCell::setTextColor($this->handle, $textColor);

        return $this;
    }

    public function datePickerMode(): NSDatePickerMode|int
    {
        return ExtNSDatePickerCell::datePickerMode($this->handle);
    }

    public function setDatePickerMode(NSDatePickerMode|int $datePickerMode): static
    {
        ExtNSDatePickerCell::setDatePickerMode($this->handle, $datePickerMode instanceof \BackedEnum ? $datePickerMode->value : $datePickerMode);

        return $this;
    }

    public function datePickerElements(): int
    {
        return ExtNSDatePickerCell::datePickerElements($this->handle);
    }

    public function setDatePickerElements(int $datePickerElements): static
    {
        ExtNSDatePickerCell::setDatePickerElements($this->handle, $datePickerElements);

        return $this;
    }

    public function calendar(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePickerCell::calendar($this->handle));
    }

    public function setCalendar(int $calendar): static
    {
        ExtNSDatePickerCell::setCalendar($this->handle, $calendar);

        return $this;
    }

    public function locale(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePickerCell::locale($this->handle));
    }

    public function setLocale(int $locale): static
    {
        ExtNSDatePickerCell::setLocale($this->handle, $locale);

        return $this;
    }

    public function timeZone(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePickerCell::timeZone($this->handle));
    }

    public function setTimeZone(int $timeZone): static
    {
        ExtNSDatePickerCell::setTimeZone($this->handle, $timeZone);

        return $this;
    }

    public function dateValue(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePickerCell::dateValue($this->handle));
    }

    public function setDateValue(int $dateValue): static
    {
        ExtNSDatePickerCell::setDateValue($this->handle, $dateValue);

        return $this;
    }

    public function timeInterval(): float
    {
        return ExtNSDatePickerCell::timeInterval($this->handle);
    }

    public function setTimeInterval(float $timeInterval): static
    {
        ExtNSDatePickerCell::setTimeInterval($this->handle, $timeInterval);

        return $this;
    }

    public function minDate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePickerCell::minDate($this->handle));
    }

    public function setMinDate(int $minDate): static
    {
        ExtNSDatePickerCell::setMinDate($this->handle, $minDate);

        return $this;
    }

    public function maxDate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePickerCell::maxDate($this->handle));
    }

    public function setMaxDate(int $maxDate): static
    {
        ExtNSDatePickerCell::setMaxDate($this->handle, $maxDate);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSDatePickerCell::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSDatePickerCell::setDelegate($this->handle, $delegate);

        return $this;
    }
}
