<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSFont\NSFont as ExtNSFont;
use Jovian\Bindings\AppKit\Enums\NSControlSize;
use Jovian\Bindings\AppKit\Enums\NSFontRenderingMode;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSFont extends ObjCObject
{
    public static function fontWithNameSize(string $fontName, float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::fontWithNameSize($fontName, $fontSize));
    }

    public static function fontWithDescriptorSize(int $fontDescriptor, float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::fontWithDescriptorSize($fontDescriptor, $fontSize));
    }

    public static function fontWithDescriptorTextTransform(int $fontDescriptor, int $textTransform): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::fontWithDescriptorTextTransform($fontDescriptor, $textTransform));
    }

    public static function userFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::userFontOfSize($fontSize));
    }

    public static function userFixedPitchFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::userFixedPitchFontOfSize($fontSize));
    }

    public static function setUserFont(int $font): void
    {
        ExtNSFont::setUserFont($font);
    }

    public static function setUserFixedPitchFont(int $font): void
    {
        ExtNSFont::setUserFixedPitchFont($font);
    }

    public static function systemFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::systemFontOfSize($fontSize));
    }

    public static function boldSystemFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::boldSystemFontOfSize($fontSize));
    }

    public static function labelFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::labelFontOfSize($fontSize));
    }

    public static function titleBarFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::titleBarFontOfSize($fontSize));
    }

    public static function menuFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::menuFontOfSize($fontSize));
    }

    public static function menuBarFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::menuBarFontOfSize($fontSize));
    }

    public static function messageFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::messageFontOfSize($fontSize));
    }

    public static function paletteFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::paletteFontOfSize($fontSize));
    }

    public static function toolTipsFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::toolTipsFontOfSize($fontSize));
    }

    public static function controlContentFontOfSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::controlContentFontOfSize($fontSize));
    }

    public static function systemFontOfSizeWeight(float $fontSize, float $weight): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::systemFontOfSizeWeight($fontSize, $weight));
    }

    public static function monospacedDigitSystemFontOfSizeWeight(float $fontSize, float $weight): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::monospacedDigitSystemFontOfSizeWeight($fontSize, $weight));
    }

    public static function systemFontOfSizeWeightWidth(float $fontSize, float $weight, float $width): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::systemFontOfSizeWeightWidth($fontSize, $weight, $width));
    }

    public static function monospacedSystemFontOfSizeWeight(float $fontSize, float $weight): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::monospacedSystemFontOfSizeWeight($fontSize, $weight));
    }

    public function fontWithSize(float $fontSize): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::fontWithSize($this->handle, $fontSize));
    }

    public static function systemFontSize(): float
    {
        return ExtNSFont::systemFontSize();
    }

    public static function smallSystemFontSize(): float
    {
        return ExtNSFont::smallSystemFontSize();
    }

    public static function labelFontSize(): float
    {
        return ExtNSFont::labelFontSize();
    }

    public static function systemFontSizeForControlSize(NSControlSize|int $controlSize): float
    {
        return ExtNSFont::systemFontSizeForControlSize($controlSize instanceof \BackedEnum ? $controlSize->value : $controlSize);
    }

    public function fontName(): ?string
    {
        return ExtNSFont::fontName($this->handle);
    }

    public function pointSize(): float
    {
        return ExtNSFont::pointSize($this->handle);
    }

    public function familyName(): mixed
    {
        return ExtNSFont::familyName($this->handle);
    }

    public function displayName(): mixed
    {
        return ExtNSFont::displayName($this->handle);
    }

    public function fontDescriptor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::fontDescriptor($this->handle));
    }

    public function textTransform(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::textTransform($this->handle));
    }

    public function numberOfGlyphs(): int
    {
        return ExtNSFont::numberOfGlyphs($this->handle);
    }

    public function mostCompatibleStringEncoding(): int
    {
        return ExtNSFont::mostCompatibleStringEncoding($this->handle);
    }

    public function coveredCharacterSet(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::coveredCharacterSet($this->handle));
    }

    public function boundingRectForFont(): NSRect
    {
        return NSRect::fromArray(ExtNSFont::boundingRectForFont($this->handle));
    }

    public function maximumAdvancement(): NSSize
    {
        return NSSize::fromArray(ExtNSFont::maximumAdvancement($this->handle));
    }

    public function ascender(): float
    {
        return ExtNSFont::ascender($this->handle);
    }

    public function descender(): float
    {
        return ExtNSFont::descender($this->handle);
    }

    public function leading(): float
    {
        return ExtNSFont::leading($this->handle);
    }

    public function underlinePosition(): float
    {
        return ExtNSFont::underlinePosition($this->handle);
    }

    public function underlineThickness(): float
    {
        return ExtNSFont::underlineThickness($this->handle);
    }

    public function italicAngle(): float
    {
        return ExtNSFont::italicAngle($this->handle);
    }

    public function capHeight(): float
    {
        return ExtNSFont::capHeight($this->handle);
    }

    public function xHeight(): float
    {
        return ExtNSFont::xHeight($this->handle);
    }

    public function isFixedPitch(): bool
    {
        return ExtNSFont::isFixedPitch($this->handle);
    }

    public function boundingRectForCGGlyph(int $glyph): NSRect
    {
        return NSRect::fromArray(ExtNSFont::boundingRectForCGGlyph($this->handle, $glyph));
    }

    public function advancementForCGGlyph(int $glyph): NSSize
    {
        return NSSize::fromArray(ExtNSFont::advancementForCGGlyph($this->handle, $glyph));
    }

    public function set(): static
    {
        ExtNSFont::set($this->handle);

        return $this;
    }

    public function setInContext(int $graphicsContext): static
    {
        ExtNSFont::setInContext($this->handle, $graphicsContext);

        return $this;
    }

    public function verticalFont(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::verticalFont($this->handle));
    }

    public function isVertical(): bool
    {
        return ExtNSFont::isVertical($this->handle);
    }

    public function glyphWithName(string $name): int
    {
        return ExtNSFont::glyphWithName($this->handle, $name);
    }

    public function boundingRectForGlyph(int $glyph): NSRect
    {
        return NSRect::fromArray(ExtNSFont::boundingRectForGlyph($this->handle, $glyph));
    }

    public function advancementForGlyph(int $glyph): NSSize
    {
        return NSSize::fromArray(ExtNSFont::advancementForGlyph($this->handle, $glyph));
    }

    public function printerFont(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::printerFont($this->handle));
    }

    public function screenFont(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::screenFont($this->handle));
    }

    public function screenFontWithRenderingMode(NSFontRenderingMode|int $renderingMode): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::screenFontWithRenderingMode($this->handle, $renderingMode instanceof \BackedEnum ? $renderingMode->value : $renderingMode));
    }

    public function renderingMode(): NSFontRenderingMode|int
    {
        return ExtNSFont::renderingMode($this->handle);
    }

    public static function preferredFontForTextStyleOptions(string $style, array $options): ?ObjCObject
    {
        return ObjCObject::box(ExtNSFont::preferredFontForTextStyleOptions($style, $options));
    }
}
