<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSGridRow\NSGridRow as ExtNSGridRow;
use Jovian\Bindings\AppKit\Enums\NSGridCellPlacement;
use Jovian\Bindings\AppKit\Enums\NSGridRowAlignment;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSGridRow extends ObjCObject
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSGridRow::init());
    }

    public function gridView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSGridRow::gridView($this->handle));
    }

    public function numberOfCells(): int
    {
        return ExtNSGridRow::numberOfCells($this->handle);
    }

    public function cellAtIndex(int $index): ?ObjCObject
    {
        return ObjCObject::box(ExtNSGridRow::cellAtIndex($this->handle, $index));
    }

    public function yPlacement(): NSGridCellPlacement|int
    {
        return ExtNSGridRow::yPlacement($this->handle);
    }

    public function setYPlacement(NSGridCellPlacement|int $yPlacement): static
    {
        ExtNSGridRow::setYPlacement($this->handle, $yPlacement instanceof \BackedEnum ? $yPlacement->value : $yPlacement);

        return $this;
    }

    public function rowAlignment(): NSGridRowAlignment|int
    {
        return ExtNSGridRow::rowAlignment($this->handle);
    }

    public function setRowAlignment(NSGridRowAlignment|int $rowAlignment): static
    {
        ExtNSGridRow::setRowAlignment($this->handle, $rowAlignment instanceof \BackedEnum ? $rowAlignment->value : $rowAlignment);

        return $this;
    }

    public function height(): float
    {
        return ExtNSGridRow::height($this->handle);
    }

    public function setHeight(float $height): static
    {
        ExtNSGridRow::setHeight($this->handle, $height);

        return $this;
    }

    public function topPadding(): float
    {
        return ExtNSGridRow::topPadding($this->handle);
    }

    public function setTopPadding(float $topPadding): static
    {
        ExtNSGridRow::setTopPadding($this->handle, $topPadding);

        return $this;
    }

    public function bottomPadding(): float
    {
        return ExtNSGridRow::bottomPadding($this->handle);
    }

    public function setBottomPadding(float $bottomPadding): static
    {
        ExtNSGridRow::setBottomPadding($this->handle, $bottomPadding);

        return $this;
    }

    public function isHidden(): bool
    {
        return ExtNSGridRow::isHidden($this->handle);
    }

    public function setHidden(bool $hidden): static
    {
        ExtNSGridRow::setHidden($this->handle, $hidden);

        return $this;
    }

    public function mergeCellsInRange(NSRange $range): static
    {
        ExtNSGridRow::mergeCellsInRange(...[$this->handle, ...$range->toArgs()]);

        return $this;
    }
}
