<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSGridCell\NSGridCell as ExtNSGridCell;
use Jovian\Bindings\AppKit\Enums\NSGridCellPlacement;
use Jovian\Bindings\AppKit\Enums\NSGridRowAlignment;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSGridCell extends ObjCObject
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSGridCell::init());
    }

    public function contentView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSGridCell::contentView($this->handle));
    }

    public function setContentView(int $contentView): static
    {
        ExtNSGridCell::setContentView($this->handle, $contentView);

        return $this;
    }

    public static function emptyContentView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSGridCell::emptyContentView());
    }

    public function row(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSGridCell::row($this->handle));
    }

    public function column(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSGridCell::column($this->handle));
    }

    public function xPlacement(): NSGridCellPlacement|int
    {
        return ExtNSGridCell::xPlacement($this->handle);
    }

    public function setXPlacement(NSGridCellPlacement|int $xPlacement): static
    {
        ExtNSGridCell::setXPlacement($this->handle, $xPlacement instanceof \BackedEnum ? $xPlacement->value : $xPlacement);

        return $this;
    }

    public function yPlacement(): NSGridCellPlacement|int
    {
        return ExtNSGridCell::yPlacement($this->handle);
    }

    public function setYPlacement(NSGridCellPlacement|int $yPlacement): static
    {
        ExtNSGridCell::setYPlacement($this->handle, $yPlacement instanceof \BackedEnum ? $yPlacement->value : $yPlacement);

        return $this;
    }

    public function rowAlignment(): NSGridRowAlignment|int
    {
        return ExtNSGridCell::rowAlignment($this->handle);
    }

    public function setRowAlignment(NSGridRowAlignment|int $rowAlignment): static
    {
        ExtNSGridCell::setRowAlignment($this->handle, $rowAlignment instanceof \BackedEnum ? $rowAlignment->value : $rowAlignment);

        return $this;
    }

    public function customPlacementConstraints(): array
    {
        return ExtNSGridCell::customPlacementConstraints($this->handle);
    }

    public function setCustomPlacementConstraints(array $customPlacementConstraints): static
    {
        ExtNSGridCell::setCustomPlacementConstraints($this->handle, $customPlacementConstraints);

        return $this;
    }
}
