<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSImageSymbolConfiguration\NSImageSymbolConfiguration as ExtNSImageSymbolConfiguration;
use Jovian\Bindings\AppKit\Enums\NSImageSymbolScale;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSImageSymbolConfiguration extends ObjCObject
{
    public static function configurationWithPointSizeWeightScale(float $pointSize, int $weight, NSImageSymbolScale|int $scale): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationWithPointSizeWeightScale($pointSize, $weight, $scale instanceof \BackedEnum ? $scale->value : $scale));
    }

    public static function configurationWithPointSizeWeight(float $pointSize, int $weight): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationWithPointSizeWeight($pointSize, $weight));
    }

    public static function configurationWithTextStyleScale(int $style, NSImageSymbolScale|int $scale): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationWithTextStyleScale($style, $scale instanceof \BackedEnum ? $scale->value : $scale));
    }

    public static function configurationWithTextStyle(int $style): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationWithTextStyle($style));
    }

    public static function configurationWithScale(NSImageSymbolScale|int $scale): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationWithScale($scale instanceof \BackedEnum ? $scale->value : $scale));
    }

    public static function configurationPreferringMonochrome(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationPreferringMonochrome());
    }

    public static function configurationPreferringHierarchical(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationPreferringHierarchical());
    }

    public static function configurationWithHierarchicalColor(int $hierarchicalColor): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationWithHierarchicalColor($hierarchicalColor));
    }

    public static function configurationWithPaletteColors(array $paletteColors): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationWithPaletteColors($paletteColors));
    }

    public static function configurationPreferringMulticolor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationPreferringMulticolor());
    }

    public function configurationByApplyingConfiguration(int $configuration): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageSymbolConfiguration::configurationByApplyingConfiguration($this->handle, $configuration));
    }
}
