<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSImageView\NSImageView as ExtNSImageView;
use Jovian\Bindings\AppKit\Enums\NSImageAlignment;
use Jovian\Bindings\AppKit\Enums\NSImageDynamicRange;
use Jovian\Bindings\AppKit\Enums\NSImageFrameStyle;
use Jovian\Bindings\AppKit\Enums\NSImageScaling;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSImageView extends NSControl
{
    public static function imageViewWithImage(int $image): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageView::imageViewWithImage($image));
    }

    public function image(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageView::image($this->handle));
    }

    public function setImage(int $image): static
    {
        ExtNSImageView::setImage($this->handle, $image);

        return $this;
    }

    public function isEditable(): bool
    {
        return ExtNSImageView::isEditable($this->handle);
    }

    public function setEditable(bool $editable): static
    {
        ExtNSImageView::setEditable($this->handle, $editable);

        return $this;
    }

    public function imageAlignment(): NSImageAlignment|int
    {
        return ExtNSImageView::imageAlignment($this->handle);
    }

    public function setImageAlignment(NSImageAlignment|int $imageAlignment): static
    {
        ExtNSImageView::setImageAlignment($this->handle, $imageAlignment instanceof \BackedEnum ? $imageAlignment->value : $imageAlignment);

        return $this;
    }

    public function imageScaling(): NSImageScaling|int
    {
        return ExtNSImageView::imageScaling($this->handle);
    }

    public function setImageScaling(NSImageScaling|int $imageScaling): static
    {
        ExtNSImageView::setImageScaling($this->handle, $imageScaling instanceof \BackedEnum ? $imageScaling->value : $imageScaling);

        return $this;
    }

    public function imageFrameStyle(): NSImageFrameStyle|int
    {
        return ExtNSImageView::imageFrameStyle($this->handle);
    }

    public function setImageFrameStyle(NSImageFrameStyle|int $imageFrameStyle): static
    {
        ExtNSImageView::setImageFrameStyle($this->handle, $imageFrameStyle instanceof \BackedEnum ? $imageFrameStyle->value : $imageFrameStyle);

        return $this;
    }

    public function symbolConfiguration(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageView::symbolConfiguration($this->handle));
    }

    public function setSymbolConfiguration(int $symbolConfiguration): static
    {
        ExtNSImageView::setSymbolConfiguration($this->handle, $symbolConfiguration);

        return $this;
    }

    public function contentTintColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSImageView::contentTintColor($this->handle));
    }

    public function setContentTintColor(int $contentTintColor): static
    {
        ExtNSImageView::setContentTintColor($this->handle, $contentTintColor);

        return $this;
    }

    public function animates(): bool
    {
        return ExtNSImageView::animates($this->handle);
    }

    public function setAnimates(bool $animates): static
    {
        ExtNSImageView::setAnimates($this->handle, $animates);

        return $this;
    }

    public function allowsCutCopyPaste(): bool
    {
        return ExtNSImageView::allowsCutCopyPaste($this->handle);
    }

    public function setAllowsCutCopyPaste(bool $allowsCutCopyPaste): static
    {
        ExtNSImageView::setAllowsCutCopyPaste($this->handle, $allowsCutCopyPaste);

        return $this;
    }

    public static function defaultPreferredImageDynamicRange(): NSImageDynamicRange|int
    {
        return ExtNSImageView::defaultPreferredImageDynamicRange();
    }

    public static function setDefaultPreferredImageDynamicRange(NSImageDynamicRange|int $defaultPreferredImageDynamicRange): void
    {
        ExtNSImageView::setDefaultPreferredImageDynamicRange($defaultPreferredImageDynamicRange instanceof \BackedEnum ? $defaultPreferredImageDynamicRange->value : $defaultPreferredImageDynamicRange);
    }

    public function preferredImageDynamicRange(): NSImageDynamicRange|int
    {
        return ExtNSImageView::preferredImageDynamicRange($this->handle);
    }

    public function setPreferredImageDynamicRange(NSImageDynamicRange|int $preferredImageDynamicRange): static
    {
        ExtNSImageView::setPreferredImageDynamicRange($this->handle, $preferredImageDynamicRange instanceof \BackedEnum ? $preferredImageDynamicRange->value : $preferredImageDynamicRange);

        return $this;
    }

    public function imageDynamicRange(): NSImageDynamicRange|int
    {
        return ExtNSImageView::imageDynamicRange($this->handle);
    }

    public function addSymbolEffect(int $symbolEffect): static
    {
        ExtNSImageView::addSymbolEffect($this->handle, $symbolEffect);

        return $this;
    }

    public function addSymbolEffectOptions(int $symbolEffect, int $options): static
    {
        ExtNSImageView::addSymbolEffectOptions($this->handle, $symbolEffect, $options);

        return $this;
    }

    public function addSymbolEffectOptionsAnimated(int $symbolEffect, int $options, bool $animated): static
    {
        ExtNSImageView::addSymbolEffectOptionsAnimated($this->handle, $symbolEffect, $options, $animated);

        return $this;
    }

    public function removeSymbolEffectOfType(int $symbolEffect): static
    {
        ExtNSImageView::removeSymbolEffectOfType($this->handle, $symbolEffect);

        return $this;
    }

    public function removeSymbolEffectOfTypeOptions(int $symbolEffect, int $options): static
    {
        ExtNSImageView::removeSymbolEffectOfTypeOptions($this->handle, $symbolEffect, $options);

        return $this;
    }

    public function removeSymbolEffectOfTypeOptionsAnimated(int $symbolEffect, int $options, bool $animated): static
    {
        ExtNSImageView::removeSymbolEffectOfTypeOptionsAnimated($this->handle, $symbolEffect, $options, $animated);

        return $this;
    }

    public function removeAllSymbolEffects(): static
    {
        ExtNSImageView::removeAllSymbolEffects($this->handle);

        return $this;
    }

    public function removeAllSymbolEffectsWithOptions(int $options): static
    {
        ExtNSImageView::removeAllSymbolEffectsWithOptions($this->handle, $options);

        return $this;
    }

    public function removeAllSymbolEffectsWithOptionsAnimated(int $options, bool $animated): static
    {
        ExtNSImageView::removeAllSymbolEffectsWithOptionsAnimated($this->handle, $options, $animated);

        return $this;
    }

    public function setSymbolImageWithContentTransition(int $symbolImage, int $transition): static
    {
        ExtNSImageView::setSymbolImageWithContentTransition($this->handle, $symbolImage, $transition);

        return $this;
    }

    public function setSymbolImageWithContentTransitionOptions(int $symbolImage, int $transition, int $options): static
    {
        ExtNSImageView::setSymbolImageWithContentTransitionOptions($this->handle, $symbolImage, $transition, $options);

        return $this;
    }
}
