<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSLayoutManager\NSLayoutManager as ExtNSLayoutManager;
use Jovian\Bindings\AppKit\Enums\NSImageScaling;
use Jovian\Bindings\AppKit\Enums\NSTypesetterBehavior;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSLayoutManager extends ObjCObject
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSLayoutManager::init());
    }

    public function textStorage(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSLayoutManager::textStorage($this->handle));
    }

    public function setTextStorage(int $textStorage): static
    {
        ExtNSLayoutManager::setTextStorage($this->handle, $textStorage);

        return $this;
    }

    public function replaceTextStorage(int $newTextStorage): static
    {
        ExtNSLayoutManager::replaceTextStorage($this->handle, $newTextStorage);

        return $this;
    }

    public function textContainers(): array
    {
        return ExtNSLayoutManager::textContainers($this->handle);
    }

    public function addTextContainer(int $container): static
    {
        ExtNSLayoutManager::addTextContainer($this->handle, $container);

        return $this;
    }

    public function insertTextContainerAtIndex(int $container, int $index): static
    {
        ExtNSLayoutManager::insertTextContainerAtIndex($this->handle, $container, $index);

        return $this;
    }

    public function removeTextContainerAtIndex(int $index): static
    {
        ExtNSLayoutManager::removeTextContainerAtIndex($this->handle, $index);

        return $this;
    }

    public function textContainerChangedGeometry(int $container): static
    {
        ExtNSLayoutManager::textContainerChangedGeometry($this->handle, $container);

        return $this;
    }

    public function textContainerChangedTextView(int $container): static
    {
        ExtNSLayoutManager::textContainerChangedTextView($this->handle, $container);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSLayoutManager::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSLayoutManager::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function showsInvisibleCharacters(): bool
    {
        return ExtNSLayoutManager::showsInvisibleCharacters($this->handle);
    }

    public function setShowsInvisibleCharacters(bool $showsInvisibleCharacters): static
    {
        ExtNSLayoutManager::setShowsInvisibleCharacters($this->handle, $showsInvisibleCharacters);

        return $this;
    }

    public function showsControlCharacters(): bool
    {
        return ExtNSLayoutManager::showsControlCharacters($this->handle);
    }

    public function setShowsControlCharacters(bool $showsControlCharacters): static
    {
        ExtNSLayoutManager::setShowsControlCharacters($this->handle, $showsControlCharacters);

        return $this;
    }

    public function usesDefaultHyphenation(): bool
    {
        return ExtNSLayoutManager::usesDefaultHyphenation($this->handle);
    }

    public function setUsesDefaultHyphenation(bool $usesDefaultHyphenation): static
    {
        ExtNSLayoutManager::setUsesDefaultHyphenation($this->handle, $usesDefaultHyphenation);

        return $this;
    }

    public function usesFontLeading(): bool
    {
        return ExtNSLayoutManager::usesFontLeading($this->handle);
    }

    public function setUsesFontLeading(bool $usesFontLeading): static
    {
        ExtNSLayoutManager::setUsesFontLeading($this->handle, $usesFontLeading);

        return $this;
    }

    public function allowsNonContiguousLayout(): bool
    {
        return ExtNSLayoutManager::allowsNonContiguousLayout($this->handle);
    }

    public function setAllowsNonContiguousLayout(bool $allowsNonContiguousLayout): static
    {
        ExtNSLayoutManager::setAllowsNonContiguousLayout($this->handle, $allowsNonContiguousLayout);

        return $this;
    }

    public function hasNonContiguousLayout(): bool
    {
        return ExtNSLayoutManager::hasNonContiguousLayout($this->handle);
    }

    public function limitsLayoutForSuspiciousContents(): bool
    {
        return ExtNSLayoutManager::limitsLayoutForSuspiciousContents($this->handle);
    }

    public function setLimitsLayoutForSuspiciousContents(bool $limitsLayoutForSuspiciousContents): static
    {
        ExtNSLayoutManager::setLimitsLayoutForSuspiciousContents($this->handle, $limitsLayoutForSuspiciousContents);

        return $this;
    }

    public function backgroundLayoutEnabled(): bool
    {
        return ExtNSLayoutManager::backgroundLayoutEnabled($this->handle);
    }

    public function setBackgroundLayoutEnabled(bool $backgroundLayoutEnabled): static
    {
        ExtNSLayoutManager::setBackgroundLayoutEnabled($this->handle, $backgroundLayoutEnabled);

        return $this;
    }

    public function defaultAttachmentScaling(): NSImageScaling|int
    {
        return ExtNSLayoutManager::defaultAttachmentScaling($this->handle);
    }

    public function setDefaultAttachmentScaling(NSImageScaling|int $defaultAttachmentScaling): static
    {
        ExtNSLayoutManager::setDefaultAttachmentScaling($this->handle, $defaultAttachmentScaling instanceof \BackedEnum ? $defaultAttachmentScaling->value : $defaultAttachmentScaling);

        return $this;
    }

    public function typesetter(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSLayoutManager::typesetter($this->handle));
    }

    public function setTypesetter(int $typesetter): static
    {
        ExtNSLayoutManager::setTypesetter($this->handle, $typesetter);

        return $this;
    }

    public function typesetterBehavior(): NSTypesetterBehavior|int
    {
        return ExtNSLayoutManager::typesetterBehavior($this->handle);
    }

    public function setTypesetterBehavior(NSTypesetterBehavior|int $typesetterBehavior): static
    {
        ExtNSLayoutManager::setTypesetterBehavior($this->handle, $typesetterBehavior instanceof \BackedEnum ? $typesetterBehavior->value : $typesetterBehavior);

        return $this;
    }

    public function invalidateGlyphsForCharacterRangeChangeInLengthActualCharacterRange(NSRange $charRange, int $delta): array
    {
        return ExtNSLayoutManager::invalidateGlyphsForCharacterRangeChangeInLengthActualCharacterRange(...[$this->handle, ...$charRange->toArgs(), $delta]);
    }

    public function invalidateLayoutForCharacterRangeActualCharacterRange(NSRange $charRange): array
    {
        return ExtNSLayoutManager::invalidateLayoutForCharacterRangeActualCharacterRange(...[$this->handle, ...$charRange->toArgs()]);
    }

    public function invalidateDisplayForCharacterRange(NSRange $charRange): static
    {
        ExtNSLayoutManager::invalidateDisplayForCharacterRange(...[$this->handle, ...$charRange->toArgs()]);

        return $this;
    }

    public function invalidateDisplayForGlyphRange(NSRange $glyphRange): static
    {
        ExtNSLayoutManager::invalidateDisplayForGlyphRange(...[$this->handle, ...$glyphRange->toArgs()]);

        return $this;
    }

    public function processEditingForTextStorageEditedRangeChangeInLengthInvalidatedRange(int $textStorage, int $editMask, NSRange $newCharRange, int $delta, NSRange $invalidatedCharRange): static
    {
        ExtNSLayoutManager::processEditingForTextStorageEditedRangeChangeInLengthInvalidatedRange(...[$this->handle, $textStorage, $editMask, ...$newCharRange->toArgs(), $delta, ...$invalidatedCharRange->toArgs()]);

        return $this;
    }

    public function ensureGlyphsForCharacterRange(NSRange $charRange): static
    {
        ExtNSLayoutManager::ensureGlyphsForCharacterRange(...[$this->handle, ...$charRange->toArgs()]);

        return $this;
    }

    public function ensureGlyphsForGlyphRange(NSRange $glyphRange): static
    {
        ExtNSLayoutManager::ensureGlyphsForGlyphRange(...[$this->handle, ...$glyphRange->toArgs()]);

        return $this;
    }

    public function ensureLayoutForCharacterRange(NSRange $charRange): static
    {
        ExtNSLayoutManager::ensureLayoutForCharacterRange(...[$this->handle, ...$charRange->toArgs()]);

        return $this;
    }

    public function ensureLayoutForGlyphRange(NSRange $glyphRange): static
    {
        ExtNSLayoutManager::ensureLayoutForGlyphRange(...[$this->handle, ...$glyphRange->toArgs()]);

        return $this;
    }

    public function ensureLayoutForTextContainer(int $container): static
    {
        ExtNSLayoutManager::ensureLayoutForTextContainer($this->handle, $container);

        return $this;
    }

    public function ensureLayoutForBoundingRectInTextContainer(NSRect $bounds, int $container): static
    {
        ExtNSLayoutManager::ensureLayoutForBoundingRectInTextContainer(...[$this->handle, ...$bounds->toArgs(), $container]);

        return $this;
    }

    public function numberOfGlyphs(): int
    {
        return ExtNSLayoutManager::numberOfGlyphs($this->handle);
    }

    public function CGGlyphAtIndexIsValidIndex(int $glyphIndex): array
    {
        return ExtNSLayoutManager::CGGlyphAtIndexIsValidIndex($this->handle, $glyphIndex);
    }

    public function CGGlyphAtIndex(int $glyphIndex): int
    {
        return ExtNSLayoutManager::CGGlyphAtIndex($this->handle, $glyphIndex);
    }

    public function isValidGlyphIndex(int $glyphIndex): bool
    {
        return ExtNSLayoutManager::isValidGlyphIndex($this->handle, $glyphIndex);
    }

    public function propertyForGlyphAtIndex(int $glyphIndex): int
    {
        return ExtNSLayoutManager::propertyForGlyphAtIndex($this->handle, $glyphIndex);
    }

    public function characterIndexForGlyphAtIndex(int $glyphIndex): int
    {
        return ExtNSLayoutManager::characterIndexForGlyphAtIndex($this->handle, $glyphIndex);
    }

    public function glyphIndexForCharacterAtIndex(int $charIndex): int
    {
        return ExtNSLayoutManager::glyphIndexForCharacterAtIndex($this->handle, $charIndex);
    }

    public function setTextContainerForGlyphRange(int $container, NSRange $glyphRange): static
    {
        ExtNSLayoutManager::setTextContainerForGlyphRange(...[$this->handle, $container, ...$glyphRange->toArgs()]);

        return $this;
    }

    public function setLineFragmentRectForGlyphRangeUsedRect(NSRect $fragmentRect, NSRange $glyphRange, NSRect $usedRect): static
    {
        ExtNSLayoutManager::setLineFragmentRectForGlyphRangeUsedRect(...[$this->handle, ...$fragmentRect->toArgs(), ...$glyphRange->toArgs(), ...$usedRect->toArgs()]);

        return $this;
    }

    public function setExtraLineFragmentRectUsedRectTextContainer(NSRect $fragmentRect, NSRect $usedRect, int $container): static
    {
        ExtNSLayoutManager::setExtraLineFragmentRectUsedRectTextContainer(...[$this->handle, ...$fragmentRect->toArgs(), ...$usedRect->toArgs(), $container]);

        return $this;
    }

    public function setLocationForStartOfGlyphRange(NSPoint $location, NSRange $glyphRange): static
    {
        ExtNSLayoutManager::setLocationForStartOfGlyphRange(...[$this->handle, ...$location->toArgs(), ...$glyphRange->toArgs()]);

        return $this;
    }

    public function setNotShownAttributeForGlyphAtIndex(bool $flag, int $glyphIndex): static
    {
        ExtNSLayoutManager::setNotShownAttributeForGlyphAtIndex($this->handle, $flag, $glyphIndex);

        return $this;
    }

    public function setDrawsOutsideLineFragmentForGlyphAtIndex(bool $flag, int $glyphIndex): static
    {
        ExtNSLayoutManager::setDrawsOutsideLineFragmentForGlyphAtIndex($this->handle, $flag, $glyphIndex);

        return $this;
    }

    public function setAttachmentSizeForGlyphRange(NSSize $attachmentSize, NSRange $glyphRange): static
    {
        ExtNSLayoutManager::setAttachmentSizeForGlyphRange(...[$this->handle, ...$attachmentSize->toArgs(), ...$glyphRange->toArgs()]);

        return $this;
    }

    public function getFirstUnlaidCharacterIndexGlyphIndex(): array
    {
        return ExtNSLayoutManager::getFirstUnlaidCharacterIndexGlyphIndex($this->handle);
    }

    public function firstUnlaidCharacterIndex(): int
    {
        return ExtNSLayoutManager::firstUnlaidCharacterIndex($this->handle);
    }

    public function firstUnlaidGlyphIndex(): int
    {
        return ExtNSLayoutManager::firstUnlaidGlyphIndex($this->handle);
    }

    public function textContainerForGlyphAtIndexEffectiveRange(int $glyphIndex): array
    {
        return ExtNSLayoutManager::textContainerForGlyphAtIndexEffectiveRange($this->handle, $glyphIndex);
    }

    public function textContainerForGlyphAtIndexEffectiveRangeWithoutAdditionalLayout(int $glyphIndex, bool $flag): array
    {
        return ExtNSLayoutManager::textContainerForGlyphAtIndexEffectiveRangeWithoutAdditionalLayout($this->handle, $glyphIndex, $flag);
    }

    public function usedRectForTextContainer(int $container): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::usedRectForTextContainer($this->handle, $container));
    }

    public function lineFragmentRectForGlyphAtIndexEffectiveRange(int $glyphIndex): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::lineFragmentRectForGlyphAtIndexEffectiveRange($this->handle, $glyphIndex));
    }

    public function lineFragmentRectForGlyphAtIndexEffectiveRangeWithoutAdditionalLayout(int $glyphIndex, bool $flag): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::lineFragmentRectForGlyphAtIndexEffectiveRangeWithoutAdditionalLayout($this->handle, $glyphIndex, $flag));
    }

    public function lineFragmentUsedRectForGlyphAtIndexEffectiveRange(int $glyphIndex): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::lineFragmentUsedRectForGlyphAtIndexEffectiveRange($this->handle, $glyphIndex));
    }

    public function lineFragmentUsedRectForGlyphAtIndexEffectiveRangeWithoutAdditionalLayout(int $glyphIndex, bool $flag): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::lineFragmentUsedRectForGlyphAtIndexEffectiveRangeWithoutAdditionalLayout($this->handle, $glyphIndex, $flag));
    }

    public function extraLineFragmentRect(): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::extraLineFragmentRect($this->handle));
    }

    public function extraLineFragmentUsedRect(): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::extraLineFragmentUsedRect($this->handle));
    }

    public function extraLineFragmentTextContainer(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSLayoutManager::extraLineFragmentTextContainer($this->handle));
    }

    public function locationForGlyphAtIndex(int $glyphIndex): NSPoint
    {
        return NSPoint::fromArray(ExtNSLayoutManager::locationForGlyphAtIndex($this->handle, $glyphIndex));
    }

    public function notShownAttributeForGlyphAtIndex(int $glyphIndex): bool
    {
        return ExtNSLayoutManager::notShownAttributeForGlyphAtIndex($this->handle, $glyphIndex);
    }

    public function drawsOutsideLineFragmentForGlyphAtIndex(int $glyphIndex): bool
    {
        return ExtNSLayoutManager::drawsOutsideLineFragmentForGlyphAtIndex($this->handle, $glyphIndex);
    }

    public function attachmentSizeForGlyphAtIndex(int $glyphIndex): NSSize
    {
        return NSSize::fromArray(ExtNSLayoutManager::attachmentSizeForGlyphAtIndex($this->handle, $glyphIndex));
    }

    public function truncatedGlyphRangeInLineFragmentForGlyphAtIndex(int $glyphIndex): NSRange
    {
        return NSRange::fromArray(ExtNSLayoutManager::truncatedGlyphRangeInLineFragmentForGlyphAtIndex($this->handle, $glyphIndex));
    }

    public function glyphRangeForCharacterRangeActualCharacterRange(NSRange $charRange): NSRange
    {
        return NSRange::fromArray(ExtNSLayoutManager::glyphRangeForCharacterRangeActualCharacterRange(...[$this->handle, ...$charRange->toArgs()]));
    }

    public function characterRangeForGlyphRangeActualGlyphRange(NSRange $glyphRange): NSRange
    {
        return NSRange::fromArray(ExtNSLayoutManager::characterRangeForGlyphRangeActualGlyphRange(...[$this->handle, ...$glyphRange->toArgs()]));
    }

    public function glyphRangeForTextContainer(int $container): NSRange
    {
        return NSRange::fromArray(ExtNSLayoutManager::glyphRangeForTextContainer($this->handle, $container));
    }

    public function rangeOfNominallySpacedGlyphsContainingIndex(int $glyphIndex): NSRange
    {
        return NSRange::fromArray(ExtNSLayoutManager::rangeOfNominallySpacedGlyphsContainingIndex($this->handle, $glyphIndex));
    }

    public function boundingRectForGlyphRangeInTextContainer(NSRange $glyphRange, int $container): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::boundingRectForGlyphRangeInTextContainer(...[$this->handle, ...$glyphRange->toArgs(), $container]));
    }

    public function glyphRangeForBoundingRectInTextContainer(NSRect $bounds, int $container): NSRange
    {
        return NSRange::fromArray(ExtNSLayoutManager::glyphRangeForBoundingRectInTextContainer(...[$this->handle, ...$bounds->toArgs(), $container]));
    }

    public function glyphRangeForBoundingRectWithoutAdditionalLayoutInTextContainer(NSRect $bounds, int $container): NSRange
    {
        return NSRange::fromArray(ExtNSLayoutManager::glyphRangeForBoundingRectWithoutAdditionalLayoutInTextContainer(...[$this->handle, ...$bounds->toArgs(), $container]));
    }

    public function glyphIndexForPointInTextContainerFractionOfDistanceThroughGlyph(NSPoint $point, int $container): array
    {
        return ExtNSLayoutManager::glyphIndexForPointInTextContainerFractionOfDistanceThroughGlyph(...[$this->handle, ...$point->toArgs(), $container]);
    }

    public function glyphIndexForPointInTextContainer(NSPoint $point, int $container): int
    {
        return ExtNSLayoutManager::glyphIndexForPointInTextContainer(...[$this->handle, ...$point->toArgs(), $container]);
    }

    public function fractionOfDistanceThroughGlyphForPointInTextContainer(NSPoint $point, int $container): float
    {
        return ExtNSLayoutManager::fractionOfDistanceThroughGlyphForPointInTextContainer(...[$this->handle, ...$point->toArgs(), $container]);
    }

    public function characterIndexForPointInTextContainerFractionOfDistanceBetweenInsertionPoints(NSPoint $point, int $container): array
    {
        return ExtNSLayoutManager::characterIndexForPointInTextContainerFractionOfDistanceBetweenInsertionPoints(...[$this->handle, ...$point->toArgs(), $container]);
    }

    public function drawBackgroundForGlyphRangeAtPoint(NSRange $glyphsToShow, NSPoint $origin): static
    {
        ExtNSLayoutManager::drawBackgroundForGlyphRangeAtPoint(...[$this->handle, ...$glyphsToShow->toArgs(), ...$origin->toArgs()]);

        return $this;
    }

    public function drawGlyphsForGlyphRangeAtPoint(NSRange $glyphsToShow, NSPoint $origin): static
    {
        ExtNSLayoutManager::drawGlyphsForGlyphRangeAtPoint(...[$this->handle, ...$glyphsToShow->toArgs(), ...$origin->toArgs()]);

        return $this;
    }

    public function drawUnderlineForGlyphRangeUnderlineTypeBaselineOffsetLineFragmentRectLineFragmentGlyphRangeContainerOrigin(NSRange $glyphRange, int $underlineVal, float $baselineOffset, NSRect $lineRect, NSRange $lineGlyphRange, NSPoint $containerOrigin): static
    {
        ExtNSLayoutManager::drawUnderlineForGlyphRangeUnderlineTypeBaselineOffsetLineFragmentRectLineFragmentGlyphRangeContainerOrigin(...[$this->handle, ...$glyphRange->toArgs(), $underlineVal, $baselineOffset, ...$lineRect->toArgs(), ...$lineGlyphRange->toArgs(), ...$containerOrigin->toArgs()]);

        return $this;
    }

    public function underlineGlyphRangeUnderlineTypeLineFragmentRectLineFragmentGlyphRangeContainerOrigin(NSRange $glyphRange, int $underlineVal, NSRect $lineRect, NSRange $lineGlyphRange, NSPoint $containerOrigin): static
    {
        ExtNSLayoutManager::underlineGlyphRangeUnderlineTypeLineFragmentRectLineFragmentGlyphRangeContainerOrigin(...[$this->handle, ...$glyphRange->toArgs(), $underlineVal, ...$lineRect->toArgs(), ...$lineGlyphRange->toArgs(), ...$containerOrigin->toArgs()]);

        return $this;
    }

    public function drawStrikethroughForGlyphRangeStrikethroughTypeBaselineOffsetLineFragmentRectLineFragmentGlyphRangeContainerOrigin(NSRange $glyphRange, int $strikethroughVal, float $baselineOffset, NSRect $lineRect, NSRange $lineGlyphRange, NSPoint $containerOrigin): static
    {
        ExtNSLayoutManager::drawStrikethroughForGlyphRangeStrikethroughTypeBaselineOffsetLineFragmentRectLineFragmentGlyphRangeContainerOrigin(...[$this->handle, ...$glyphRange->toArgs(), $strikethroughVal, $baselineOffset, ...$lineRect->toArgs(), ...$lineGlyphRange->toArgs(), ...$containerOrigin->toArgs()]);

        return $this;
    }

    public function strikethroughGlyphRangeStrikethroughTypeLineFragmentRectLineFragmentGlyphRangeContainerOrigin(NSRange $glyphRange, int $strikethroughVal, NSRect $lineRect, NSRange $lineGlyphRange, NSPoint $containerOrigin): static
    {
        ExtNSLayoutManager::strikethroughGlyphRangeStrikethroughTypeLineFragmentRectLineFragmentGlyphRangeContainerOrigin(...[$this->handle, ...$glyphRange->toArgs(), $strikethroughVal, ...$lineRect->toArgs(), ...$lineGlyphRange->toArgs(), ...$containerOrigin->toArgs()]);

        return $this;
    }

    public function showAttachmentCellInRectCharacterIndex(int $cell, NSRect $rect, int $attachmentIndex): static
    {
        ExtNSLayoutManager::showAttachmentCellInRectCharacterIndex(...[$this->handle, $cell, ...$rect->toArgs(), $attachmentIndex]);

        return $this;
    }

    public function setLayoutRectForTextBlockGlyphRange(NSRect $rect, int $block, NSRange $glyphRange): static
    {
        ExtNSLayoutManager::setLayoutRectForTextBlockGlyphRange(...[$this->handle, ...$rect->toArgs(), $block, ...$glyphRange->toArgs()]);

        return $this;
    }

    public function setBoundsRectForTextBlockGlyphRange(NSRect $rect, int $block, NSRange $glyphRange): static
    {
        ExtNSLayoutManager::setBoundsRectForTextBlockGlyphRange(...[$this->handle, ...$rect->toArgs(), $block, ...$glyphRange->toArgs()]);

        return $this;
    }

    public function layoutRectForTextBlockGlyphRange(int $block, NSRange $glyphRange): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::layoutRectForTextBlockGlyphRange(...[$this->handle, $block, ...$glyphRange->toArgs()]));
    }

    public function boundsRectForTextBlockGlyphRange(int $block, NSRange $glyphRange): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::boundsRectForTextBlockGlyphRange(...[$this->handle, $block, ...$glyphRange->toArgs()]));
    }

    public function layoutRectForTextBlockAtIndexEffectiveRange(int $block, int $glyphIndex): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::layoutRectForTextBlockAtIndexEffectiveRange($this->handle, $block, $glyphIndex));
    }

    public function boundsRectForTextBlockAtIndexEffectiveRange(int $block, int $glyphIndex): NSRect
    {
        return NSRect::fromArray(ExtNSLayoutManager::boundsRectForTextBlockAtIndexEffectiveRange($this->handle, $block, $glyphIndex));
    }

    public function temporaryAttributesAtCharacterIndexEffectiveRange(int $charIndex): array
    {
        return ExtNSLayoutManager::temporaryAttributesAtCharacterIndexEffectiveRange($this->handle, $charIndex);
    }

    public function setTemporaryAttributesForCharacterRange(array $attrs, NSRange $charRange): static
    {
        ExtNSLayoutManager::setTemporaryAttributesForCharacterRange(...[$this->handle, $attrs, ...$charRange->toArgs()]);

        return $this;
    }

    public function addTemporaryAttributesForCharacterRange(array $attrs, NSRange $charRange): static
    {
        ExtNSLayoutManager::addTemporaryAttributesForCharacterRange(...[$this->handle, $attrs, ...$charRange->toArgs()]);

        return $this;
    }

    public function removeTemporaryAttributeForCharacterRange(string $attrName, NSRange $charRange): static
    {
        ExtNSLayoutManager::removeTemporaryAttributeForCharacterRange(...[$this->handle, $attrName, ...$charRange->toArgs()]);

        return $this;
    }

    public function temporaryAttributeAtCharacterIndexEffectiveRange(string $attrName, int $location): array
    {
        return ExtNSLayoutManager::temporaryAttributeAtCharacterIndexEffectiveRange($this->handle, $attrName, $location);
    }

    public function temporaryAttributeAtCharacterIndexLongestEffectiveRangeInRange(string $attrName, int $location, NSRange $rangeLimit): array
    {
        return ExtNSLayoutManager::temporaryAttributeAtCharacterIndexLongestEffectiveRangeInRange(...[$this->handle, $attrName, $location, ...$rangeLimit->toArgs()]);
    }

    public function temporaryAttributesAtCharacterIndexLongestEffectiveRangeInRange(int $location, NSRange $rangeLimit): array
    {
        return ExtNSLayoutManager::temporaryAttributesAtCharacterIndexLongestEffectiveRangeInRange(...[$this->handle, $location, ...$rangeLimit->toArgs()]);
    }

    public function addTemporaryAttributeValueForCharacterRange(string $attrName, int $value, NSRange $charRange): static
    {
        ExtNSLayoutManager::addTemporaryAttributeValueForCharacterRange(...[$this->handle, $attrName, $value, ...$charRange->toArgs()]);

        return $this;
    }

    public function defaultLineHeightForFont(int $theFont): float
    {
        return ExtNSLayoutManager::defaultLineHeightForFont($this->handle, $theFont);
    }

    public function defaultBaselineOffsetForFont(int $theFont): float
    {
        return ExtNSLayoutManager::defaultBaselineOffsetForFont($this->handle, $theFont);
    }

    public function rulerMarkersForTextViewParagraphStyleRuler(int $view, int $style, int $ruler): array
    {
        return ExtNSLayoutManager::rulerMarkersForTextViewParagraphStyleRuler($this->handle, $view, $style, $ruler);
    }

    public function rulerAccessoryViewForTextViewParagraphStyleRulerEnabled(int $view, int $style, int $ruler, bool $isEnabled): ?ObjCObject
    {
        return ObjCObject::box(ExtNSLayoutManager::rulerAccessoryViewForTextViewParagraphStyleRulerEnabled($this->handle, $view, $style, $ruler, $isEnabled));
    }

    public function layoutManagerOwnsFirstResponderInWindow(int $window): bool
    {
        return ExtNSLayoutManager::layoutManagerOwnsFirstResponderInWindow($this->handle, $window);
    }

    public function firstTextView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSLayoutManager::firstTextView($this->handle));
    }

    public function textViewForBeginningOfSelection(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSLayoutManager::textViewForBeginningOfSelection($this->handle));
    }

    public function glyphAtIndexIsValidIndex(int $glyphIndex): array
    {
        return ExtNSLayoutManager::glyphAtIndexIsValidIndex($this->handle, $glyphIndex);
    }

    public function glyphAtIndex(int $glyphIndex): int
    {
        return ExtNSLayoutManager::glyphAtIndex($this->handle, $glyphIndex);
    }

    public function rectArrayForCharacterRangeWithinSelectedCharacterRangeInTextContainerRectCount(NSRange $charRange, NSRange $selCharRange, int $container): array
    {
        return ExtNSLayoutManager::rectArrayForCharacterRangeWithinSelectedCharacterRangeInTextContainerRectCount(...[$this->handle, ...$charRange->toArgs(), ...$selCharRange->toArgs(), $container]);
    }

    public function rectArrayForGlyphRangeWithinSelectedGlyphRangeInTextContainerRectCount(NSRange $glyphRange, NSRange $selGlyphRange, int $container): array
    {
        return ExtNSLayoutManager::rectArrayForGlyphRangeWithinSelectedGlyphRangeInTextContainerRectCount(...[$this->handle, ...$glyphRange->toArgs(), ...$selGlyphRange->toArgs(), $container]);
    }

    public function glyphGenerator(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSLayoutManager::glyphGenerator($this->handle));
    }

    public function setGlyphGenerator(int $glyphGenerator): static
    {
        ExtNSLayoutManager::setGlyphGenerator($this->handle, $glyphGenerator);

        return $this;
    }
}
