<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSMenu\NSMenu as ExtNSMenu;
use Jovian\Bindings\AppKit\Enums\NSMenuPresentationStyle;
use Jovian\Bindings\AppKit\Enums\NSMenuSelectionMode;
use Jovian\Bindings\AppKit\Enums\NSUserInterfaceLayoutDirection;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSMenu extends ObjCObject
{
    public static function initWithTitle(string $title): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenu::initWithTitle($title));
    }

    public function title(): ?string
    {
        return ExtNSMenu::title($this->handle);
    }

    public function setTitle(string $title): static
    {
        ExtNSMenu::setTitle($this->handle, $title);

        return $this;
    }

    public static function popUpContextMenuWithEventForView(int $menu, int $event, int $view): void
    {
        ExtNSMenu::popUpContextMenuWithEventForView($menu, $event, $view);
    }

    public static function popUpContextMenuWithEventForViewWithFont(int $menu, int $event, int $view, int $font): void
    {
        ExtNSMenu::popUpContextMenuWithEventForViewWithFont($menu, $event, $view, $font);
    }

    public function popUpMenuPositioningItemAtLocationInView(int $item, NSPoint $location, int $view): bool
    {
        return ExtNSMenu::popUpMenuPositioningItemAtLocationInView(...[$this->handle, $item, ...$location->toArgs(), $view]);
    }

    public static function setMenuBarVisible(bool $visible): void
    {
        ExtNSMenu::setMenuBarVisible($visible);
    }

    public static function menuBarVisible(): bool
    {
        return ExtNSMenu::menuBarVisible();
    }

    public function supermenu(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenu::supermenu($this->handle));
    }

    public function setSupermenu(int $supermenu): static
    {
        ExtNSMenu::setSupermenu($this->handle, $supermenu);

        return $this;
    }

    public function insertItemAtIndex(int $newItem, int $index): static
    {
        ExtNSMenu::insertItemAtIndex($this->handle, $newItem, $index);

        return $this;
    }

    public function addItem(int $newItem): static
    {
        ExtNSMenu::addItem($this->handle, $newItem);

        return $this;
    }

    public function insertItemWithTitleActionKeyEquivalentAtIndex(string $string, string $selector, string $charCode, int $index): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenu::insertItemWithTitleActionKeyEquivalentAtIndex($this->handle, $string, $selector, $charCode, $index));
    }

    public function addItemWithTitleActionKeyEquivalent(string $string, string $selector, string $charCode): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenu::addItemWithTitleActionKeyEquivalent($this->handle, $string, $selector, $charCode));
    }

    public function removeItemAtIndex(int $index): static
    {
        ExtNSMenu::removeItemAtIndex($this->handle, $index);

        return $this;
    }

    public function removeItem(int $item): static
    {
        ExtNSMenu::removeItem($this->handle, $item);

        return $this;
    }

    public function setSubmenuForItem(int $menu, int $item): static
    {
        ExtNSMenu::setSubmenuForItem($this->handle, $menu, $item);

        return $this;
    }

    public function removeAllItems(): static
    {
        ExtNSMenu::removeAllItems($this->handle);

        return $this;
    }

    public function itemArray(): array
    {
        return ExtNSMenu::itemArray($this->handle);
    }

    public function setItemArray(array $itemArray): static
    {
        ExtNSMenu::setItemArray($this->handle, $itemArray);

        return $this;
    }

    public function numberOfItems(): int
    {
        return ExtNSMenu::numberOfItems($this->handle);
    }

    public function itemAtIndex(int $index): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenu::itemAtIndex($this->handle, $index));
    }

    public function indexOfItem(int $item): int
    {
        return ExtNSMenu::indexOfItem($this->handle, $item);
    }

    public function indexOfItemWithTitle(string $title): int
    {
        return ExtNSMenu::indexOfItemWithTitle($this->handle, $title);
    }

    public function indexOfItemWithTag(int $tag): int
    {
        return ExtNSMenu::indexOfItemWithTag($this->handle, $tag);
    }

    public function indexOfItemWithRepresentedObject(int $object): int
    {
        return ExtNSMenu::indexOfItemWithRepresentedObject($this->handle, $object);
    }

    public function indexOfItemWithSubmenu(int $submenu): int
    {
        return ExtNSMenu::indexOfItemWithSubmenu($this->handle, $submenu);
    }

    public function indexOfItemWithTargetAndAction(int $target, string $actionSelector): int
    {
        return ExtNSMenu::indexOfItemWithTargetAndAction($this->handle, $target, $actionSelector);
    }

    public function itemWithTitle(string $title): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenu::itemWithTitle($this->handle, $title));
    }

    public function itemWithTag(int $tag): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenu::itemWithTag($this->handle, $tag));
    }

    public function autoenablesItems(): bool
    {
        return ExtNSMenu::autoenablesItems($this->handle);
    }

    public function setAutoenablesItems(bool $autoenablesItems): static
    {
        ExtNSMenu::setAutoenablesItems($this->handle, $autoenablesItems);

        return $this;
    }

    public function update(): static
    {
        ExtNSMenu::update($this->handle);

        return $this;
    }

    public function performKeyEquivalent(int $event): bool
    {
        return ExtNSMenu::performKeyEquivalent($this->handle, $event);
    }

    public function itemChanged(int $item): static
    {
        ExtNSMenu::itemChanged($this->handle, $item);

        return $this;
    }

    public function performActionForItemAtIndex(int $index): static
    {
        ExtNSMenu::performActionForItemAtIndex($this->handle, $index);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenu::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSMenu::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function menuBarHeight(): float
    {
        return ExtNSMenu::menuBarHeight($this->handle);
    }

    public function cancelTracking(): static
    {
        ExtNSMenu::cancelTracking($this->handle);

        return $this;
    }

    public function cancelTrackingWithoutAnimation(): static
    {
        ExtNSMenu::cancelTrackingWithoutAnimation($this->handle);

        return $this;
    }

    public function highlightedItem(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenu::highlightedItem($this->handle));
    }

    public function minimumWidth(): float
    {
        return ExtNSMenu::minimumWidth($this->handle);
    }

    public function setMinimumWidth(float $minimumWidth): static
    {
        ExtNSMenu::setMinimumWidth($this->handle, $minimumWidth);

        return $this;
    }

    public function size(): NSSize
    {
        return NSSize::fromArray(ExtNSMenu::size($this->handle));
    }

    public function font(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenu::font($this->handle));
    }

    public function setFont(int $font): static
    {
        ExtNSMenu::setFont($this->handle, $font);

        return $this;
    }

    public function allowsContextMenuPlugIns(): bool
    {
        return ExtNSMenu::allowsContextMenuPlugIns($this->handle);
    }

    public function setAllowsContextMenuPlugIns(bool $allowsContextMenuPlugIns): static
    {
        ExtNSMenu::setAllowsContextMenuPlugIns($this->handle, $allowsContextMenuPlugIns);

        return $this;
    }

    public function automaticallyInsertsWritingToolsItems(): bool
    {
        return ExtNSMenu::automaticallyInsertsWritingToolsItems($this->handle);
    }

    public function setAutomaticallyInsertsWritingToolsItems(bool $automaticallyInsertsWritingToolsItems): static
    {
        ExtNSMenu::setAutomaticallyInsertsWritingToolsItems($this->handle, $automaticallyInsertsWritingToolsItems);

        return $this;
    }

    public function showsStateColumn(): bool
    {
        return ExtNSMenu::showsStateColumn($this->handle);
    }

    public function setShowsStateColumn(bool $showsStateColumn): static
    {
        ExtNSMenu::setShowsStateColumn($this->handle, $showsStateColumn);

        return $this;
    }

    public function userInterfaceLayoutDirection(): NSUserInterfaceLayoutDirection|int
    {
        return ExtNSMenu::userInterfaceLayoutDirection($this->handle);
    }

    public function setUserInterfaceLayoutDirection(NSUserInterfaceLayoutDirection|int $userInterfaceLayoutDirection): static
    {
        ExtNSMenu::setUserInterfaceLayoutDirection($this->handle, $userInterfaceLayoutDirection instanceof \BackedEnum ? $userInterfaceLayoutDirection->value : $userInterfaceLayoutDirection);

        return $this;
    }

    public function presentationStyle(): NSMenuPresentationStyle|int
    {
        return ExtNSMenu::presentationStyle($this->handle);
    }

    public function setPresentationStyle(NSMenuPresentationStyle|int $presentationStyle): static
    {
        ExtNSMenu::setPresentationStyle($this->handle, $presentationStyle instanceof \BackedEnum ? $presentationStyle->value : $presentationStyle);

        return $this;
    }

    public function selectionMode(): NSMenuSelectionMode|int
    {
        return ExtNSMenu::selectionMode($this->handle);
    }

    public function setSelectionMode(NSMenuSelectionMode|int $selectionMode): static
    {
        ExtNSMenu::setSelectionMode($this->handle, $selectionMode instanceof \BackedEnum ? $selectionMode->value : $selectionMode);

        return $this;
    }

    public function selectedItems(): array
    {
        return ExtNSMenu::selectedItems($this->handle);
    }

    public function setSelectedItems(array $selectedItems): static
    {
        ExtNSMenu::setSelectedItems($this->handle, $selectedItems);

        return $this;
    }

    public function submenuAction(int $sender): static
    {
        ExtNSMenu::submenuAction($this->handle, $sender);

        return $this;
    }

    public function propertiesToUpdate(): int
    {
        return ExtNSMenu::propertiesToUpdate($this->handle);
    }
}
