<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSMenuItem\NSMenuItem as ExtNSMenuItem;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSMenuItem extends ObjCObject
{
    public static function usesUserKeyEquivalents(): bool
    {
        return ExtNSMenuItem::usesUserKeyEquivalents();
    }

    public static function setUsesUserKeyEquivalents(bool $usesUserKeyEquivalents): void
    {
        ExtNSMenuItem::setUsesUserKeyEquivalents($usesUserKeyEquivalents);
    }

    public static function separatorItem(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::separatorItem());
    }

    public static function sectionHeaderWithTitle(string $title): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::sectionHeaderWithTitle($title));
    }

    public static function writingToolsItems(): array
    {
        return ExtNSMenuItem::writingToolsItems();
    }

    public static function initWithTitleActionKeyEquivalent(string $string, string $selector, string $charCode): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::initWithTitleActionKeyEquivalent($string, $selector, $charCode));
    }

    public function menu(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::menu($this->handle));
    }

    public function setMenu(int $menu): static
    {
        ExtNSMenuItem::setMenu($this->handle, $menu);

        return $this;
    }

    public function hasSubmenu(): bool
    {
        return ExtNSMenuItem::hasSubmenu($this->handle);
    }

    public function submenu(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::submenu($this->handle));
    }

    public function setSubmenu(int $submenu): static
    {
        ExtNSMenuItem::setSubmenu($this->handle, $submenu);

        return $this;
    }

    public function parentItem(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::parentItem($this->handle));
    }

    public function title(): ?string
    {
        return ExtNSMenuItem::title($this->handle);
    }

    public function setTitle(string $title): static
    {
        ExtNSMenuItem::setTitle($this->handle, $title);

        return $this;
    }

    public function subtitle(): mixed
    {
        return ExtNSMenuItem::subtitle($this->handle);
    }

    public function setSubtitle(string $subtitle): static
    {
        ExtNSMenuItem::setSubtitle($this->handle, $subtitle);

        return $this;
    }

    public function isSeparatorItem(): bool
    {
        return ExtNSMenuItem::isSeparatorItem($this->handle);
    }

    public function isSectionHeader(): bool
    {
        return ExtNSMenuItem::isSectionHeader($this->handle);
    }

    public function keyEquivalent(): ?string
    {
        return ExtNSMenuItem::keyEquivalent($this->handle);
    }

    public function setKeyEquivalent(string $keyEquivalent): static
    {
        ExtNSMenuItem::setKeyEquivalent($this->handle, $keyEquivalent);

        return $this;
    }

    public function keyEquivalentModifierMask(): int
    {
        return ExtNSMenuItem::keyEquivalentModifierMask($this->handle);
    }

    public function setKeyEquivalentModifierMask(int $keyEquivalentModifierMask): static
    {
        ExtNSMenuItem::setKeyEquivalentModifierMask($this->handle, $keyEquivalentModifierMask);

        return $this;
    }

    public function userKeyEquivalent(): ?string
    {
        return ExtNSMenuItem::userKeyEquivalent($this->handle);
    }

    public function allowsKeyEquivalentWhenHidden(): bool
    {
        return ExtNSMenuItem::allowsKeyEquivalentWhenHidden($this->handle);
    }

    public function setAllowsKeyEquivalentWhenHidden(bool $allowsKeyEquivalentWhenHidden): static
    {
        ExtNSMenuItem::setAllowsKeyEquivalentWhenHidden($this->handle, $allowsKeyEquivalentWhenHidden);

        return $this;
    }

    public function allowsAutomaticKeyEquivalentLocalization(): bool
    {
        return ExtNSMenuItem::allowsAutomaticKeyEquivalentLocalization($this->handle);
    }

    public function setAllowsAutomaticKeyEquivalentLocalization(bool $allowsAutomaticKeyEquivalentLocalization): static
    {
        ExtNSMenuItem::setAllowsAutomaticKeyEquivalentLocalization($this->handle, $allowsAutomaticKeyEquivalentLocalization);

        return $this;
    }

    public function allowsAutomaticKeyEquivalentMirroring(): bool
    {
        return ExtNSMenuItem::allowsAutomaticKeyEquivalentMirroring($this->handle);
    }

    public function setAllowsAutomaticKeyEquivalentMirroring(bool $allowsAutomaticKeyEquivalentMirroring): static
    {
        ExtNSMenuItem::setAllowsAutomaticKeyEquivalentMirroring($this->handle, $allowsAutomaticKeyEquivalentMirroring);

        return $this;
    }

    public function image(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::image($this->handle));
    }

    public function setImage(int $image): static
    {
        ExtNSMenuItem::setImage($this->handle, $image);

        return $this;
    }

    public function state(): int
    {
        return ExtNSMenuItem::state($this->handle);
    }

    public function setState(int $state): static
    {
        ExtNSMenuItem::setState($this->handle, $state);

        return $this;
    }

    public function onStateImage(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::onStateImage($this->handle));
    }

    public function setOnStateImage(int $onStateImage): static
    {
        ExtNSMenuItem::setOnStateImage($this->handle, $onStateImage);

        return $this;
    }

    public function offStateImage(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::offStateImage($this->handle));
    }

    public function setOffStateImage(int $offStateImage): static
    {
        ExtNSMenuItem::setOffStateImage($this->handle, $offStateImage);

        return $this;
    }

    public function mixedStateImage(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::mixedStateImage($this->handle));
    }

    public function setMixedStateImage(int $mixedStateImage): static
    {
        ExtNSMenuItem::setMixedStateImage($this->handle, $mixedStateImage);

        return $this;
    }

    public function isEnabled(): bool
    {
        return ExtNSMenuItem::isEnabled($this->handle);
    }

    public function setEnabled(bool $enabled): static
    {
        ExtNSMenuItem::setEnabled($this->handle, $enabled);

        return $this;
    }

    public function isAlternate(): bool
    {
        return ExtNSMenuItem::isAlternate($this->handle);
    }

    public function setAlternate(bool $alternate): static
    {
        ExtNSMenuItem::setAlternate($this->handle, $alternate);

        return $this;
    }

    public function indentationLevel(): int
    {
        return ExtNSMenuItem::indentationLevel($this->handle);
    }

    public function setIndentationLevel(int $indentationLevel): static
    {
        ExtNSMenuItem::setIndentationLevel($this->handle, $indentationLevel);

        return $this;
    }

    public function target(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::target($this->handle));
    }

    public function setTarget(int $target): static
    {
        ExtNSMenuItem::setTarget($this->handle, $target);

        return $this;
    }

    public function action(): mixed
    {
        return ExtNSMenuItem::action($this->handle);
    }

    public function setAction(string $action): static
    {
        ExtNSMenuItem::setAction($this->handle, $action);

        return $this;
    }

    public function tag(): int
    {
        return ExtNSMenuItem::tag($this->handle);
    }

    public function setTag(int $tag): static
    {
        ExtNSMenuItem::setTag($this->handle, $tag);

        return $this;
    }

    public function representedObject(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::representedObject($this->handle));
    }

    public function setRepresentedObject(int $representedObject): static
    {
        ExtNSMenuItem::setRepresentedObject($this->handle, $representedObject);

        return $this;
    }

    public function view(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::view($this->handle));
    }

    public function setView(int $view): static
    {
        ExtNSMenuItem::setView($this->handle, $view);

        return $this;
    }

    public function isHighlighted(): bool
    {
        return ExtNSMenuItem::isHighlighted($this->handle);
    }

    public function isHidden(): bool
    {
        return ExtNSMenuItem::isHidden($this->handle);
    }

    public function setHidden(bool $hidden): static
    {
        ExtNSMenuItem::setHidden($this->handle, $hidden);

        return $this;
    }

    public function isHiddenOrHasHiddenAncestor(): bool
    {
        return ExtNSMenuItem::isHiddenOrHasHiddenAncestor($this->handle);
    }

    public function toolTip(): mixed
    {
        return ExtNSMenuItem::toolTip($this->handle);
    }

    public function setToolTip(string $toolTip): static
    {
        ExtNSMenuItem::setToolTip($this->handle, $toolTip);

        return $this;
    }

    public function badge(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSMenuItem::badge($this->handle));
    }

    public function setBadge(int $badge): static
    {
        ExtNSMenuItem::setBadge($this->handle, $badge);

        return $this;
    }
}
