<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSOpenGLContext\NSOpenGLContext as ExtNSOpenGLContext;
use Jovian\Bindings\AppKit\Enums\NSOpenGLContextParameter;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSOpenGLContext extends ObjCObject
{
    public static function initWithFormatShareContext(int $format, int $share): ?ObjCObject
    {
        return ObjCObject::box(ExtNSOpenGLContext::initWithFormatShareContext($format, $share));
    }

    public static function initWithCGLContextObj(int $context): ?ObjCObject
    {
        return ObjCObject::box(ExtNSOpenGLContext::initWithCGLContextObj($context));
    }

    public function pixelFormat(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSOpenGLContext::pixelFormat($this->handle));
    }

    public function view(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSOpenGLContext::view($this->handle));
    }

    public function setView(int $view): static
    {
        ExtNSOpenGLContext::setView($this->handle, $view);

        return $this;
    }

    public function setFullScreen(): static
    {
        ExtNSOpenGLContext::setFullScreen($this->handle);

        return $this;
    }

    public function setOffScreenWidthHeightRowbytes(int $baseaddr, int $width, int $height, int $rowbytes): static
    {
        ExtNSOpenGLContext::setOffScreenWidthHeightRowbytes($this->handle, $baseaddr, $width, $height, $rowbytes);

        return $this;
    }

    public function clearDrawable(): static
    {
        ExtNSOpenGLContext::clearDrawable($this->handle);

        return $this;
    }

    public function update(): static
    {
        ExtNSOpenGLContext::update($this->handle);

        return $this;
    }

    public function flushBuffer(): static
    {
        ExtNSOpenGLContext::flushBuffer($this->handle);

        return $this;
    }

    public function makeCurrentContext(): static
    {
        ExtNSOpenGLContext::makeCurrentContext($this->handle);

        return $this;
    }

    public static function clearCurrentContext(): void
    {
        ExtNSOpenGLContext::clearCurrentContext();
    }

    public static function currentContext(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSOpenGLContext::currentContext());
    }

    public function copyAttributesFromContextWithMask(int $context, int $mask): static
    {
        ExtNSOpenGLContext::copyAttributesFromContextWithMask($this->handle, $context, $mask);

        return $this;
    }

    public function setValuesForParameter(array $vals, NSOpenGLContextParameter|int $param): static
    {
        ExtNSOpenGLContext::setValuesForParameter($this->handle, $vals, $param instanceof \BackedEnum ? $param->value : $param);

        return $this;
    }

    public function getValuesForParameter(NSOpenGLContextParameter|int $param): array
    {
        return ExtNSOpenGLContext::getValuesForParameter($this->handle, $param instanceof \BackedEnum ? $param->value : $param);
    }

    public function currentVirtualScreen(): int
    {
        return ExtNSOpenGLContext::currentVirtualScreen($this->handle);
    }

    public function setCurrentVirtualScreen(int $currentVirtualScreen): static
    {
        ExtNSOpenGLContext::setCurrentVirtualScreen($this->handle, $currentVirtualScreen);

        return $this;
    }

    public function createTextureFromViewInternalFormat(int $target, int $view, int $format): static
    {
        ExtNSOpenGLContext::createTextureFromViewInternalFormat($this->handle, $target, $view, $format);

        return $this;
    }

    public function CGLContextObj(): int
    {
        return ExtNSOpenGLContext::CGLContextObj($this->handle);
    }

    public function setPixelBufferCubeMapFaceMipMapLevelCurrentVirtualScreen(int $pixelBuffer, int $face, int $level, int $screen): static
    {
        ExtNSOpenGLContext::setPixelBufferCubeMapFaceMipMapLevelCurrentVirtualScreen($this->handle, $pixelBuffer, $face, $level, $screen);

        return $this;
    }

    public function pixelBuffer(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSOpenGLContext::pixelBuffer($this->handle));
    }

    public function pixelBufferCubeMapFace(): int
    {
        return ExtNSOpenGLContext::pixelBufferCubeMapFace($this->handle);
    }

    public function pixelBufferMipMapLevel(): int
    {
        return ExtNSOpenGLContext::pixelBufferMipMapLevel($this->handle);
    }

    public function setTextureImageToPixelBufferColorBuffer(int $pixelBuffer, int $source): static
    {
        ExtNSOpenGLContext::setTextureImageToPixelBufferColorBuffer($this->handle, $pixelBuffer, $source);

        return $this;
    }
}
