<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSOpenGLPixelFormat\NSOpenGLPixelFormat as ExtNSOpenGLPixelFormat;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSOpenGLPixelFormat extends ObjCObject
{
    public static function initWithCGLPixelFormatObj(int $format): ?ObjCObject
    {
        return ObjCObject::box(ExtNSOpenGLPixelFormat::initWithCGLPixelFormatObj($format));
    }

    public static function initWithAttributes(array $attribs): ?ObjCObject
    {
        return ObjCObject::box(ExtNSOpenGLPixelFormat::initWithAttributes($attribs));
    }

    public function getValuesForAttributeForVirtualScreen(int $attrib, int $screen): array
    {
        return ExtNSOpenGLPixelFormat::getValuesForAttributeForVirtualScreen($this->handle, $attrib, $screen);
    }

    public function numberOfVirtualScreens(): int
    {
        return ExtNSOpenGLPixelFormat::numberOfVirtualScreens($this->handle);
    }

    public function CGLPixelFormatObj(): int
    {
        return ExtNSOpenGLPixelFormat::CGLPixelFormatObj($this->handle);
    }
}
