<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSPathCell\NSPathCell as ExtNSPathCell;
use Jovian\Bindings\AppKit\Enums\NSPathStyle;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSPathCell extends ObjCObject
{
    public static function initTextCell(string $string): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathCell::initTextCell($string));
    }

    public static function initImageCell(int $image): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathCell::initImageCell($image));
    }

    public function pathStyle(): NSPathStyle|int
    {
        return ExtNSPathCell::pathStyle($this->handle);
    }

    public function setPathStyle(NSPathStyle|int $pathStyle): static
    {
        ExtNSPathCell::setPathStyle($this->handle, $pathStyle instanceof \BackedEnum ? $pathStyle->value : $pathStyle);

        return $this;
    }

    public function URL(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathCell::URL($this->handle));
    }

    public function setURL(int $URL): static
    {
        ExtNSPathCell::setURL($this->handle, $URL);

        return $this;
    }

    public function setObjectValue(int $obj): static
    {
        ExtNSPathCell::setObjectValue($this->handle, $obj);

        return $this;
    }

    public function allowedTypes(): mixed
    {
        return ExtNSPathCell::allowedTypes($this->handle);
    }

    public function setAllowedTypes(array $allowedTypes): static
    {
        ExtNSPathCell::setAllowedTypes($this->handle, $allowedTypes);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathCell::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSPathCell::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function pathComponentCells(): array
    {
        return ExtNSPathCell::pathComponentCells($this->handle);
    }

    public function setPathComponentCells(array $pathComponentCells): static
    {
        ExtNSPathCell::setPathComponentCells($this->handle, $pathComponentCells);

        return $this;
    }

    public function rectOfPathComponentCellWithFrameInView(int $cell, NSRect $frame, int $view): NSRect
    {
        return NSRect::fromArray(ExtNSPathCell::rectOfPathComponentCellWithFrameInView(...[$this->handle, $cell, ...$frame->toArgs(), $view]));
    }

    public function pathComponentCellAtPointWithFrameInView(NSPoint $point, NSRect $frame, int $view): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathCell::pathComponentCellAtPointWithFrameInView(...[$this->handle, ...$point->toArgs(), ...$frame->toArgs(), $view]));
    }

    public function clickedPathComponentCell(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathCell::clickedPathComponentCell($this->handle));
    }

    public function mouseEnteredWithFrameInView(int $event, NSRect $frame, int $view): static
    {
        ExtNSPathCell::mouseEnteredWithFrameInView(...[$this->handle, $event, ...$frame->toArgs(), $view]);

        return $this;
    }

    public function mouseExitedWithFrameInView(int $event, NSRect $frame, int $view): static
    {
        ExtNSPathCell::mouseExitedWithFrameInView(...[$this->handle, $event, ...$frame->toArgs(), $view]);

        return $this;
    }

    public function doubleAction(): mixed
    {
        return ExtNSPathCell::doubleAction($this->handle);
    }

    public function setDoubleAction(string $doubleAction): static
    {
        ExtNSPathCell::setDoubleAction($this->handle, $doubleAction);

        return $this;
    }

    public function backgroundColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathCell::backgroundColor($this->handle));
    }

    public function setBackgroundColor(int $backgroundColor): static
    {
        ExtNSPathCell::setBackgroundColor($this->handle, $backgroundColor);

        return $this;
    }

    public function placeholderString(): mixed
    {
        return ExtNSPathCell::placeholderString($this->handle);
    }

    public function setPlaceholderString(string $placeholderString): static
    {
        ExtNSPathCell::setPlaceholderString($this->handle, $placeholderString);

        return $this;
    }
}
