<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSPathControl\NSPathControl as ExtNSPathControl;
use Jovian\Bindings\AppKit\Enums\NSPathStyle;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSPathControl extends NSControl
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathControl::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function isEditable(): bool
    {
        return ExtNSPathControl::isEditable($this->handle);
    }

    public function setEditable(bool $editable): static
    {
        ExtNSPathControl::setEditable($this->handle, $editable);

        return $this;
    }

    public function allowedTypes(): mixed
    {
        return ExtNSPathControl::allowedTypes($this->handle);
    }

    public function setAllowedTypes(array $allowedTypes): static
    {
        ExtNSPathControl::setAllowedTypes($this->handle, $allowedTypes);

        return $this;
    }

    public function placeholderString(): mixed
    {
        return ExtNSPathControl::placeholderString($this->handle);
    }

    public function setPlaceholderString(string $placeholderString): static
    {
        ExtNSPathControl::setPlaceholderString($this->handle, $placeholderString);

        return $this;
    }

    public function URL(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathControl::URL($this->handle));
    }

    public function setURL(int $URL): static
    {
        ExtNSPathControl::setURL($this->handle, $URL);

        return $this;
    }

    public function doubleAction(): mixed
    {
        return ExtNSPathControl::doubleAction($this->handle);
    }

    public function setDoubleAction(string $doubleAction): static
    {
        ExtNSPathControl::setDoubleAction($this->handle, $doubleAction);

        return $this;
    }

    public function pathStyle(): NSPathStyle|int
    {
        return ExtNSPathControl::pathStyle($this->handle);
    }

    public function setPathStyle(NSPathStyle|int $pathStyle): static
    {
        ExtNSPathControl::setPathStyle($this->handle, $pathStyle instanceof \BackedEnum ? $pathStyle->value : $pathStyle);

        return $this;
    }

    public function clickedPathItem(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathControl::clickedPathItem($this->handle));
    }

    public function pathItems(): array
    {
        return ExtNSPathControl::pathItems($this->handle);
    }

    public function setPathItems(array $pathItems): static
    {
        ExtNSPathControl::setPathItems($this->handle, $pathItems);

        return $this;
    }

    public function backgroundColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathControl::backgroundColor($this->handle));
    }

    public function setBackgroundColor(int $backgroundColor): static
    {
        ExtNSPathControl::setBackgroundColor($this->handle, $backgroundColor);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathControl::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSPathControl::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function setDraggingSourceOperationMaskForLocal(int $mask, bool $isLocal): static
    {
        ExtNSPathControl::setDraggingSourceOperationMaskForLocal($this->handle, $mask, $isLocal);

        return $this;
    }

    public function menu(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPathControl::menu($this->handle));
    }

    public function setMenu(int $menu): static
    {
        ExtNSPathControl::setMenu($this->handle, $menu);

        return $this;
    }
}
