<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSPopUpButton\NSPopUpButton as ExtNSPopUpButton;
use Jovian\Bindings\AppKit\Enums\NSRectEdge;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSPopUpButton extends NSButton
{
    public static function popUpButtonWithMenuTargetAction(int $menu, int $target, string $action): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopUpButton::popUpButtonWithMenuTargetAction($menu, $target, $action));
    }

    public static function pullDownButtonWithTitleMenu(string $title, int $menu): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopUpButton::pullDownButtonWithTitleMenu($title, $menu));
    }

    public static function pullDownButtonWithImageMenu(int $image, int $menu): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopUpButton::pullDownButtonWithImageMenu($image, $menu));
    }

    public static function pullDownButtonWithTitleImageMenu(string $title, int $image, int $menu): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopUpButton::pullDownButtonWithTitleImageMenu($title, $image, $menu));
    }

    public static function initWithFramePullsDown(NSRect $buttonFrame, bool $flag): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopUpButton::initWithFramePullsDown(...[...$buttonFrame->toArgs(), $flag]));
    }

    public function menu(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopUpButton::menu($this->handle));
    }

    public function setMenu(int $menu): static
    {
        ExtNSPopUpButton::setMenu($this->handle, $menu);

        return $this;
    }

    public function pullsDown(): bool
    {
        return ExtNSPopUpButton::pullsDown($this->handle);
    }

    public function setPullsDown(bool $pullsDown): static
    {
        ExtNSPopUpButton::setPullsDown($this->handle, $pullsDown);

        return $this;
    }

    public function autoenablesItems(): bool
    {
        return ExtNSPopUpButton::autoenablesItems($this->handle);
    }

    public function setAutoenablesItems(bool $autoenablesItems): static
    {
        ExtNSPopUpButton::setAutoenablesItems($this->handle, $autoenablesItems);

        return $this;
    }

    public function preferredEdge(): NSRectEdge|int
    {
        return ExtNSPopUpButton::preferredEdge($this->handle);
    }

    public function setPreferredEdge(NSRectEdge|int $preferredEdge): static
    {
        ExtNSPopUpButton::setPreferredEdge($this->handle, $preferredEdge instanceof \BackedEnum ? $preferredEdge->value : $preferredEdge);

        return $this;
    }

    public function usesItemFromMenu(): bool
    {
        return ExtNSPopUpButton::usesItemFromMenu($this->handle);
    }

    public function setUsesItemFromMenu(bool $usesItemFromMenu): static
    {
        ExtNSPopUpButton::setUsesItemFromMenu($this->handle, $usesItemFromMenu);

        return $this;
    }

    public function altersStateOfSelectedItem(): bool
    {
        return ExtNSPopUpButton::altersStateOfSelectedItem($this->handle);
    }

    public function setAltersStateOfSelectedItem(bool $altersStateOfSelectedItem): static
    {
        ExtNSPopUpButton::setAltersStateOfSelectedItem($this->handle, $altersStateOfSelectedItem);

        return $this;
    }

    public function addItemWithTitle(string $title): static
    {
        ExtNSPopUpButton::addItemWithTitle($this->handle, $title);

        return $this;
    }

    public function addItemsWithTitles(array $itemTitles): static
    {
        ExtNSPopUpButton::addItemsWithTitles($this->handle, $itemTitles);

        return $this;
    }

    public function insertItemWithTitleAtIndex(string $title, int $index): static
    {
        ExtNSPopUpButton::insertItemWithTitleAtIndex($this->handle, $title, $index);

        return $this;
    }

    public function removeItemWithTitle(string $title): static
    {
        ExtNSPopUpButton::removeItemWithTitle($this->handle, $title);

        return $this;
    }

    public function removeItemAtIndex(int $index): static
    {
        ExtNSPopUpButton::removeItemAtIndex($this->handle, $index);

        return $this;
    }

    public function removeAllItems(): static
    {
        ExtNSPopUpButton::removeAllItems($this->handle);

        return $this;
    }

    public function itemArray(): array
    {
        return ExtNSPopUpButton::itemArray($this->handle);
    }

    public function numberOfItems(): int
    {
        return ExtNSPopUpButton::numberOfItems($this->handle);
    }

    public function indexOfItem(int $item): int
    {
        return ExtNSPopUpButton::indexOfItem($this->handle, $item);
    }

    public function indexOfItemWithTitle(string $title): int
    {
        return ExtNSPopUpButton::indexOfItemWithTitle($this->handle, $title);
    }

    public function indexOfItemWithTag(int $tag): int
    {
        return ExtNSPopUpButton::indexOfItemWithTag($this->handle, $tag);
    }

    public function indexOfItemWithRepresentedObject(int $obj): int
    {
        return ExtNSPopUpButton::indexOfItemWithRepresentedObject($this->handle, $obj);
    }

    public function indexOfItemWithTargetAndAction(int $target, string $actionSelector): int
    {
        return ExtNSPopUpButton::indexOfItemWithTargetAndAction($this->handle, $target, $actionSelector);
    }

    public function itemAtIndex(int $index): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopUpButton::itemAtIndex($this->handle, $index));
    }

    public function itemWithTitle(string $title): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopUpButton::itemWithTitle($this->handle, $title));
    }

    public function lastItem(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopUpButton::lastItem($this->handle));
    }

    public function selectItem(int $item): static
    {
        ExtNSPopUpButton::selectItem($this->handle, $item);

        return $this;
    }

    public function selectItemAtIndex(int $index): static
    {
        ExtNSPopUpButton::selectItemAtIndex($this->handle, $index);

        return $this;
    }

    public function selectItemWithTitle(string $title): static
    {
        ExtNSPopUpButton::selectItemWithTitle($this->handle, $title);

        return $this;
    }

    public function selectItemWithTag(int $tag): bool
    {
        return ExtNSPopUpButton::selectItemWithTag($this->handle, $tag);
    }

    public function setTitle(string $string): static
    {
        ExtNSPopUpButton::setTitle($this->handle, $string);

        return $this;
    }

    public function selectedItem(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopUpButton::selectedItem($this->handle));
    }

    public function indexOfSelectedItem(): int
    {
        return ExtNSPopUpButton::indexOfSelectedItem($this->handle);
    }

    public function selectedTag(): int
    {
        return ExtNSPopUpButton::selectedTag($this->handle);
    }

    public function synchronizeTitleAndSelectedItem(): static
    {
        ExtNSPopUpButton::synchronizeTitleAndSelectedItem($this->handle);

        return $this;
    }

    public function itemTitleAtIndex(int $index): ?string
    {
        return ExtNSPopUpButton::itemTitleAtIndex($this->handle, $index);
    }

    public function itemTitles(): array
    {
        return ExtNSPopUpButton::itemTitles($this->handle);
    }

    public function titleOfSelectedItem(): mixed
    {
        return ExtNSPopUpButton::titleOfSelectedItem($this->handle);
    }
}
