<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSPopover\NSPopover as ExtNSPopover;
use Jovian\Bindings\AppKit\Enums\NSPopoverBehavior;
use Jovian\Bindings\AppKit\Enums\NSRectEdge;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSPopover extends NSResponder
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopover::init());
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopover::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSPopover::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function appearance(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopover::appearance($this->handle));
    }

    public function setAppearance(int $appearance): static
    {
        ExtNSPopover::setAppearance($this->handle, $appearance);

        return $this;
    }

    public function effectiveAppearance(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopover::effectiveAppearance($this->handle));
    }

    public function behavior(): NSPopoverBehavior|int
    {
        return ExtNSPopover::behavior($this->handle);
    }

    public function setBehavior(NSPopoverBehavior|int $behavior): static
    {
        ExtNSPopover::setBehavior($this->handle, $behavior instanceof \BackedEnum ? $behavior->value : $behavior);

        return $this;
    }

    public function animates(): bool
    {
        return ExtNSPopover::animates($this->handle);
    }

    public function setAnimates(bool $animates): static
    {
        ExtNSPopover::setAnimates($this->handle, $animates);

        return $this;
    }

    public function contentViewController(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSPopover::contentViewController($this->handle));
    }

    public function setContentViewController(int $contentViewController): static
    {
        ExtNSPopover::setContentViewController($this->handle, $contentViewController);

        return $this;
    }

    public function contentSize(): NSSize
    {
        return NSSize::fromArray(ExtNSPopover::contentSize($this->handle));
    }

    public function setContentSize(NSSize $contentSize): static
    {
        ExtNSPopover::setContentSize(...[$this->handle, ...$contentSize->toArgs()]);

        return $this;
    }

    public function isShown(): bool
    {
        return ExtNSPopover::isShown($this->handle);
    }

    public function isDetached(): bool
    {
        return ExtNSPopover::isDetached($this->handle);
    }

    public function positioningRect(): NSRect
    {
        return NSRect::fromArray(ExtNSPopover::positioningRect($this->handle));
    }

    public function setPositioningRect(NSRect $positioningRect): static
    {
        ExtNSPopover::setPositioningRect(...[$this->handle, ...$positioningRect->toArgs()]);

        return $this;
    }

    public function hasFullSizeContent(): bool
    {
        return ExtNSPopover::hasFullSizeContent($this->handle);
    }

    public function setHasFullSizeContent(bool $hasFullSizeContent): static
    {
        ExtNSPopover::setHasFullSizeContent($this->handle, $hasFullSizeContent);

        return $this;
    }

    public function showRelativeToRectOfViewPreferredEdge(NSRect $positioningRect, int $positioningView, NSRectEdge|int $preferredEdge): static
    {
        ExtNSPopover::showRelativeToRectOfViewPreferredEdge(...[$this->handle, ...$positioningRect->toArgs(), $positioningView, $preferredEdge instanceof \BackedEnum ? $preferredEdge->value : $preferredEdge]);

        return $this;
    }

    public function showRelativeToToolbarItem(int $toolbarItem): static
    {
        ExtNSPopover::showRelativeToToolbarItem($this->handle, $toolbarItem);

        return $this;
    }

    public function performClose(int $sender): static
    {
        ExtNSPopover::performClose($this->handle, $sender);

        return $this;
    }

    public function close(): static
    {
        ExtNSPopover::close($this->handle);

        return $this;
    }
}
