<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSResponder\NSResponder as ExtNSResponder;
use Jovian\Bindings\AppKit\Enums\NSEventGestureAxis;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSResponder extends ObjCObject
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSResponder::init());
    }

    public function nextResponder(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSResponder::nextResponder($this->handle));
    }

    public function setNextResponder(int $nextResponder): static
    {
        ExtNSResponder::setNextResponder($this->handle, $nextResponder);

        return $this;
    }

    public function tryToPerformWith(string $action, int $object): bool
    {
        return ExtNSResponder::tryToPerformWith($this->handle, $action, $object);
    }

    public function performKeyEquivalent(int $event): bool
    {
        return ExtNSResponder::performKeyEquivalent($this->handle, $event);
    }

    public function validRequestorForSendTypeReturnType(string $sendType, string $returnType): ?ObjCObject
    {
        return ObjCObject::box(ExtNSResponder::validRequestorForSendTypeReturnType($this->handle, $sendType, $returnType));
    }

    public function mouseDown(int $event): static
    {
        ExtNSResponder::mouseDown($this->handle, $event);

        return $this;
    }

    public function rightMouseDown(int $event): static
    {
        ExtNSResponder::rightMouseDown($this->handle, $event);

        return $this;
    }

    public function otherMouseDown(int $event): static
    {
        ExtNSResponder::otherMouseDown($this->handle, $event);

        return $this;
    }

    public function mouseUp(int $event): static
    {
        ExtNSResponder::mouseUp($this->handle, $event);

        return $this;
    }

    public function rightMouseUp(int $event): static
    {
        ExtNSResponder::rightMouseUp($this->handle, $event);

        return $this;
    }

    public function otherMouseUp(int $event): static
    {
        ExtNSResponder::otherMouseUp($this->handle, $event);

        return $this;
    }

    public function mouseMoved(int $event): static
    {
        ExtNSResponder::mouseMoved($this->handle, $event);

        return $this;
    }

    public function mouseDragged(int $event): static
    {
        ExtNSResponder::mouseDragged($this->handle, $event);

        return $this;
    }

    public function scrollWheel(int $event): static
    {
        ExtNSResponder::scrollWheel($this->handle, $event);

        return $this;
    }

    public function rightMouseDragged(int $event): static
    {
        ExtNSResponder::rightMouseDragged($this->handle, $event);

        return $this;
    }

    public function otherMouseDragged(int $event): static
    {
        ExtNSResponder::otherMouseDragged($this->handle, $event);

        return $this;
    }

    public function mouseEntered(int $event): static
    {
        ExtNSResponder::mouseEntered($this->handle, $event);

        return $this;
    }

    public function mouseExited(int $event): static
    {
        ExtNSResponder::mouseExited($this->handle, $event);

        return $this;
    }

    public function keyDown(int $event): static
    {
        ExtNSResponder::keyDown($this->handle, $event);

        return $this;
    }

    public function keyUp(int $event): static
    {
        ExtNSResponder::keyUp($this->handle, $event);

        return $this;
    }

    public function flagsChanged(int $event): static
    {
        ExtNSResponder::flagsChanged($this->handle, $event);

        return $this;
    }

    public function tabletPoint(int $event): static
    {
        ExtNSResponder::tabletPoint($this->handle, $event);

        return $this;
    }

    public function tabletProximity(int $event): static
    {
        ExtNSResponder::tabletProximity($this->handle, $event);

        return $this;
    }

    public function cursorUpdate(int $event): static
    {
        ExtNSResponder::cursorUpdate($this->handle, $event);

        return $this;
    }

    public function magnifyWithEvent(int $event): static
    {
        ExtNSResponder::magnifyWithEvent($this->handle, $event);

        return $this;
    }

    public function rotateWithEvent(int $event): static
    {
        ExtNSResponder::rotateWithEvent($this->handle, $event);

        return $this;
    }

    public function swipeWithEvent(int $event): static
    {
        ExtNSResponder::swipeWithEvent($this->handle, $event);

        return $this;
    }

    public function beginGestureWithEvent(int $event): static
    {
        ExtNSResponder::beginGestureWithEvent($this->handle, $event);

        return $this;
    }

    public function endGestureWithEvent(int $event): static
    {
        ExtNSResponder::endGestureWithEvent($this->handle, $event);

        return $this;
    }

    public function smartMagnifyWithEvent(int $event): static
    {
        ExtNSResponder::smartMagnifyWithEvent($this->handle, $event);

        return $this;
    }

    public function changeModeWithEvent(int $event): static
    {
        ExtNSResponder::changeModeWithEvent($this->handle, $event);

        return $this;
    }

    public function touchesBeganWithEvent(int $event): static
    {
        ExtNSResponder::touchesBeganWithEvent($this->handle, $event);

        return $this;
    }

    public function touchesMovedWithEvent(int $event): static
    {
        ExtNSResponder::touchesMovedWithEvent($this->handle, $event);

        return $this;
    }

    public function touchesEndedWithEvent(int $event): static
    {
        ExtNSResponder::touchesEndedWithEvent($this->handle, $event);

        return $this;
    }

    public function touchesCancelledWithEvent(int $event): static
    {
        ExtNSResponder::touchesCancelledWithEvent($this->handle, $event);

        return $this;
    }

    public function quickLookWithEvent(int $event): static
    {
        ExtNSResponder::quickLookWithEvent($this->handle, $event);

        return $this;
    }

    public function pressureChangeWithEvent(int $event): static
    {
        ExtNSResponder::pressureChangeWithEvent($this->handle, $event);

        return $this;
    }

    public function contextMenuKeyDown(int $event): static
    {
        ExtNSResponder::contextMenuKeyDown($this->handle, $event);

        return $this;
    }

    public function noResponderFor(string $eventSelector): static
    {
        ExtNSResponder::noResponderFor($this->handle, $eventSelector);

        return $this;
    }

    public function acceptsFirstResponder(): bool
    {
        return ExtNSResponder::acceptsFirstResponder($this->handle);
    }

    public function becomeFirstResponder(): bool
    {
        return ExtNSResponder::becomeFirstResponder($this->handle);
    }

    public function resignFirstResponder(): bool
    {
        return ExtNSResponder::resignFirstResponder($this->handle);
    }

    public function interpretKeyEvents(array $eventArray): static
    {
        ExtNSResponder::interpretKeyEvents($this->handle, $eventArray);

        return $this;
    }

    public function flushBufferedKeyEvents(): static
    {
        ExtNSResponder::flushBufferedKeyEvents($this->handle);

        return $this;
    }

    public function menu(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSResponder::menu($this->handle));
    }

    public function setMenu(int $menu): static
    {
        ExtNSResponder::setMenu($this->handle, $menu);

        return $this;
    }

    public function showContextHelp(int $sender): static
    {
        ExtNSResponder::showContextHelp($this->handle, $sender);

        return $this;
    }

    public function helpRequested(int $eventPtr): static
    {
        ExtNSResponder::helpRequested($this->handle, $eventPtr);

        return $this;
    }

    public function shouldBeTreatedAsInkEvent(int $event): bool
    {
        return ExtNSResponder::shouldBeTreatedAsInkEvent($this->handle, $event);
    }

    public function wantsScrollEventsForSwipeTrackingOnAxis(NSEventGestureAxis|int $axis): bool
    {
        return ExtNSResponder::wantsScrollEventsForSwipeTrackingOnAxis($this->handle, $axis instanceof \BackedEnum ? $axis->value : $axis);
    }

    public function wantsForwardedScrollEventsForAxis(NSEventGestureAxis|int $axis): bool
    {
        return ExtNSResponder::wantsForwardedScrollEventsForAxis($this->handle, $axis instanceof \BackedEnum ? $axis->value : $axis);
    }

    public function supplementalTargetForActionSender(string $action, int $sender): ?ObjCObject
    {
        return ObjCObject::box(ExtNSResponder::supplementalTargetForActionSender($this->handle, $action, $sender));
    }

    public function undoManager(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSResponder::undoManager($this->handle));
    }

    public function validateProposedFirstResponderForEvent(int $responder, int $event): bool
    {
        return ExtNSResponder::validateProposedFirstResponderForEvent($this->handle, $responder, $event);
    }

    public function presentErrorModalForWindowDelegateDidPresentSelectorContextInfo(int $error, int $window, int $delegate, string $didPresentSelector, int $contextInfo): static
    {
        ExtNSResponder::presentErrorModalForWindowDelegateDidPresentSelectorContextInfo($this->handle, $error, $window, $delegate, $didPresentSelector, $contextInfo);

        return $this;
    }

    public function presentError(int $error): bool
    {
        return ExtNSResponder::presentError($this->handle, $error);
    }

    public function willPresentError(int $error): ?ObjCObject
    {
        return ObjCObject::box(ExtNSResponder::willPresentError($this->handle, $error));
    }

    public function performTextFinderAction(int $sender): static
    {
        ExtNSResponder::performTextFinderAction($this->handle, $sender);

        return $this;
    }

    public function newWindowForTab(int $sender): static
    {
        ExtNSResponder::newWindowForTab($this->handle, $sender);

        return $this;
    }

    public function showWritingTools(int $sender): static
    {
        ExtNSResponder::showWritingTools($this->handle, $sender);

        return $this;
    }
}
