<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSScreen\NSScreen as ExtNSScreen;
use Jovian\Bindings\AppKit\Enums\NSDisplayGamut;
use Jovian\Bindings\AppKit\Enums\NSWindowDepth;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSScreen extends ObjCObject
{
    public static function screens(): array
    {
        return ExtNSScreen::screens();
    }

    public static function mainScreen(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSScreen::mainScreen());
    }

    public static function deepestScreen(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSScreen::deepestScreen());
    }

    public static function screensHaveSeparateSpaces(): bool
    {
        return ExtNSScreen::screensHaveSeparateSpaces();
    }

    public function depth(): NSWindowDepth|int
    {
        return ExtNSScreen::depth($this->handle);
    }

    public function frame(): NSRect
    {
        return NSRect::fromArray(ExtNSScreen::frame($this->handle));
    }

    public function visibleFrame(): NSRect
    {
        return NSRect::fromArray(ExtNSScreen::visibleFrame($this->handle));
    }

    public function deviceDescription(): int
    {
        return ExtNSScreen::deviceDescription($this->handle);
    }

    public function colorSpace(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSScreen::colorSpace($this->handle));
    }

    public function canRepresentDisplayGamut(NSDisplayGamut|int $displayGamut): bool
    {
        return ExtNSScreen::canRepresentDisplayGamut($this->handle, $displayGamut instanceof \BackedEnum ? $displayGamut->value : $displayGamut);
    }

    public function convertRectToBacking(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSScreen::convertRectToBacking(...[$this->handle, ...$rect->toArgs()]));
    }

    public function convertRectFromBacking(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSScreen::convertRectFromBacking(...[$this->handle, ...$rect->toArgs()]));
    }

    public function backingAlignedRectOptions(NSRect $rect, int $options): NSRect
    {
        return NSRect::fromArray(ExtNSScreen::backingAlignedRectOptions(...[$this->handle, ...$rect->toArgs(), $options]));
    }

    public function backingScaleFactor(): float
    {
        return ExtNSScreen::backingScaleFactor($this->handle);
    }

    public function localizedName(): ?string
    {
        return ExtNSScreen::localizedName($this->handle);
    }

    public function safeAreaInsets(): NSEdgeInsets
    {
        return NSEdgeInsets::fromArray(ExtNSScreen::safeAreaInsets($this->handle));
    }

    public function auxiliaryTopLeftArea(): NSRect
    {
        return NSRect::fromArray(ExtNSScreen::auxiliaryTopLeftArea($this->handle));
    }

    public function auxiliaryTopRightArea(): NSRect
    {
        return NSRect::fromArray(ExtNSScreen::auxiliaryTopRightArea($this->handle));
    }

    public function maximumExtendedDynamicRangeColorComponentValue(): float
    {
        return ExtNSScreen::maximumExtendedDynamicRangeColorComponentValue($this->handle);
    }

    public function maximumPotentialExtendedDynamicRangeColorComponentValue(): float
    {
        return ExtNSScreen::maximumPotentialExtendedDynamicRangeColorComponentValue($this->handle);
    }

    public function maximumReferenceExtendedDynamicRangeColorComponentValue(): float
    {
        return ExtNSScreen::maximumReferenceExtendedDynamicRangeColorComponentValue($this->handle);
    }

    public function maximumFramesPerSecond(): int
    {
        return ExtNSScreen::maximumFramesPerSecond($this->handle);
    }

    public function minimumRefreshInterval(): float
    {
        return ExtNSScreen::minimumRefreshInterval($this->handle);
    }

    public function maximumRefreshInterval(): float
    {
        return ExtNSScreen::maximumRefreshInterval($this->handle);
    }

    public function displayUpdateGranularity(): float
    {
        return ExtNSScreen::displayUpdateGranularity($this->handle);
    }

    public function lastDisplayUpdateTimestamp(): float
    {
        return ExtNSScreen::lastDisplayUpdateTimestamp($this->handle);
    }

    public function displayLinkWithTargetSelector(int $target, string $selector): ?ObjCObject
    {
        return ObjCObject::box(ExtNSScreen::displayLinkWithTargetSelector($this->handle, $target, $selector));
    }
}
