<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSSecureTextFieldCell\NSSecureTextFieldCell as ExtNSSecureTextFieldCell;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSSecureTextFieldCell extends NSTextFieldCell
{
    public static function initTextCell(string $string): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSecureTextFieldCell::initTextCell($string));
    }

    public function echosBullets(): bool
    {
        return ExtNSSecureTextFieldCell::echosBullets($this->handle);
    }

    public function setEchosBullets(bool $echosBullets): static
    {
        ExtNSSecureTextFieldCell::setEchosBullets($this->handle, $echosBullets);

        return $this;
    }
}
