<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSSearchFieldCell\NSSearchFieldCell as ExtNSSearchFieldCell;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSSearchFieldCell extends NSTextFieldCell
{
    public static function initTextCell(string $string): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSearchFieldCell::initTextCell($string));
    }

    public function searchButtonCell(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSearchFieldCell::searchButtonCell($this->handle));
    }

    public function setSearchButtonCell(int $searchButtonCell): static
    {
        ExtNSSearchFieldCell::setSearchButtonCell($this->handle, $searchButtonCell);

        return $this;
    }

    public function cancelButtonCell(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSearchFieldCell::cancelButtonCell($this->handle));
    }

    public function setCancelButtonCell(int $cancelButtonCell): static
    {
        ExtNSSearchFieldCell::setCancelButtonCell($this->handle, $cancelButtonCell);

        return $this;
    }

    public function resetSearchButtonCell(): static
    {
        ExtNSSearchFieldCell::resetSearchButtonCell($this->handle);

        return $this;
    }

    public function resetCancelButtonCell(): static
    {
        ExtNSSearchFieldCell::resetCancelButtonCell($this->handle);

        return $this;
    }

    public function searchTextRectForBounds(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSSearchFieldCell::searchTextRectForBounds(...[$this->handle, ...$rect->toArgs()]));
    }

    public function searchButtonRectForBounds(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSSearchFieldCell::searchButtonRectForBounds(...[$this->handle, ...$rect->toArgs()]));
    }

    public function cancelButtonRectForBounds(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSSearchFieldCell::cancelButtonRectForBounds(...[$this->handle, ...$rect->toArgs()]));
    }

    public function searchMenuTemplate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSearchFieldCell::searchMenuTemplate($this->handle));
    }

    public function setSearchMenuTemplate(int $searchMenuTemplate): static
    {
        ExtNSSearchFieldCell::setSearchMenuTemplate($this->handle, $searchMenuTemplate);

        return $this;
    }

    public function sendsWholeSearchString(): bool
    {
        return ExtNSSearchFieldCell::sendsWholeSearchString($this->handle);
    }

    public function setSendsWholeSearchString(bool $sendsWholeSearchString): static
    {
        ExtNSSearchFieldCell::setSendsWholeSearchString($this->handle, $sendsWholeSearchString);

        return $this;
    }

    public function maximumRecents(): int
    {
        return ExtNSSearchFieldCell::maximumRecents($this->handle);
    }

    public function setMaximumRecents(int $maximumRecents): static
    {
        ExtNSSearchFieldCell::setMaximumRecents($this->handle, $maximumRecents);

        return $this;
    }

    public function recentSearches(): array
    {
        return ExtNSSearchFieldCell::recentSearches($this->handle);
    }

    public function setRecentSearches(array $recentSearches): static
    {
        ExtNSSearchFieldCell::setRecentSearches($this->handle, $recentSearches);

        return $this;
    }

    public function recentsAutosaveName(): mixed
    {
        return ExtNSSearchFieldCell::recentsAutosaveName($this->handle);
    }

    public function setRecentsAutosaveName(string $recentsAutosaveName): static
    {
        ExtNSSearchFieldCell::setRecentsAutosaveName($this->handle, $recentsAutosaveName);

        return $this;
    }

    public function sendsSearchStringImmediately(): bool
    {
        return ExtNSSearchFieldCell::sendsSearchStringImmediately($this->handle);
    }

    public function setSendsSearchStringImmediately(bool $sendsSearchStringImmediately): static
    {
        ExtNSSearchFieldCell::setSendsSearchStringImmediately($this->handle, $sendsSearchStringImmediately);

        return $this;
    }
}
