<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSSegmentedControl\NSSegmentedControl as ExtNSSegmentedControl;
use Jovian\Bindings\AppKit\Enums\NSImageScaling;
use Jovian\Bindings\AppKit\Enums\NSSegmentDistribution;
use Jovian\Bindings\AppKit\Enums\NSSegmentStyle;
use Jovian\Bindings\AppKit\Enums\NSSegmentSwitchTracking;
use Jovian\Bindings\AppKit\Enums\NSTextAlignment;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSSegmentedControl extends NSControl
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSegmentedControl::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function segmentCount(): int
    {
        return ExtNSSegmentedControl::segmentCount($this->handle);
    }

    public function setSegmentCount(int $segmentCount): static
    {
        ExtNSSegmentedControl::setSegmentCount($this->handle, $segmentCount);

        return $this;
    }

    public function selectedSegment(): int
    {
        return ExtNSSegmentedControl::selectedSegment($this->handle);
    }

    public function setSelectedSegment(int $selectedSegment): static
    {
        ExtNSSegmentedControl::setSelectedSegment($this->handle, $selectedSegment);

        return $this;
    }

    public function selectSegmentWithTag(int $tag): bool
    {
        return ExtNSSegmentedControl::selectSegmentWithTag($this->handle, $tag);
    }

    public function setWidthForSegment(float $width, int $segment): static
    {
        ExtNSSegmentedControl::setWidthForSegment($this->handle, $width, $segment);

        return $this;
    }

    public function widthForSegment(int $segment): float
    {
        return ExtNSSegmentedControl::widthForSegment($this->handle, $segment);
    }

    public function setImageForSegment(int $image, int $segment): static
    {
        ExtNSSegmentedControl::setImageForSegment($this->handle, $image, $segment);

        return $this;
    }

    public function imageForSegment(int $segment): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSegmentedControl::imageForSegment($this->handle, $segment));
    }

    public function setImageScalingForSegment(NSImageScaling|int $scaling, int $segment): static
    {
        ExtNSSegmentedControl::setImageScalingForSegment($this->handle, $scaling instanceof \BackedEnum ? $scaling->value : $scaling, $segment);

        return $this;
    }

    public function imageScalingForSegment(int $segment): NSImageScaling|int
    {
        return ExtNSSegmentedControl::imageScalingForSegment($this->handle, $segment);
    }

    public function setLabelForSegment(string $label, int $segment): static
    {
        ExtNSSegmentedControl::setLabelForSegment($this->handle, $label, $segment);

        return $this;
    }

    public function labelForSegment(int $segment): mixed
    {
        return ExtNSSegmentedControl::labelForSegment($this->handle, $segment);
    }

    public function setMenuForSegment(int $menu, int $segment): static
    {
        ExtNSSegmentedControl::setMenuForSegment($this->handle, $menu, $segment);

        return $this;
    }

    public function menuForSegment(int $segment): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSegmentedControl::menuForSegment($this->handle, $segment));
    }

    public function setSelectedForSegment(bool $selected, int $segment): static
    {
        ExtNSSegmentedControl::setSelectedForSegment($this->handle, $selected, $segment);

        return $this;
    }

    public function isSelectedForSegment(int $segment): bool
    {
        return ExtNSSegmentedControl::isSelectedForSegment($this->handle, $segment);
    }

    public function setEnabledForSegment(bool $enabled, int $segment): static
    {
        ExtNSSegmentedControl::setEnabledForSegment($this->handle, $enabled, $segment);

        return $this;
    }

    public function isEnabledForSegment(int $segment): bool
    {
        return ExtNSSegmentedControl::isEnabledForSegment($this->handle, $segment);
    }

    public function setToolTipForSegment(string $toolTip, int $segment): static
    {
        ExtNSSegmentedControl::setToolTipForSegment($this->handle, $toolTip, $segment);

        return $this;
    }

    public function toolTipForSegment(int $segment): mixed
    {
        return ExtNSSegmentedControl::toolTipForSegment($this->handle, $segment);
    }

    public function setTagForSegment(int $tag, int $segment): static
    {
        ExtNSSegmentedControl::setTagForSegment($this->handle, $tag, $segment);

        return $this;
    }

    public function tagForSegment(int $segment): int
    {
        return ExtNSSegmentedControl::tagForSegment($this->handle, $segment);
    }

    public function setShowsMenuIndicatorForSegment(bool $showsMenuIndicator, int $segment): static
    {
        ExtNSSegmentedControl::setShowsMenuIndicatorForSegment($this->handle, $showsMenuIndicator, $segment);

        return $this;
    }

    public function showsMenuIndicatorForSegment(int $segment): bool
    {
        return ExtNSSegmentedControl::showsMenuIndicatorForSegment($this->handle, $segment);
    }

    public function segmentStyle(): NSSegmentStyle|int
    {
        return ExtNSSegmentedControl::segmentStyle($this->handle);
    }

    public function setSegmentStyle(NSSegmentStyle|int $segmentStyle): static
    {
        ExtNSSegmentedControl::setSegmentStyle($this->handle, $segmentStyle instanceof \BackedEnum ? $segmentStyle->value : $segmentStyle);

        return $this;
    }

    public function isSpringLoaded(): bool
    {
        return ExtNSSegmentedControl::isSpringLoaded($this->handle);
    }

    public function setSpringLoaded(bool $springLoaded): static
    {
        ExtNSSegmentedControl::setSpringLoaded($this->handle, $springLoaded);

        return $this;
    }

    public function trackingMode(): NSSegmentSwitchTracking|int
    {
        return ExtNSSegmentedControl::trackingMode($this->handle);
    }

    public function setTrackingMode(NSSegmentSwitchTracking|int $trackingMode): static
    {
        ExtNSSegmentedControl::setTrackingMode($this->handle, $trackingMode instanceof \BackedEnum ? $trackingMode->value : $trackingMode);

        return $this;
    }

    public function doubleValueForSelectedSegment(): float
    {
        return ExtNSSegmentedControl::doubleValueForSelectedSegment($this->handle);
    }

    public function selectedSegmentBezelColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSegmentedControl::selectedSegmentBezelColor($this->handle));
    }

    public function setSelectedSegmentBezelColor(int $selectedSegmentBezelColor): static
    {
        ExtNSSegmentedControl::setSelectedSegmentBezelColor($this->handle, $selectedSegmentBezelColor);

        return $this;
    }

    public function indexOfSelectedItem(): int
    {
        return ExtNSSegmentedControl::indexOfSelectedItem($this->handle);
    }

    public function setAlignmentForSegment(NSTextAlignment|int $alignment, int $segment): static
    {
        ExtNSSegmentedControl::setAlignmentForSegment($this->handle, $alignment instanceof \BackedEnum ? $alignment->value : $alignment, $segment);

        return $this;
    }

    public function alignmentForSegment(int $segment): NSTextAlignment|int
    {
        return ExtNSSegmentedControl::alignmentForSegment($this->handle, $segment);
    }

    public function segmentDistribution(): NSSegmentDistribution|int
    {
        return ExtNSSegmentedControl::segmentDistribution($this->handle);
    }

    public function setSegmentDistribution(NSSegmentDistribution|int $segmentDistribution): static
    {
        ExtNSSegmentedControl::setSegmentDistribution($this->handle, $segmentDistribution instanceof \BackedEnum ? $segmentDistribution->value : $segmentDistribution);

        return $this;
    }

    public function compressWithPrioritizedCompressionOptions(array $prioritizedOptions): static
    {
        ExtNSSegmentedControl::compressWithPrioritizedCompressionOptions($this->handle, $prioritizedOptions);

        return $this;
    }

    public function minimumSizeWithPrioritizedCompressionOptions(array $prioritizedOptions): NSSize
    {
        return NSSize::fromArray(ExtNSSegmentedControl::minimumSizeWithPrioritizedCompressionOptions($this->handle, $prioritizedOptions));
    }

    public function activeCompressionOptions(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSegmentedControl::activeCompressionOptions($this->handle));
    }

    public static function segmentedControlWithLabelsTrackingModeTargetAction(array $labels, NSSegmentSwitchTracking|int $trackingMode, int $target, string $action): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSegmentedControl::segmentedControlWithLabelsTrackingModeTargetAction($labels, $trackingMode instanceof \BackedEnum ? $trackingMode->value : $trackingMode, $target, $action));
    }

    public static function segmentedControlWithImagesTrackingModeTargetAction(array $images, NSSegmentSwitchTracking|int $trackingMode, int $target, string $action): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSegmentedControl::segmentedControlWithImagesTrackingModeTargetAction($images, $trackingMode instanceof \BackedEnum ? $trackingMode->value : $trackingMode, $target, $action));
    }
}
