<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSSlider\NSSlider as ExtNSSlider;
use Jovian\Bindings\AppKit\Enums\NSSliderType;
use Jovian\Bindings\AppKit\Enums\NSTickMarkPosition;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSSlider extends NSControl
{
    public function sliderType(): NSSliderType|int
    {
        return ExtNSSlider::sliderType($this->handle);
    }

    public function setSliderType(NSSliderType|int $sliderType): static
    {
        ExtNSSlider::setSliderType($this->handle, $sliderType instanceof \BackedEnum ? $sliderType->value : $sliderType);

        return $this;
    }

    public function minValue(): float
    {
        return ExtNSSlider::minValue($this->handle);
    }

    public function setMinValue(float $minValue): static
    {
        ExtNSSlider::setMinValue($this->handle, $minValue);

        return $this;
    }

    public function maxValue(): float
    {
        return ExtNSSlider::maxValue($this->handle);
    }

    public function setMaxValue(float $maxValue): static
    {
        ExtNSSlider::setMaxValue($this->handle, $maxValue);

        return $this;
    }

    public function altIncrementValue(): float
    {
        return ExtNSSlider::altIncrementValue($this->handle);
    }

    public function setAltIncrementValue(float $altIncrementValue): static
    {
        ExtNSSlider::setAltIncrementValue($this->handle, $altIncrementValue);

        return $this;
    }

    public function knobThickness(): float
    {
        return ExtNSSlider::knobThickness($this->handle);
    }

    public function acceptsFirstMouse(int $event): bool
    {
        return ExtNSSlider::acceptsFirstMouse($this->handle, $event);
    }

    public function isVertical(): bool
    {
        return ExtNSSlider::isVertical($this->handle);
    }

    public function setVertical(bool $vertical): static
    {
        ExtNSSlider::setVertical($this->handle, $vertical);

        return $this;
    }

    public function trackFillColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSlider::trackFillColor($this->handle));
    }

    public function setTrackFillColor(int $trackFillColor): static
    {
        ExtNSSlider::setTrackFillColor($this->handle, $trackFillColor);

        return $this;
    }

    public function numberOfTickMarks(): int
    {
        return ExtNSSlider::numberOfTickMarks($this->handle);
    }

    public function setNumberOfTickMarks(int $numberOfTickMarks): static
    {
        ExtNSSlider::setNumberOfTickMarks($this->handle, $numberOfTickMarks);

        return $this;
    }

    public function tickMarkPosition(): NSTickMarkPosition|int
    {
        return ExtNSSlider::tickMarkPosition($this->handle);
    }

    public function setTickMarkPosition(NSTickMarkPosition|int $tickMarkPosition): static
    {
        ExtNSSlider::setTickMarkPosition($this->handle, $tickMarkPosition instanceof \BackedEnum ? $tickMarkPosition->value : $tickMarkPosition);

        return $this;
    }

    public function allowsTickMarkValuesOnly(): bool
    {
        return ExtNSSlider::allowsTickMarkValuesOnly($this->handle);
    }

    public function setAllowsTickMarkValuesOnly(bool $allowsTickMarkValuesOnly): static
    {
        ExtNSSlider::setAllowsTickMarkValuesOnly($this->handle, $allowsTickMarkValuesOnly);

        return $this;
    }

    public function tickMarkValueAtIndex(int $index): float
    {
        return ExtNSSlider::tickMarkValueAtIndex($this->handle, $index);
    }

    public function rectOfTickMarkAtIndex(int $index): NSRect
    {
        return NSRect::fromArray(ExtNSSlider::rectOfTickMarkAtIndex($this->handle, $index));
    }

    public function indexOfTickMarkAtPoint(NSPoint $point): int
    {
        return ExtNSSlider::indexOfTickMarkAtPoint(...[$this->handle, ...$point->toArgs()]);
    }

    public function closestTickMarkValueToValue(float $value): float
    {
        return ExtNSSlider::closestTickMarkValueToValue($this->handle, $value);
    }

    public static function sliderWithTargetAction(int $target, string $action): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSlider::sliderWithTargetAction($target, $action));
    }

    public static function sliderWithValueMinValueMaxValueTargetAction(float $value, float $minValue, float $maxValue, int $target, string $action): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSlider::sliderWithValueMinValueMaxValueTargetAction($value, $minValue, $maxValue, $target, $action));
    }
}
