<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSSplitView\NSSplitView as ExtNSSplitView;
use Jovian\Bindings\AppKit\Enums\NSSplitViewDividerStyle;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSSplitView extends NSView
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSplitView::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function isVertical(): bool
    {
        return ExtNSSplitView::isVertical($this->handle);
    }

    public function setVertical(bool $vertical): static
    {
        ExtNSSplitView::setVertical($this->handle, $vertical);

        return $this;
    }

    public function dividerStyle(): NSSplitViewDividerStyle|int
    {
        return ExtNSSplitView::dividerStyle($this->handle);
    }

    public function setDividerStyle(NSSplitViewDividerStyle|int $dividerStyle): static
    {
        ExtNSSplitView::setDividerStyle($this->handle, $dividerStyle instanceof \BackedEnum ? $dividerStyle->value : $dividerStyle);

        return $this;
    }

    public function autosaveName(): mixed
    {
        return ExtNSSplitView::autosaveName($this->handle);
    }

    public function setAutosaveName(int $autosaveName): static
    {
        ExtNSSplitView::setAutosaveName($this->handle, $autosaveName);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSplitView::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSSplitView::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function drawDividerInRect(NSRect $rect): static
    {
        ExtNSSplitView::drawDividerInRect(...[$this->handle, ...$rect->toArgs()]);

        return $this;
    }

    public function dividerColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSSplitView::dividerColor($this->handle));
    }

    public function dividerThickness(): float
    {
        return ExtNSSplitView::dividerThickness($this->handle);
    }

    public function adjustSubviews(): static
    {
        ExtNSSplitView::adjustSubviews($this->handle);

        return $this;
    }

    public function isSubviewCollapsed(int $subview): bool
    {
        return ExtNSSplitView::isSubviewCollapsed($this->handle, $subview);
    }

    public function minPossiblePositionOfDividerAtIndex(int $dividerIndex): float
    {
        return ExtNSSplitView::minPossiblePositionOfDividerAtIndex($this->handle, $dividerIndex);
    }

    public function maxPossiblePositionOfDividerAtIndex(int $dividerIndex): float
    {
        return ExtNSSplitView::maxPossiblePositionOfDividerAtIndex($this->handle, $dividerIndex);
    }

    public function setPositionOfDividerAtIndex(float $position, int $dividerIndex): static
    {
        ExtNSSplitView::setPositionOfDividerAtIndex($this->handle, $position, $dividerIndex);

        return $this;
    }

    public function holdingPriorityForSubviewAtIndex(int $subviewIndex): float
    {
        return ExtNSSplitView::holdingPriorityForSubviewAtIndex($this->handle, $subviewIndex);
    }

    public function setHoldingPriorityForSubviewAtIndex(int $priority, int $subviewIndex): static
    {
        ExtNSSplitView::setHoldingPriorityForSubviewAtIndex($this->handle, $priority, $subviewIndex);

        return $this;
    }

    public function arrangesAllSubviews(): bool
    {
        return ExtNSSplitView::arrangesAllSubviews($this->handle);
    }

    public function setArrangesAllSubviews(bool $arrangesAllSubviews): static
    {
        ExtNSSplitView::setArrangesAllSubviews($this->handle, $arrangesAllSubviews);

        return $this;
    }

    public function arrangedSubviews(): array
    {
        return ExtNSSplitView::arrangedSubviews($this->handle);
    }

    public function addArrangedSubview(int $view): static
    {
        ExtNSSplitView::addArrangedSubview($this->handle, $view);

        return $this;
    }

    public function insertArrangedSubviewAtIndex(int $view, int $index): static
    {
        ExtNSSplitView::insertArrangedSubviewAtIndex($this->handle, $view, $index);

        return $this;
    }

    public function removeArrangedSubview(int $view): static
    {
        ExtNSSplitView::removeArrangedSubview($this->handle, $view);

        return $this;
    }
}
