<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSStepperCell\NSStepperCell as ExtNSStepperCell;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSStepperCell extends NSCell
{
    public static function initTextCell(string $string): ?ObjCObject
    {
        return ObjCObject::box(ExtNSStepperCell::initTextCell($string));
    }

    public static function initImageCell(int $image): ?ObjCObject
    {
        return ObjCObject::box(ExtNSStepperCell::initImageCell($image));
    }

    public function minValue(): float
    {
        return ExtNSStepperCell::minValue($this->handle);
    }

    public function setMinValue(float $minValue): static
    {
        ExtNSStepperCell::setMinValue($this->handle, $minValue);

        return $this;
    }

    public function maxValue(): float
    {
        return ExtNSStepperCell::maxValue($this->handle);
    }

    public function setMaxValue(float $maxValue): static
    {
        ExtNSStepperCell::setMaxValue($this->handle, $maxValue);

        return $this;
    }

    public function increment(): float
    {
        return ExtNSStepperCell::increment($this->handle);
    }

    public function setIncrement(float $increment): static
    {
        ExtNSStepperCell::setIncrement($this->handle, $increment);

        return $this;
    }

    public function valueWraps(): bool
    {
        return ExtNSStepperCell::valueWraps($this->handle);
    }

    public function setValueWraps(bool $valueWraps): static
    {
        ExtNSStepperCell::setValueWraps($this->handle, $valueWraps);

        return $this;
    }

    public function autorepeat(): bool
    {
        return ExtNSStepperCell::autorepeat($this->handle);
    }

    public function setAutorepeat(bool $autorepeat): static
    {
        ExtNSStepperCell::setAutorepeat($this->handle, $autorepeat);

        return $this;
    }
}
