<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSTableColumn\NSTableColumn as ExtNSTableColumn;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSTableColumn extends ObjCObject
{
    public static function initWithIdentifier(int $identifier): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTableColumn::initWithIdentifier($identifier));
    }

    public function identifier(): ?string
    {
        return ExtNSTableColumn::identifier($this->handle);
    }

    public function setIdentifier(int $identifier): static
    {
        ExtNSTableColumn::setIdentifier($this->handle, $identifier);

        return $this;
    }

    public function tableView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTableColumn::tableView($this->handle));
    }

    public function setTableView(int $tableView): static
    {
        ExtNSTableColumn::setTableView($this->handle, $tableView);

        return $this;
    }

    public function width(): float
    {
        return ExtNSTableColumn::width($this->handle);
    }

    public function setWidth(float $width): static
    {
        ExtNSTableColumn::setWidth($this->handle, $width);

        return $this;
    }

    public function minWidth(): float
    {
        return ExtNSTableColumn::minWidth($this->handle);
    }

    public function setMinWidth(float $minWidth): static
    {
        ExtNSTableColumn::setMinWidth($this->handle, $minWidth);

        return $this;
    }

    public function maxWidth(): float
    {
        return ExtNSTableColumn::maxWidth($this->handle);
    }

    public function setMaxWidth(float $maxWidth): static
    {
        ExtNSTableColumn::setMaxWidth($this->handle, $maxWidth);

        return $this;
    }

    public function title(): ?string
    {
        return ExtNSTableColumn::title($this->handle);
    }

    public function setTitle(string $title): static
    {
        ExtNSTableColumn::setTitle($this->handle, $title);

        return $this;
    }

    public function headerCell(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTableColumn::headerCell($this->handle));
    }

    public function setHeaderCell(int $headerCell): static
    {
        ExtNSTableColumn::setHeaderCell($this->handle, $headerCell);

        return $this;
    }

    public function isEditable(): bool
    {
        return ExtNSTableColumn::isEditable($this->handle);
    }

    public function setEditable(bool $editable): static
    {
        ExtNSTableColumn::setEditable($this->handle, $editable);

        return $this;
    }

    public function sizeToFit(): static
    {
        ExtNSTableColumn::sizeToFit($this->handle);

        return $this;
    }

    public function sortDescriptorPrototype(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTableColumn::sortDescriptorPrototype($this->handle));
    }

    public function setSortDescriptorPrototype(int $sortDescriptorPrototype): static
    {
        ExtNSTableColumn::setSortDescriptorPrototype($this->handle, $sortDescriptorPrototype);

        return $this;
    }

    public function resizingMask(): int
    {
        return ExtNSTableColumn::resizingMask($this->handle);
    }

    public function setResizingMask(int $resizingMask): static
    {
        ExtNSTableColumn::setResizingMask($this->handle, $resizingMask);

        return $this;
    }

    public function headerToolTip(): mixed
    {
        return ExtNSTableColumn::headerToolTip($this->handle);
    }

    public function setHeaderToolTip(string $headerToolTip): static
    {
        ExtNSTableColumn::setHeaderToolTip($this->handle, $headerToolTip);

        return $this;
    }

    public function isHidden(): bool
    {
        return ExtNSTableColumn::isHidden($this->handle);
    }

    public function setHidden(bool $hidden): static
    {
        ExtNSTableColumn::setHidden($this->handle, $hidden);

        return $this;
    }
}
