<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSTableHeaderView\NSTableHeaderView as ExtNSTableHeaderView;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSTableHeaderView extends NSView
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTableHeaderView::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function tableView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTableHeaderView::tableView($this->handle));
    }

    public function setTableView(int $tableView): static
    {
        ExtNSTableHeaderView::setTableView($this->handle, $tableView);

        return $this;
    }

    public function draggedColumn(): int
    {
        return ExtNSTableHeaderView::draggedColumn($this->handle);
    }

    public function draggedDistance(): float
    {
        return ExtNSTableHeaderView::draggedDistance($this->handle);
    }

    public function resizedColumn(): int
    {
        return ExtNSTableHeaderView::resizedColumn($this->handle);
    }

    public function headerRectOfColumn(int $column): NSRect
    {
        return NSRect::fromArray(ExtNSTableHeaderView::headerRectOfColumn($this->handle, $column));
    }

    public function columnAtPoint(NSPoint $point): int
    {
        return ExtNSTableHeaderView::columnAtPoint(...[$this->handle, ...$point->toArgs()]);
    }
}
