<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSTableRowView\NSTableRowView as ExtNSTableRowView;
use Jovian\Bindings\AppKit\Enums\NSBackgroundStyle;
use Jovian\Bindings\AppKit\Enums\NSTableViewDraggingDestinationFeedbackStyle;
use Jovian\Bindings\AppKit\Enums\NSTableViewSelectionHighlightStyle;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSTableRowView extends NSView
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTableRowView::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function selectionHighlightStyle(): NSTableViewSelectionHighlightStyle|int
    {
        return ExtNSTableRowView::selectionHighlightStyle($this->handle);
    }

    public function setSelectionHighlightStyle(NSTableViewSelectionHighlightStyle|int $selectionHighlightStyle): static
    {
        ExtNSTableRowView::setSelectionHighlightStyle($this->handle, $selectionHighlightStyle instanceof \BackedEnum ? $selectionHighlightStyle->value : $selectionHighlightStyle);

        return $this;
    }

    public function isEmphasized(): bool
    {
        return ExtNSTableRowView::isEmphasized($this->handle);
    }

    public function setEmphasized(bool $emphasized): static
    {
        ExtNSTableRowView::setEmphasized($this->handle, $emphasized);

        return $this;
    }

    public function isGroupRowStyle(): bool
    {
        return ExtNSTableRowView::isGroupRowStyle($this->handle);
    }

    public function setGroupRowStyle(bool $groupRowStyle): static
    {
        ExtNSTableRowView::setGroupRowStyle($this->handle, $groupRowStyle);

        return $this;
    }

    public function isSelected(): bool
    {
        return ExtNSTableRowView::isSelected($this->handle);
    }

    public function setSelected(bool $selected): static
    {
        ExtNSTableRowView::setSelected($this->handle, $selected);

        return $this;
    }

    public function isPreviousRowSelected(): bool
    {
        return ExtNSTableRowView::isPreviousRowSelected($this->handle);
    }

    public function setPreviousRowSelected(bool $previousRowSelected): static
    {
        ExtNSTableRowView::setPreviousRowSelected($this->handle, $previousRowSelected);

        return $this;
    }

    public function isNextRowSelected(): bool
    {
        return ExtNSTableRowView::isNextRowSelected($this->handle);
    }

    public function setNextRowSelected(bool $nextRowSelected): static
    {
        ExtNSTableRowView::setNextRowSelected($this->handle, $nextRowSelected);

        return $this;
    }

    public function isFloating(): bool
    {
        return ExtNSTableRowView::isFloating($this->handle);
    }

    public function setFloating(bool $floating): static
    {
        ExtNSTableRowView::setFloating($this->handle, $floating);

        return $this;
    }

    public function isTargetForDropOperation(): bool
    {
        return ExtNSTableRowView::isTargetForDropOperation($this->handle);
    }

    public function setTargetForDropOperation(bool $targetForDropOperation): static
    {
        ExtNSTableRowView::setTargetForDropOperation($this->handle, $targetForDropOperation);

        return $this;
    }

    public function draggingDestinationFeedbackStyle(): NSTableViewDraggingDestinationFeedbackStyle|int
    {
        return ExtNSTableRowView::draggingDestinationFeedbackStyle($this->handle);
    }

    public function setDraggingDestinationFeedbackStyle(NSTableViewDraggingDestinationFeedbackStyle|int $draggingDestinationFeedbackStyle): static
    {
        ExtNSTableRowView::setDraggingDestinationFeedbackStyle($this->handle, $draggingDestinationFeedbackStyle instanceof \BackedEnum ? $draggingDestinationFeedbackStyle->value : $draggingDestinationFeedbackStyle);

        return $this;
    }

    public function indentationForDropOperation(): float
    {
        return ExtNSTableRowView::indentationForDropOperation($this->handle);
    }

    public function setIndentationForDropOperation(float $indentationForDropOperation): static
    {
        ExtNSTableRowView::setIndentationForDropOperation($this->handle, $indentationForDropOperation);

        return $this;
    }

    public function interiorBackgroundStyle(): NSBackgroundStyle|int
    {
        return ExtNSTableRowView::interiorBackgroundStyle($this->handle);
    }

    public function backgroundColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTableRowView::backgroundColor($this->handle));
    }

    public function setBackgroundColor(int $backgroundColor): static
    {
        ExtNSTableRowView::setBackgroundColor($this->handle, $backgroundColor);

        return $this;
    }

    public function drawBackgroundInRect(NSRect $dirtyRect): static
    {
        ExtNSTableRowView::drawBackgroundInRect(...[$this->handle, ...$dirtyRect->toArgs()]);

        return $this;
    }

    public function drawSelectionInRect(NSRect $dirtyRect): static
    {
        ExtNSTableRowView::drawSelectionInRect(...[$this->handle, ...$dirtyRect->toArgs()]);

        return $this;
    }

    public function drawSeparatorInRect(NSRect $dirtyRect): static
    {
        ExtNSTableRowView::drawSeparatorInRect(...[$this->handle, ...$dirtyRect->toArgs()]);

        return $this;
    }

    public function drawDraggingDestinationFeedbackInRect(NSRect $dirtyRect): static
    {
        ExtNSTableRowView::drawDraggingDestinationFeedbackInRect(...[$this->handle, ...$dirtyRect->toArgs()]);

        return $this;
    }

    public function viewAtColumn(int $column): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTableRowView::viewAtColumn($this->handle, $column));
    }

    public function numberOfColumns(): int
    {
        return ExtNSTableRowView::numberOfColumns($this->handle);
    }
}
