<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSTableHeaderCell\NSTableHeaderCell as ExtNSTableHeaderCell;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSTableHeaderCell extends NSTextFieldCell
{
    public static function initTextCell(string $string): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTableHeaderCell::initTextCell($string));
    }

    public function drawSortIndicatorWithFrameInViewAscendingPriority(NSRect $cellFrame, int $controlView, bool $ascending, int $priority): static
    {
        ExtNSTableHeaderCell::drawSortIndicatorWithFrameInViewAscendingPriority(...[$this->handle, ...$cellFrame->toArgs(), $controlView, $ascending, $priority]);

        return $this;
    }

    public function sortIndicatorRectForBounds(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSTableHeaderCell::sortIndicatorRectForBounds(...[$this->handle, ...$rect->toArgs()]));
    }
}
