<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSTabViewItem\NSTabViewItem as ExtNSTabViewItem;
use Jovian\Bindings\AppKit\Enums\NSTabState;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSTabViewItem extends ObjCObject
{
    public static function tabViewItemWithViewController(int $viewController): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTabViewItem::tabViewItemWithViewController($viewController));
    }

    public static function initWithIdentifier(int $identifier): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTabViewItem::initWithIdentifier($identifier));
    }

    public function identifier(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTabViewItem::identifier($this->handle));
    }

    public function setIdentifier(int $identifier): static
    {
        ExtNSTabViewItem::setIdentifier($this->handle, $identifier);

        return $this;
    }

    public function color(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTabViewItem::color($this->handle));
    }

    public function setColor(int $color): static
    {
        ExtNSTabViewItem::setColor($this->handle, $color);

        return $this;
    }

    public function label(): ?string
    {
        return ExtNSTabViewItem::label($this->handle);
    }

    public function setLabel(string $label): static
    {
        ExtNSTabViewItem::setLabel($this->handle, $label);

        return $this;
    }

    public function image(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTabViewItem::image($this->handle));
    }

    public function setImage(int $image): static
    {
        ExtNSTabViewItem::setImage($this->handle, $image);

        return $this;
    }

    public function view(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTabViewItem::view($this->handle));
    }

    public function setView(int $view): static
    {
        ExtNSTabViewItem::setView($this->handle, $view);

        return $this;
    }

    public function viewController(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTabViewItem::viewController($this->handle));
    }

    public function setViewController(int $viewController): static
    {
        ExtNSTabViewItem::setViewController($this->handle, $viewController);

        return $this;
    }

    public function tabState(): NSTabState|int
    {
        return ExtNSTabViewItem::tabState($this->handle);
    }

    public function tabView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTabViewItem::tabView($this->handle));
    }

    public function initialFirstResponder(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTabViewItem::initialFirstResponder($this->handle));
    }

    public function setInitialFirstResponder(int $initialFirstResponder): static
    {
        ExtNSTabViewItem::setInitialFirstResponder($this->handle, $initialFirstResponder);

        return $this;
    }

    public function toolTip(): mixed
    {
        return ExtNSTabViewItem::toolTip($this->handle);
    }

    public function setToolTip(string $toolTip): static
    {
        ExtNSTabViewItem::setToolTip($this->handle, $toolTip);

        return $this;
    }

    public function drawLabelInRect(bool $shouldTruncateLabel, NSRect $labelRect): static
    {
        ExtNSTabViewItem::drawLabelInRect(...[$this->handle, $shouldTruncateLabel, ...$labelRect->toArgs()]);

        return $this;
    }

    public function sizeOfLabel(bool $computeMin): NSSize
    {
        return NSSize::fromArray(ExtNSTabViewItem::sizeOfLabel($this->handle, $computeMin));
    }
}
