<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSText\NSText as ExtNSText;
use Jovian\Bindings\AppKit\Enums\NSTextAlignment;
use Jovian\Bindings\AppKit\Enums\NSWritingDirection;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSText extends NSView
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSText::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function string_(): ?string
    {
        return ExtNSText::string_($this->handle);
    }

    public function setString(string $string): static
    {
        ExtNSText::setString($this->handle, $string);

        return $this;
    }

    public function replaceCharactersInRangeWithString(NSRange $range, string $string): static
    {
        ExtNSText::replaceCharactersInRangeWithString(...[$this->handle, ...$range->toArgs(), $string]);

        return $this;
    }

    public function writeRTFDToFileAtomically(string $path, bool $flag): bool
    {
        return ExtNSText::writeRTFDToFileAtomically($this->handle, $path, $flag);
    }

    public function readRTFDFromFile(string $path): bool
    {
        return ExtNSText::readRTFDFromFile($this->handle, $path);
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSText::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSText::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function isEditable(): bool
    {
        return ExtNSText::isEditable($this->handle);
    }

    public function setEditable(bool $editable): static
    {
        ExtNSText::setEditable($this->handle, $editable);

        return $this;
    }

    public function isSelectable(): bool
    {
        return ExtNSText::isSelectable($this->handle);
    }

    public function setSelectable(bool $selectable): static
    {
        ExtNSText::setSelectable($this->handle, $selectable);

        return $this;
    }

    public function isRichText(): bool
    {
        return ExtNSText::isRichText($this->handle);
    }

    public function setRichText(bool $richText): static
    {
        ExtNSText::setRichText($this->handle, $richText);

        return $this;
    }

    public function importsGraphics(): bool
    {
        return ExtNSText::importsGraphics($this->handle);
    }

    public function setImportsGraphics(bool $importsGraphics): static
    {
        ExtNSText::setImportsGraphics($this->handle, $importsGraphics);

        return $this;
    }

    public function isFieldEditor(): bool
    {
        return ExtNSText::isFieldEditor($this->handle);
    }

    public function setFieldEditor(bool $fieldEditor): static
    {
        ExtNSText::setFieldEditor($this->handle, $fieldEditor);

        return $this;
    }

    public function usesFontPanel(): bool
    {
        return ExtNSText::usesFontPanel($this->handle);
    }

    public function setUsesFontPanel(bool $usesFontPanel): static
    {
        ExtNSText::setUsesFontPanel($this->handle, $usesFontPanel);

        return $this;
    }

    public function drawsBackground(): bool
    {
        return ExtNSText::drawsBackground($this->handle);
    }

    public function setDrawsBackground(bool $drawsBackground): static
    {
        ExtNSText::setDrawsBackground($this->handle, $drawsBackground);

        return $this;
    }

    public function backgroundColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSText::backgroundColor($this->handle));
    }

    public function setBackgroundColor(int $backgroundColor): static
    {
        ExtNSText::setBackgroundColor($this->handle, $backgroundColor);

        return $this;
    }

    public function isRulerVisible(): bool
    {
        return ExtNSText::isRulerVisible($this->handle);
    }

    public function selectedRange(): NSRange
    {
        return NSRange::fromArray(ExtNSText::selectedRange($this->handle));
    }

    public function setSelectedRange(NSRange $selectedRange): static
    {
        ExtNSText::setSelectedRange(...[$this->handle, ...$selectedRange->toArgs()]);

        return $this;
    }

    public function scrollRangeToVisible(NSRange $range): static
    {
        ExtNSText::scrollRangeToVisible(...[$this->handle, ...$range->toArgs()]);

        return $this;
    }

    public function font(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSText::font($this->handle));
    }

    public function setFont(int $font): static
    {
        ExtNSText::setFont($this->handle, $font);

        return $this;
    }

    public function textColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSText::textColor($this->handle));
    }

    public function setTextColor(int $textColor): static
    {
        ExtNSText::setTextColor($this->handle, $textColor);

        return $this;
    }

    public function alignment(): NSTextAlignment|int
    {
        return ExtNSText::alignment($this->handle);
    }

    public function setAlignment(NSTextAlignment|int $alignment): static
    {
        ExtNSText::setAlignment($this->handle, $alignment instanceof \BackedEnum ? $alignment->value : $alignment);

        return $this;
    }

    public function baseWritingDirection(): NSWritingDirection|int
    {
        return ExtNSText::baseWritingDirection($this->handle);
    }

    public function setBaseWritingDirection(NSWritingDirection|int $baseWritingDirection): static
    {
        ExtNSText::setBaseWritingDirection($this->handle, $baseWritingDirection instanceof \BackedEnum ? $baseWritingDirection->value : $baseWritingDirection);

        return $this;
    }

    public function setTextColorRange(int $color, NSRange $range): static
    {
        ExtNSText::setTextColorRange(...[$this->handle, $color, ...$range->toArgs()]);

        return $this;
    }

    public function setFontRange(int $font, NSRange $range): static
    {
        ExtNSText::setFontRange(...[$this->handle, $font, ...$range->toArgs()]);

        return $this;
    }

    public function maxSize(): NSSize
    {
        return NSSize::fromArray(ExtNSText::maxSize($this->handle));
    }

    public function setMaxSize(NSSize $maxSize): static
    {
        ExtNSText::setMaxSize(...[$this->handle, ...$maxSize->toArgs()]);

        return $this;
    }

    public function minSize(): NSSize
    {
        return NSSize::fromArray(ExtNSText::minSize($this->handle));
    }

    public function setMinSize(NSSize $minSize): static
    {
        ExtNSText::setMinSize(...[$this->handle, ...$minSize->toArgs()]);

        return $this;
    }

    public function isHorizontallyResizable(): bool
    {
        return ExtNSText::isHorizontallyResizable($this->handle);
    }

    public function setHorizontallyResizable(bool $horizontallyResizable): static
    {
        ExtNSText::setHorizontallyResizable($this->handle, $horizontallyResizable);

        return $this;
    }

    public function isVerticallyResizable(): bool
    {
        return ExtNSText::isVerticallyResizable($this->handle);
    }

    public function setVerticallyResizable(bool $verticallyResizable): static
    {
        ExtNSText::setVerticallyResizable($this->handle, $verticallyResizable);

        return $this;
    }

    public function sizeToFit(): static
    {
        ExtNSText::sizeToFit($this->handle);

        return $this;
    }

    public function copy_(int $sender): static
    {
        ExtNSText::copy_($this->handle, $sender);

        return $this;
    }

    public function copyFont(int $sender): static
    {
        ExtNSText::copyFont($this->handle, $sender);

        return $this;
    }

    public function copyRuler(int $sender): static
    {
        ExtNSText::copyRuler($this->handle, $sender);

        return $this;
    }

    public function cut(int $sender): static
    {
        ExtNSText::cut($this->handle, $sender);

        return $this;
    }

    public function delete(int $sender): static
    {
        ExtNSText::delete($this->handle, $sender);

        return $this;
    }

    public function paste(int $sender): static
    {
        ExtNSText::paste($this->handle, $sender);

        return $this;
    }

    public function pasteFont(int $sender): static
    {
        ExtNSText::pasteFont($this->handle, $sender);

        return $this;
    }

    public function pasteRuler(int $sender): static
    {
        ExtNSText::pasteRuler($this->handle, $sender);

        return $this;
    }

    public function selectAll(int $sender): static
    {
        ExtNSText::selectAll($this->handle, $sender);

        return $this;
    }

    public function changeFont(int $sender): static
    {
        ExtNSText::changeFont($this->handle, $sender);

        return $this;
    }

    public function alignLeft(int $sender): static
    {
        ExtNSText::alignLeft($this->handle, $sender);

        return $this;
    }

    public function alignRight(int $sender): static
    {
        ExtNSText::alignRight($this->handle, $sender);

        return $this;
    }

    public function alignCenter(int $sender): static
    {
        ExtNSText::alignCenter($this->handle, $sender);

        return $this;
    }

    public function subscript(int $sender): static
    {
        ExtNSText::subscript($this->handle, $sender);

        return $this;
    }

    public function superscript(int $sender): static
    {
        ExtNSText::superscript($this->handle, $sender);

        return $this;
    }

    public function underline(int $sender): static
    {
        ExtNSText::underline($this->handle, $sender);

        return $this;
    }

    public function unscript(int $sender): static
    {
        ExtNSText::unscript($this->handle, $sender);

        return $this;
    }

    public function showGuessPanel(int $sender): static
    {
        ExtNSText::showGuessPanel($this->handle, $sender);

        return $this;
    }

    public function checkSpelling(int $sender): static
    {
        ExtNSText::checkSpelling($this->handle, $sender);

        return $this;
    }

    public function toggleRuler(int $sender): static
    {
        ExtNSText::toggleRuler($this->handle, $sender);

        return $this;
    }
}
