<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSTextStorage\NSTextStorage as ExtNSTextStorage;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSTextStorage extends NSAttributedString
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextStorage::init());
    }

    public static function initWithString(string $str): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextStorage::initWithString($str));
    }

    public function layoutManagers(): array
    {
        return ExtNSTextStorage::layoutManagers($this->handle);
    }

    public function addLayoutManager(int $aLayoutManager): static
    {
        ExtNSTextStorage::addLayoutManager($this->handle, $aLayoutManager);

        return $this;
    }

    public function removeLayoutManager(int $aLayoutManager): static
    {
        ExtNSTextStorage::removeLayoutManager($this->handle, $aLayoutManager);

        return $this;
    }

    public function editedMask(): int
    {
        return ExtNSTextStorage::editedMask($this->handle);
    }

    public function editedRange(): NSRange
    {
        return NSRange::fromArray(ExtNSTextStorage::editedRange($this->handle));
    }

    public function changeInLength(): int
    {
        return ExtNSTextStorage::changeInLength($this->handle);
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextStorage::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSTextStorage::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function editedRangeChangeInLength(int $editedMask, NSRange $editedRange, int $delta): static
    {
        ExtNSTextStorage::editedRangeChangeInLength(...[$this->handle, $editedMask, ...$editedRange->toArgs(), $delta]);

        return $this;
    }

    public function processEditing(): static
    {
        ExtNSTextStorage::processEditing($this->handle);

        return $this;
    }

    public function fixesAttributesLazily(): bool
    {
        return ExtNSTextStorage::fixesAttributesLazily($this->handle);
    }

    public function invalidateAttributesInRange(NSRange $range): static
    {
        ExtNSTextStorage::invalidateAttributesInRange(...[$this->handle, ...$range->toArgs()]);

        return $this;
    }

    public function ensureAttributesAreFixedInRange(NSRange $range): static
    {
        ExtNSTextStorage::ensureAttributesAreFixedInRange(...[$this->handle, ...$range->toArgs()]);

        return $this;
    }

    public function textStorageObserver(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextStorage::textStorageObserver($this->handle));
    }

    public function setTextStorageObserver(int $textStorageObserver): static
    {
        ExtNSTextStorage::setTextStorageObserver($this->handle, $textStorageObserver);

        return $this;
    }
}
