<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSTextView\NSTextView as ExtNSTextView;
use Jovian\Bindings\AppKit\Enums\NSSelectionAffinity;
use Jovian\Bindings\AppKit\Enums\NSSelectionGranularity;
use Jovian\Bindings\AppKit\Enums\NSTextAlignment;
use Jovian\Bindings\AppKit\Enums\NSTextInputTraitType;
use Jovian\Bindings\AppKit\Enums\NSTextLayoutOrientation;
use Jovian\Bindings\AppKit\Enums\NSWritingDirection;
use Jovian\Bindings\AppKit\Enums\NSWritingToolsBehavior;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSTextView extends NSText
{
    public static function initWithFrameTextContainer(NSRect $frameRect, int $container): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::initWithFrameTextContainer(...[...$frameRect->toArgs(), $container]));
    }

    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public static function initUsingTextLayoutManager(bool $usingTextLayoutManager): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::initUsingTextLayoutManager($usingTextLayoutManager));
    }

    public static function textViewUsingTextLayoutManager(bool $usingTextLayoutManager): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::textViewUsingTextLayoutManager($usingTextLayoutManager));
    }

    public function textContainer(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::textContainer($this->handle));
    }

    public function setTextContainer(int $textContainer): static
    {
        ExtNSTextView::setTextContainer($this->handle, $textContainer);

        return $this;
    }

    public function replaceTextContainer(int $newContainer): static
    {
        ExtNSTextView::replaceTextContainer($this->handle, $newContainer);

        return $this;
    }

    public function textContainerInset(): NSSize
    {
        return NSSize::fromArray(ExtNSTextView::textContainerInset($this->handle));
    }

    public function setTextContainerInset(NSSize $textContainerInset): static
    {
        ExtNSTextView::setTextContainerInset(...[$this->handle, ...$textContainerInset->toArgs()]);

        return $this;
    }

    public function textContainerOrigin(): NSPoint
    {
        return NSPoint::fromArray(ExtNSTextView::textContainerOrigin($this->handle));
    }

    public function invalidateTextContainerOrigin(): static
    {
        ExtNSTextView::invalidateTextContainerOrigin($this->handle);

        return $this;
    }

    public function layoutManager(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::layoutManager($this->handle));
    }

    public function textStorage(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::textStorage($this->handle));
    }

    public function textLayoutManager(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::textLayoutManager($this->handle));
    }

    public function textContentStorage(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::textContentStorage($this->handle));
    }

    public function setConstrainedFrameSize(NSSize $desiredSize): static
    {
        ExtNSTextView::setConstrainedFrameSize(...[$this->handle, ...$desiredSize->toArgs()]);

        return $this;
    }

    public function setAlignmentRange(NSTextAlignment|int $alignment, NSRange $range): static
    {
        ExtNSTextView::setAlignmentRange(...[$this->handle, $alignment instanceof \BackedEnum ? $alignment->value : $alignment, ...$range->toArgs()]);

        return $this;
    }

    public function setBaseWritingDirectionRange(NSWritingDirection|int $writingDirection, NSRange $range): static
    {
        ExtNSTextView::setBaseWritingDirectionRange(...[$this->handle, $writingDirection instanceof \BackedEnum ? $writingDirection->value : $writingDirection, ...$range->toArgs()]);

        return $this;
    }

    public function turnOffKerning(int $sender): static
    {
        ExtNSTextView::turnOffKerning($this->handle, $sender);

        return $this;
    }

    public function tightenKerning(int $sender): static
    {
        ExtNSTextView::tightenKerning($this->handle, $sender);

        return $this;
    }

    public function loosenKerning(int $sender): static
    {
        ExtNSTextView::loosenKerning($this->handle, $sender);

        return $this;
    }

    public function useStandardKerning(int $sender): static
    {
        ExtNSTextView::useStandardKerning($this->handle, $sender);

        return $this;
    }

    public function turnOffLigatures(int $sender): static
    {
        ExtNSTextView::turnOffLigatures($this->handle, $sender);

        return $this;
    }

    public function useStandardLigatures(int $sender): static
    {
        ExtNSTextView::useStandardLigatures($this->handle, $sender);

        return $this;
    }

    public function useAllLigatures(int $sender): static
    {
        ExtNSTextView::useAllLigatures($this->handle, $sender);

        return $this;
    }

    public function raiseBaseline(int $sender): static
    {
        ExtNSTextView::raiseBaseline($this->handle, $sender);

        return $this;
    }

    public function lowerBaseline(int $sender): static
    {
        ExtNSTextView::lowerBaseline($this->handle, $sender);

        return $this;
    }

    public function outline(int $sender): static
    {
        ExtNSTextView::outline($this->handle, $sender);

        return $this;
    }

    public function performFindPanelAction(int $sender): static
    {
        ExtNSTextView::performFindPanelAction($this->handle, $sender);

        return $this;
    }

    public function alignJustified(int $sender): static
    {
        ExtNSTextView::alignJustified($this->handle, $sender);

        return $this;
    }

    public function changeColor(int $sender): static
    {
        ExtNSTextView::changeColor($this->handle, $sender);

        return $this;
    }

    public function changeAttributes(int $sender): static
    {
        ExtNSTextView::changeAttributes($this->handle, $sender);

        return $this;
    }

    public function changeDocumentBackgroundColor(int $sender): static
    {
        ExtNSTextView::changeDocumentBackgroundColor($this->handle, $sender);

        return $this;
    }

    public function orderFrontSpacingPanel(int $sender): static
    {
        ExtNSTextView::orderFrontSpacingPanel($this->handle, $sender);

        return $this;
    }

    public function orderFrontLinkPanel(int $sender): static
    {
        ExtNSTextView::orderFrontLinkPanel($this->handle, $sender);

        return $this;
    }

    public function orderFrontListPanel(int $sender): static
    {
        ExtNSTextView::orderFrontListPanel($this->handle, $sender);

        return $this;
    }

    public function orderFrontTablePanel(int $sender): static
    {
        ExtNSTextView::orderFrontTablePanel($this->handle, $sender);

        return $this;
    }

    public function rulerViewDidMoveMarker(int $ruler, int $marker): static
    {
        ExtNSTextView::rulerViewDidMoveMarker($this->handle, $ruler, $marker);

        return $this;
    }

    public function rulerViewDidRemoveMarker(int $ruler, int $marker): static
    {
        ExtNSTextView::rulerViewDidRemoveMarker($this->handle, $ruler, $marker);

        return $this;
    }

    public function rulerViewDidAddMarker(int $ruler, int $marker): static
    {
        ExtNSTextView::rulerViewDidAddMarker($this->handle, $ruler, $marker);

        return $this;
    }

    public function rulerViewShouldMoveMarker(int $ruler, int $marker): bool
    {
        return ExtNSTextView::rulerViewShouldMoveMarker($this->handle, $ruler, $marker);
    }

    public function rulerViewShouldAddMarker(int $ruler, int $marker): bool
    {
        return ExtNSTextView::rulerViewShouldAddMarker($this->handle, $ruler, $marker);
    }

    public function rulerViewWillMoveMarkerToLocation(int $ruler, int $marker, float $location): float
    {
        return ExtNSTextView::rulerViewWillMoveMarkerToLocation($this->handle, $ruler, $marker, $location);
    }

    public function rulerViewShouldRemoveMarker(int $ruler, int $marker): bool
    {
        return ExtNSTextView::rulerViewShouldRemoveMarker($this->handle, $ruler, $marker);
    }

    public function rulerViewWillAddMarkerAtLocation(int $ruler, int $marker, float $location): float
    {
        return ExtNSTextView::rulerViewWillAddMarkerAtLocation($this->handle, $ruler, $marker, $location);
    }

    public function rulerViewHandleMouseDown(int $ruler, int $event): static
    {
        ExtNSTextView::rulerViewHandleMouseDown($this->handle, $ruler, $event);

        return $this;
    }

    public function setNeedsDisplayInRectAvoidAdditionalLayout(NSRect $rect, bool $flag): static
    {
        ExtNSTextView::setNeedsDisplayInRectAvoidAdditionalLayout(...[$this->handle, ...$rect->toArgs(), $flag]);

        return $this;
    }

    public function shouldDrawInsertionPoint(): bool
    {
        return ExtNSTextView::shouldDrawInsertionPoint($this->handle);
    }

    public function drawInsertionPointInRectColorTurnedOn(NSRect $rect, int $color, bool $flag): static
    {
        ExtNSTextView::drawInsertionPointInRectColorTurnedOn(...[$this->handle, ...$rect->toArgs(), $color, $flag]);

        return $this;
    }

    public function drawViewBackgroundInRect(NSRect $rect): static
    {
        ExtNSTextView::drawViewBackgroundInRect(...[$this->handle, ...$rect->toArgs()]);

        return $this;
    }

    public function updateRuler(): static
    {
        ExtNSTextView::updateRuler($this->handle);

        return $this;
    }

    public function updateFontPanel(): static
    {
        ExtNSTextView::updateFontPanel($this->handle);

        return $this;
    }

    public function updateDragTypeRegistration(): static
    {
        ExtNSTextView::updateDragTypeRegistration($this->handle);

        return $this;
    }

    public function selectionRangeForProposedRangeGranularity(NSRange $proposedCharRange, NSSelectionGranularity|int $granularity): NSRange
    {
        return NSRange::fromArray(ExtNSTextView::selectionRangeForProposedRangeGranularity(...[$this->handle, ...$proposedCharRange->toArgs(), $granularity instanceof \BackedEnum ? $granularity->value : $granularity]));
    }

    public function clickedOnLinkAtIndex(int $link, int $charIndex): static
    {
        ExtNSTextView::clickedOnLinkAtIndex($this->handle, $link, $charIndex);

        return $this;
    }

    public function startSpeaking(int $sender): static
    {
        ExtNSTextView::startSpeaking($this->handle, $sender);

        return $this;
    }

    public function stopSpeaking(int $sender): static
    {
        ExtNSTextView::stopSpeaking($this->handle, $sender);

        return $this;
    }

    public function setLayoutOrientation(NSTextLayoutOrientation|int $orientation): static
    {
        ExtNSTextView::setLayoutOrientation($this->handle, $orientation instanceof \BackedEnum ? $orientation->value : $orientation);

        return $this;
    }

    public function changeLayoutOrientation(int $sender): static
    {
        ExtNSTextView::changeLayoutOrientation($this->handle, $sender);

        return $this;
    }

    public function characterIndexForInsertionAtPoint(NSPoint $point): int
    {
        return ExtNSTextView::characterIndexForInsertionAtPoint(...[$this->handle, ...$point->toArgs()]);
    }

    public static function stronglyReferencesTextStorage(): bool
    {
        return ExtNSTextView::stronglyReferencesTextStorage();
    }

    public function usesAdaptiveColorMappingForDarkAppearance(): bool
    {
        return ExtNSTextView::usesAdaptiveColorMappingForDarkAppearance($this->handle);
    }

    public function setUsesAdaptiveColorMappingForDarkAppearance(bool $usesAdaptiveColorMappingForDarkAppearance): static
    {
        ExtNSTextView::setUsesAdaptiveColorMappingForDarkAppearance($this->handle, $usesAdaptiveColorMappingForDarkAppearance);

        return $this;
    }

    public function complete(int $sender): static
    {
        ExtNSTextView::complete($this->handle, $sender);

        return $this;
    }

    public function rangeForUserCompletion(): NSRange
    {
        return NSRange::fromArray(ExtNSTextView::rangeForUserCompletion($this->handle));
    }

    public function completionsForPartialWordRangeIndexOfSelectedItem(NSRange $charRange): array
    {
        return ExtNSTextView::completionsForPartialWordRangeIndexOfSelectedItem(...[$this->handle, ...$charRange->toArgs()]);
    }

    public function insertCompletionForPartialWordRangeMovementIsFinal(string $word, NSRange $charRange, int $movement, bool $flag): static
    {
        ExtNSTextView::insertCompletionForPartialWordRangeMovementIsFinal(...[$this->handle, $word, ...$charRange->toArgs(), $movement, $flag]);

        return $this;
    }

    public function writablePasteboardTypes(): array
    {
        return ExtNSTextView::writablePasteboardTypes($this->handle);
    }

    public function writeSelectionToPasteboardType(int $pboard, string $type): bool
    {
        return ExtNSTextView::writeSelectionToPasteboardType($this->handle, $pboard, $type);
    }

    public function writeSelectionToPasteboardTypes(int $pboard, array $types): bool
    {
        return ExtNSTextView::writeSelectionToPasteboardTypes($this->handle, $pboard, $types);
    }

    public function readablePasteboardTypes(): array
    {
        return ExtNSTextView::readablePasteboardTypes($this->handle);
    }

    public function preferredPasteboardTypeFromArrayRestrictedToTypesFromArray(array $availableTypes, array $allowedTypes): mixed
    {
        return ExtNSTextView::preferredPasteboardTypeFromArrayRestrictedToTypesFromArray($this->handle, $availableTypes, $allowedTypes);
    }

    public function readSelectionFromPasteboardType(int $pboard, string $type): bool
    {
        return ExtNSTextView::readSelectionFromPasteboardType($this->handle, $pboard, $type);
    }

    public function readSelectionFromPasteboard(int $pboard): bool
    {
        return ExtNSTextView::readSelectionFromPasteboard($this->handle, $pboard);
    }

    public static function registerForServices(): void
    {
        ExtNSTextView::registerForServices();
    }

    public function validRequestorForSendTypeReturnType(string $sendType, string $returnType): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::validRequestorForSendTypeReturnType($this->handle, $sendType, $returnType));
    }

    public function pasteAsPlainText(int $sender): static
    {
        ExtNSTextView::pasteAsPlainText($this->handle, $sender);

        return $this;
    }

    public function pasteAsRichText(int $sender): static
    {
        ExtNSTextView::pasteAsRichText($this->handle, $sender);

        return $this;
    }

    public function dragSelectionWithEventOffsetSlideBack(int $event, NSSize $mouseOffset, bool $slideBack): bool
    {
        return ExtNSTextView::dragSelectionWithEventOffsetSlideBack(...[$this->handle, $event, ...$mouseOffset->toArgs(), $slideBack]);
    }

    public function dragImageForSelectionWithEventOrigin(int $event): array
    {
        return ExtNSTextView::dragImageForSelectionWithEventOrigin($this->handle, $event);
    }

    public function acceptableDragTypes(): array
    {
        return ExtNSTextView::acceptableDragTypes($this->handle);
    }

    public function dragOperationForDraggingInfoType(int $dragInfo, string $type): int
    {
        return ExtNSTextView::dragOperationForDraggingInfoType($this->handle, $dragInfo, $type);
    }

    public function cleanUpAfterDragOperation(): static
    {
        ExtNSTextView::cleanUpAfterDragOperation($this->handle);

        return $this;
    }

    public function selectedRanges(): array
    {
        return ExtNSTextView::selectedRanges($this->handle);
    }

    public function setSelectedRanges(array $selectedRanges): static
    {
        ExtNSTextView::setSelectedRanges($this->handle, $selectedRanges);

        return $this;
    }

    public function setSelectedRangesAffinityStillSelecting(array $ranges, NSSelectionAffinity|int $affinity, bool $stillSelectingFlag): static
    {
        ExtNSTextView::setSelectedRangesAffinityStillSelecting($this->handle, $ranges, $affinity instanceof \BackedEnum ? $affinity->value : $affinity, $stillSelectingFlag);

        return $this;
    }

    public function setSelectedRangeAffinityStillSelecting(NSRange $charRange, NSSelectionAffinity|int $affinity, bool $stillSelectingFlag): static
    {
        ExtNSTextView::setSelectedRangeAffinityStillSelecting(...[$this->handle, ...$charRange->toArgs(), $affinity instanceof \BackedEnum ? $affinity->value : $affinity, $stillSelectingFlag]);

        return $this;
    }

    public function selectionAffinity(): NSSelectionAffinity|int
    {
        return ExtNSTextView::selectionAffinity($this->handle);
    }

    public function selectionGranularity(): NSSelectionGranularity|int
    {
        return ExtNSTextView::selectionGranularity($this->handle);
    }

    public function setSelectionGranularity(NSSelectionGranularity|int $selectionGranularity): static
    {
        ExtNSTextView::setSelectionGranularity($this->handle, $selectionGranularity instanceof \BackedEnum ? $selectionGranularity->value : $selectionGranularity);

        return $this;
    }

    public function selectedTextAttributes(): int
    {
        return ExtNSTextView::selectedTextAttributes($this->handle);
    }

    public function setSelectedTextAttributes(array $selectedTextAttributes): static
    {
        ExtNSTextView::setSelectedTextAttributes($this->handle, $selectedTextAttributes);

        return $this;
    }

    public function insertionPointColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::insertionPointColor($this->handle));
    }

    public function setInsertionPointColor(int $insertionPointColor): static
    {
        ExtNSTextView::setInsertionPointColor($this->handle, $insertionPointColor);

        return $this;
    }

    public function updateInsertionPointStateAndRestartTimer(bool $restartFlag): static
    {
        ExtNSTextView::updateInsertionPointStateAndRestartTimer($this->handle, $restartFlag);

        return $this;
    }

    public function markedTextAttributes(): int
    {
        return ExtNSTextView::markedTextAttributes($this->handle);
    }

    public function setMarkedTextAttributes(array $markedTextAttributes): static
    {
        ExtNSTextView::setMarkedTextAttributes($this->handle, $markedTextAttributes);

        return $this;
    }

    public function linkTextAttributes(): int
    {
        return ExtNSTextView::linkTextAttributes($this->handle);
    }

    public function setLinkTextAttributes(array $linkTextAttributes): static
    {
        ExtNSTextView::setLinkTextAttributes($this->handle, $linkTextAttributes);

        return $this;
    }

    public function displaysLinkToolTips(): bool
    {
        return ExtNSTextView::displaysLinkToolTips($this->handle);
    }

    public function setDisplaysLinkToolTips(bool $displaysLinkToolTips): static
    {
        ExtNSTextView::setDisplaysLinkToolTips($this->handle, $displaysLinkToolTips);

        return $this;
    }

    public function acceptsGlyphInfo(): bool
    {
        return ExtNSTextView::acceptsGlyphInfo($this->handle);
    }

    public function setAcceptsGlyphInfo(bool $acceptsGlyphInfo): static
    {
        ExtNSTextView::setAcceptsGlyphInfo($this->handle, $acceptsGlyphInfo);

        return $this;
    }

    public function usesRuler(): bool
    {
        return ExtNSTextView::usesRuler($this->handle);
    }

    public function setUsesRuler(bool $usesRuler): static
    {
        ExtNSTextView::setUsesRuler($this->handle, $usesRuler);

        return $this;
    }

    public function usesInspectorBar(): bool
    {
        return ExtNSTextView::usesInspectorBar($this->handle);
    }

    public function setUsesInspectorBar(bool $usesInspectorBar): static
    {
        ExtNSTextView::setUsesInspectorBar($this->handle, $usesInspectorBar);

        return $this;
    }

    public function isContinuousSpellCheckingEnabled(): bool
    {
        return ExtNSTextView::isContinuousSpellCheckingEnabled($this->handle);
    }

    public function setContinuousSpellCheckingEnabled(bool $continuousSpellCheckingEnabled): static
    {
        ExtNSTextView::setContinuousSpellCheckingEnabled($this->handle, $continuousSpellCheckingEnabled);

        return $this;
    }

    public function toggleContinuousSpellChecking(int $sender): static
    {
        ExtNSTextView::toggleContinuousSpellChecking($this->handle, $sender);

        return $this;
    }

    public function spellCheckerDocumentTag(): int
    {
        return ExtNSTextView::spellCheckerDocumentTag($this->handle);
    }

    public function isGrammarCheckingEnabled(): bool
    {
        return ExtNSTextView::isGrammarCheckingEnabled($this->handle);
    }

    public function setGrammarCheckingEnabled(bool $grammarCheckingEnabled): static
    {
        ExtNSTextView::setGrammarCheckingEnabled($this->handle, $grammarCheckingEnabled);

        return $this;
    }

    public function toggleGrammarChecking(int $sender): static
    {
        ExtNSTextView::toggleGrammarChecking($this->handle, $sender);

        return $this;
    }

    public function setSpellingStateRange(int $value, NSRange $charRange): static
    {
        ExtNSTextView::setSpellingStateRange(...[$this->handle, $value, ...$charRange->toArgs()]);

        return $this;
    }

    public function typingAttributes(): int
    {
        return ExtNSTextView::typingAttributes($this->handle);
    }

    public function setTypingAttributes(array $typingAttributes): static
    {
        ExtNSTextView::setTypingAttributes($this->handle, $typingAttributes);

        return $this;
    }

    public function shouldChangeTextInRangesReplacementStrings(array $affectedRanges, array $replacementStrings): bool
    {
        return ExtNSTextView::shouldChangeTextInRangesReplacementStrings($this->handle, $affectedRanges, $replacementStrings);
    }

    public function rangesForUserTextChange(): array
    {
        return ExtNSTextView::rangesForUserTextChange($this->handle);
    }

    public function rangesForUserCharacterAttributeChange(): array
    {
        return ExtNSTextView::rangesForUserCharacterAttributeChange($this->handle);
    }

    public function rangesForUserParagraphAttributeChange(): array
    {
        return ExtNSTextView::rangesForUserParagraphAttributeChange($this->handle);
    }

    public function shouldChangeTextInRangeReplacementString(NSRange $affectedCharRange, string $replacementString): bool
    {
        return ExtNSTextView::shouldChangeTextInRangeReplacementString(...[$this->handle, ...$affectedCharRange->toArgs(), $replacementString]);
    }

    public function didChangeText(): static
    {
        ExtNSTextView::didChangeText($this->handle);

        return $this;
    }

    public function rangeForUserTextChange(): NSRange
    {
        return NSRange::fromArray(ExtNSTextView::rangeForUserTextChange($this->handle));
    }

    public function rangeForUserCharacterAttributeChange(): NSRange
    {
        return NSRange::fromArray(ExtNSTextView::rangeForUserCharacterAttributeChange($this->handle));
    }

    public function rangeForUserParagraphAttributeChange(): NSRange
    {
        return NSRange::fromArray(ExtNSTextView::rangeForUserParagraphAttributeChange($this->handle));
    }

    public function allowsDocumentBackgroundColorChange(): bool
    {
        return ExtNSTextView::allowsDocumentBackgroundColorChange($this->handle);
    }

    public function setAllowsDocumentBackgroundColorChange(bool $allowsDocumentBackgroundColorChange): static
    {
        ExtNSTextView::setAllowsDocumentBackgroundColorChange($this->handle, $allowsDocumentBackgroundColorChange);

        return $this;
    }

    public function defaultParagraphStyle(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::defaultParagraphStyle($this->handle));
    }

    public function setDefaultParagraphStyle(int $defaultParagraphStyle): static
    {
        ExtNSTextView::setDefaultParagraphStyle($this->handle, $defaultParagraphStyle);

        return $this;
    }

    public function allowsUndo(): bool
    {
        return ExtNSTextView::allowsUndo($this->handle);
    }

    public function setAllowsUndo(bool $allowsUndo): static
    {
        ExtNSTextView::setAllowsUndo($this->handle, $allowsUndo);

        return $this;
    }

    public function breakUndoCoalescing(): static
    {
        ExtNSTextView::breakUndoCoalescing($this->handle);

        return $this;
    }

    public function isCoalescingUndo(): bool
    {
        return ExtNSTextView::isCoalescingUndo($this->handle);
    }

    public function allowsImageEditing(): bool
    {
        return ExtNSTextView::allowsImageEditing($this->handle);
    }

    public function setAllowsImageEditing(bool $allowsImageEditing): static
    {
        ExtNSTextView::setAllowsImageEditing($this->handle, $allowsImageEditing);

        return $this;
    }

    public function showFindIndicatorForRange(NSRange $charRange): static
    {
        ExtNSTextView::showFindIndicatorForRange(...[$this->handle, ...$charRange->toArgs()]);

        return $this;
    }

    public function usesRolloverButtonForSelection(): bool
    {
        return ExtNSTextView::usesRolloverButtonForSelection($this->handle);
    }

    public function setUsesRolloverButtonForSelection(bool $usesRolloverButtonForSelection): static
    {
        ExtNSTextView::setUsesRolloverButtonForSelection($this->handle, $usesRolloverButtonForSelection);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSTextView::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function isEditable(): bool
    {
        return ExtNSTextView::isEditable($this->handle);
    }

    public function setEditable(bool $editable): static
    {
        ExtNSTextView::setEditable($this->handle, $editable);

        return $this;
    }

    public function isSelectable(): bool
    {
        return ExtNSTextView::isSelectable($this->handle);
    }

    public function setSelectable(bool $selectable): static
    {
        ExtNSTextView::setSelectable($this->handle, $selectable);

        return $this;
    }

    public function isRichText(): bool
    {
        return ExtNSTextView::isRichText($this->handle);
    }

    public function setRichText(bool $richText): static
    {
        ExtNSTextView::setRichText($this->handle, $richText);

        return $this;
    }

    public function importsGraphics(): bool
    {
        return ExtNSTextView::importsGraphics($this->handle);
    }

    public function setImportsGraphics(bool $importsGraphics): static
    {
        ExtNSTextView::setImportsGraphics($this->handle, $importsGraphics);

        return $this;
    }

    public function drawsBackground(): bool
    {
        return ExtNSTextView::drawsBackground($this->handle);
    }

    public function setDrawsBackground(bool $drawsBackground): static
    {
        ExtNSTextView::setDrawsBackground($this->handle, $drawsBackground);

        return $this;
    }

    public function backgroundColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::backgroundColor($this->handle));
    }

    public function setBackgroundColor(int $backgroundColor): static
    {
        ExtNSTextView::setBackgroundColor($this->handle, $backgroundColor);

        return $this;
    }

    public function isFieldEditor(): bool
    {
        return ExtNSTextView::isFieldEditor($this->handle);
    }

    public function setFieldEditor(bool $fieldEditor): static
    {
        ExtNSTextView::setFieldEditor($this->handle, $fieldEditor);

        return $this;
    }

    public function usesFontPanel(): bool
    {
        return ExtNSTextView::usesFontPanel($this->handle);
    }

    public function setUsesFontPanel(bool $usesFontPanel): static
    {
        ExtNSTextView::setUsesFontPanel($this->handle, $usesFontPanel);

        return $this;
    }

    public function isRulerVisible(): bool
    {
        return ExtNSTextView::isRulerVisible($this->handle);
    }

    public function setRulerVisible(bool $rulerVisible): static
    {
        ExtNSTextView::setRulerVisible($this->handle, $rulerVisible);

        return $this;
    }

    public function setSelectedRange(NSRange $charRange): static
    {
        ExtNSTextView::setSelectedRange(...[$this->handle, ...$charRange->toArgs()]);

        return $this;
    }

    public function allowedInputSourceLocales(): array
    {
        return ExtNSTextView::allowedInputSourceLocales($this->handle);
    }

    public function setAllowedInputSourceLocales(array $allowedInputSourceLocales): static
    {
        ExtNSTextView::setAllowedInputSourceLocales($this->handle, $allowedInputSourceLocales);

        return $this;
    }

    public function isWritingToolsActive(): bool
    {
        return ExtNSTextView::isWritingToolsActive($this->handle);
    }

    public function writingToolsBehavior(): NSWritingToolsBehavior|int
    {
        return ExtNSTextView::writingToolsBehavior($this->handle);
    }

    public function setWritingToolsBehavior(NSWritingToolsBehavior|int $writingToolsBehavior): static
    {
        ExtNSTextView::setWritingToolsBehavior($this->handle, $writingToolsBehavior instanceof \BackedEnum ? $writingToolsBehavior->value : $writingToolsBehavior);

        return $this;
    }

    public function allowedWritingToolsResultOptions(): int
    {
        return ExtNSTextView::allowedWritingToolsResultOptions($this->handle);
    }

    public function setAllowedWritingToolsResultOptions(int $allowedWritingToolsResultOptions): static
    {
        ExtNSTextView::setAllowedWritingToolsResultOptions($this->handle, $allowedWritingToolsResultOptions);

        return $this;
    }

    public function smartInsertDeleteEnabled(): bool
    {
        return ExtNSTextView::smartInsertDeleteEnabled($this->handle);
    }

    public function setSmartInsertDeleteEnabled(bool $smartInsertDeleteEnabled): static
    {
        ExtNSTextView::setSmartInsertDeleteEnabled($this->handle, $smartInsertDeleteEnabled);

        return $this;
    }

    public function smartDeleteRangeForProposedRange(NSRange $proposedCharRange): NSRange
    {
        return NSRange::fromArray(ExtNSTextView::smartDeleteRangeForProposedRange(...[$this->handle, ...$proposedCharRange->toArgs()]));
    }

    public function toggleSmartInsertDelete(int $sender): static
    {
        ExtNSTextView::toggleSmartInsertDelete($this->handle, $sender);

        return $this;
    }

    public function smartInsertForStringReplacingRangeBeforeStringAfterString(string $pasteString, NSRange $charRangeToReplace): array
    {
        return ExtNSTextView::smartInsertForStringReplacingRangeBeforeStringAfterString(...[$this->handle, $pasteString, ...$charRangeToReplace->toArgs()]);
    }

    public function smartInsertBeforeStringForStringReplacingRange(string $pasteString, NSRange $charRangeToReplace): mixed
    {
        return ExtNSTextView::smartInsertBeforeStringForStringReplacingRange(...[$this->handle, $pasteString, ...$charRangeToReplace->toArgs()]);
    }

    public function smartInsertAfterStringForStringReplacingRange(string $pasteString, NSRange $charRangeToReplace): mixed
    {
        return ExtNSTextView::smartInsertAfterStringForStringReplacingRange(...[$this->handle, $pasteString, ...$charRangeToReplace->toArgs()]);
    }

    public function isAutomaticQuoteSubstitutionEnabled(): bool
    {
        return ExtNSTextView::isAutomaticQuoteSubstitutionEnabled($this->handle);
    }

    public function setAutomaticQuoteSubstitutionEnabled(bool $automaticQuoteSubstitutionEnabled): static
    {
        ExtNSTextView::setAutomaticQuoteSubstitutionEnabled($this->handle, $automaticQuoteSubstitutionEnabled);

        return $this;
    }

    public function toggleAutomaticQuoteSubstitution(int $sender): static
    {
        ExtNSTextView::toggleAutomaticQuoteSubstitution($this->handle, $sender);

        return $this;
    }

    public function isAutomaticLinkDetectionEnabled(): bool
    {
        return ExtNSTextView::isAutomaticLinkDetectionEnabled($this->handle);
    }

    public function setAutomaticLinkDetectionEnabled(bool $automaticLinkDetectionEnabled): static
    {
        ExtNSTextView::setAutomaticLinkDetectionEnabled($this->handle, $automaticLinkDetectionEnabled);

        return $this;
    }

    public function toggleAutomaticLinkDetection(int $sender): static
    {
        ExtNSTextView::toggleAutomaticLinkDetection($this->handle, $sender);

        return $this;
    }

    public function isAutomaticDataDetectionEnabled(): bool
    {
        return ExtNSTextView::isAutomaticDataDetectionEnabled($this->handle);
    }

    public function setAutomaticDataDetectionEnabled(bool $automaticDataDetectionEnabled): static
    {
        ExtNSTextView::setAutomaticDataDetectionEnabled($this->handle, $automaticDataDetectionEnabled);

        return $this;
    }

    public function toggleAutomaticDataDetection(int $sender): static
    {
        ExtNSTextView::toggleAutomaticDataDetection($this->handle, $sender);

        return $this;
    }

    public function isAutomaticDashSubstitutionEnabled(): bool
    {
        return ExtNSTextView::isAutomaticDashSubstitutionEnabled($this->handle);
    }

    public function setAutomaticDashSubstitutionEnabled(bool $automaticDashSubstitutionEnabled): static
    {
        ExtNSTextView::setAutomaticDashSubstitutionEnabled($this->handle, $automaticDashSubstitutionEnabled);

        return $this;
    }

    public function toggleAutomaticDashSubstitution(int $sender): static
    {
        ExtNSTextView::toggleAutomaticDashSubstitution($this->handle, $sender);

        return $this;
    }

    public function isAutomaticTextReplacementEnabled(): bool
    {
        return ExtNSTextView::isAutomaticTextReplacementEnabled($this->handle);
    }

    public function setAutomaticTextReplacementEnabled(bool $automaticTextReplacementEnabled): static
    {
        ExtNSTextView::setAutomaticTextReplacementEnabled($this->handle, $automaticTextReplacementEnabled);

        return $this;
    }

    public function toggleAutomaticTextReplacement(int $sender): static
    {
        ExtNSTextView::toggleAutomaticTextReplacement($this->handle, $sender);

        return $this;
    }

    public function isAutomaticSpellingCorrectionEnabled(): bool
    {
        return ExtNSTextView::isAutomaticSpellingCorrectionEnabled($this->handle);
    }

    public function setAutomaticSpellingCorrectionEnabled(bool $automaticSpellingCorrectionEnabled): static
    {
        ExtNSTextView::setAutomaticSpellingCorrectionEnabled($this->handle, $automaticSpellingCorrectionEnabled);

        return $this;
    }

    public function toggleAutomaticSpellingCorrection(int $sender): static
    {
        ExtNSTextView::toggleAutomaticSpellingCorrection($this->handle, $sender);

        return $this;
    }

    public function enabledTextCheckingTypes(): int
    {
        return ExtNSTextView::enabledTextCheckingTypes($this->handle);
    }

    public function setEnabledTextCheckingTypes(int $enabledTextCheckingTypes): static
    {
        ExtNSTextView::setEnabledTextCheckingTypes($this->handle, $enabledTextCheckingTypes);

        return $this;
    }

    public function checkTextInRangeTypesOptions(NSRange $range, int $checkingTypes, array $options): static
    {
        ExtNSTextView::checkTextInRangeTypesOptions(...[$this->handle, ...$range->toArgs(), $checkingTypes, $options]);

        return $this;
    }

    public function handleTextCheckingResultsForRangeTypesOptionsOrthographyWordCount(array $results, NSRange $range, int $checkingTypes, array $options, int $orthography, int $wordCount): static
    {
        ExtNSTextView::handleTextCheckingResultsForRangeTypesOptionsOrthographyWordCount(...[$this->handle, $results, ...$range->toArgs(), $checkingTypes, $options, $orthography, $wordCount]);

        return $this;
    }

    public function orderFrontSubstitutionsPanel(int $sender): static
    {
        ExtNSTextView::orderFrontSubstitutionsPanel($this->handle, $sender);

        return $this;
    }

    public function checkTextInSelection(int $sender): static
    {
        ExtNSTextView::checkTextInSelection($this->handle, $sender);

        return $this;
    }

    public function checkTextInDocument(int $sender): static
    {
        ExtNSTextView::checkTextInDocument($this->handle, $sender);

        return $this;
    }

    public function usesFindPanel(): bool
    {
        return ExtNSTextView::usesFindPanel($this->handle);
    }

    public function setUsesFindPanel(bool $usesFindPanel): static
    {
        ExtNSTextView::setUsesFindPanel($this->handle, $usesFindPanel);

        return $this;
    }

    public function usesFindBar(): bool
    {
        return ExtNSTextView::usesFindBar($this->handle);
    }

    public function setUsesFindBar(bool $usesFindBar): static
    {
        ExtNSTextView::setUsesFindBar($this->handle, $usesFindBar);

        return $this;
    }

    public function isIncrementalSearchingEnabled(): bool
    {
        return ExtNSTextView::isIncrementalSearchingEnabled($this->handle);
    }

    public function setIncrementalSearchingEnabled(bool $incrementalSearchingEnabled): static
    {
        ExtNSTextView::setIncrementalSearchingEnabled($this->handle, $incrementalSearchingEnabled);

        return $this;
    }

    public function inlinePredictionType(): NSTextInputTraitType|int
    {
        return ExtNSTextView::inlinePredictionType($this->handle);
    }

    public function setInlinePredictionType(NSTextInputTraitType|int $inlinePredictionType): static
    {
        ExtNSTextView::setInlinePredictionType($this->handle, $inlinePredictionType instanceof \BackedEnum ? $inlinePredictionType->value : $inlinePredictionType);

        return $this;
    }

    public function mathExpressionCompletionType(): NSTextInputTraitType|int
    {
        return ExtNSTextView::mathExpressionCompletionType($this->handle);
    }

    public function setMathExpressionCompletionType(NSTextInputTraitType|int $mathExpressionCompletionType): static
    {
        ExtNSTextView::setMathExpressionCompletionType($this->handle, $mathExpressionCompletionType instanceof \BackedEnum ? $mathExpressionCompletionType->value : $mathExpressionCompletionType);

        return $this;
    }

    public function toggleQuickLookPreviewPanel(int $sender): static
    {
        ExtNSTextView::toggleQuickLookPreviewPanel($this->handle, $sender);

        return $this;
    }

    public function quickLookPreviewableItemsInRanges(array $ranges): array
    {
        return ExtNSTextView::quickLookPreviewableItemsInRanges($this->handle, $ranges);
    }

    public function updateQuickLookPreviewPanel(): static
    {
        ExtNSTextView::updateQuickLookPreviewPanel($this->handle);

        return $this;
    }

    public function orderFrontSharingServicePicker(int $sender): static
    {
        ExtNSTextView::orderFrontSharingServicePicker($this->handle, $sender);

        return $this;
    }

    public function isAutomaticTextCompletionEnabled(): bool
    {
        return ExtNSTextView::isAutomaticTextCompletionEnabled($this->handle);
    }

    public function setAutomaticTextCompletionEnabled(bool $automaticTextCompletionEnabled): static
    {
        ExtNSTextView::setAutomaticTextCompletionEnabled($this->handle, $automaticTextCompletionEnabled);

        return $this;
    }

    public function toggleAutomaticTextCompletion(int $sender): static
    {
        ExtNSTextView::toggleAutomaticTextCompletion($this->handle, $sender);

        return $this;
    }

    public function allowsCharacterPickerTouchBarItem(): bool
    {
        return ExtNSTextView::allowsCharacterPickerTouchBarItem($this->handle);
    }

    public function setAllowsCharacterPickerTouchBarItem(bool $allowsCharacterPickerTouchBarItem): static
    {
        ExtNSTextView::setAllowsCharacterPickerTouchBarItem($this->handle, $allowsCharacterPickerTouchBarItem);

        return $this;
    }

    public function updateTouchBarItemIdentifiers(): static
    {
        ExtNSTextView::updateTouchBarItemIdentifiers($this->handle);

        return $this;
    }

    public function updateTextTouchBarItems(): static
    {
        ExtNSTextView::updateTextTouchBarItems($this->handle);

        return $this;
    }

    public function updateCandidates(): static
    {
        ExtNSTextView::updateCandidates($this->handle);

        return $this;
    }

    public function candidateListTouchBarItem(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::candidateListTouchBarItem($this->handle));
    }

    public static function scrollableTextView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::scrollableTextView());
    }

    public static function fieldEditor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::fieldEditor());
    }

    public static function scrollableDocumentContentTextView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::scrollableDocumentContentTextView());
    }

    public static function scrollablePlainDocumentContentTextView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSTextView::scrollablePlainDocumentContentTextView());
    }

    public function textHighlightAttributes(): int
    {
        return ExtNSTextView::textHighlightAttributes($this->handle);
    }

    public function setTextHighlightAttributes(array $textHighlightAttributes): static
    {
        ExtNSTextView::setTextHighlightAttributes($this->handle, $textHighlightAttributes);

        return $this;
    }

    public function drawTextHighlightBackgroundForTextRangeOrigin(int $textRange, NSPoint $origin): static
    {
        ExtNSTextView::drawTextHighlightBackgroundForTextRangeOrigin(...[$this->handle, $textRange, ...$origin->toArgs()]);

        return $this;
    }

    public function highlight(int $sender): static
    {
        ExtNSTextView::highlight($this->handle, $sender);

        return $this;
    }
}
