<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSToolbarItemGroup\NSToolbarItemGroup as ExtNSToolbarItemGroup;
use Jovian\Bindings\AppKit\Enums\NSToolbarItemGroupControlRepresentation;
use Jovian\Bindings\AppKit\Enums\NSToolbarItemGroupSelectionMode;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSToolbarItemGroup extends NSToolbarItem
{
    public static function initWithItemIdentifier(string $itemIdentifier): ?ObjCObject
    {
        return ObjCObject::box(ExtNSToolbarItemGroup::initWithItemIdentifier($itemIdentifier));
    }

    public static function groupWithItemIdentifierTitlesSelectionModeLabelsTargetAction(string $itemIdentifier, array $titles, NSToolbarItemGroupSelectionMode|int $selectionMode, array $labels, int $target, string $action): ?ObjCObject
    {
        return ObjCObject::box(ExtNSToolbarItemGroup::groupWithItemIdentifierTitlesSelectionModeLabelsTargetAction($itemIdentifier, $titles, $selectionMode instanceof \BackedEnum ? $selectionMode->value : $selectionMode, $labels, $target, $action));
    }

    public static function groupWithItemIdentifierImagesSelectionModeLabelsTargetAction(string $itemIdentifier, array $images, NSToolbarItemGroupSelectionMode|int $selectionMode, array $labels, int $target, string $action): ?ObjCObject
    {
        return ObjCObject::box(ExtNSToolbarItemGroup::groupWithItemIdentifierImagesSelectionModeLabelsTargetAction($itemIdentifier, $images, $selectionMode instanceof \BackedEnum ? $selectionMode->value : $selectionMode, $labels, $target, $action));
    }

    public function subitems(): array
    {
        return ExtNSToolbarItemGroup::subitems($this->handle);
    }

    public function setSubitems(array $subitems): static
    {
        ExtNSToolbarItemGroup::setSubitems($this->handle, $subitems);

        return $this;
    }

    public function controlRepresentation(): NSToolbarItemGroupControlRepresentation|int
    {
        return ExtNSToolbarItemGroup::controlRepresentation($this->handle);
    }

    public function setControlRepresentation(NSToolbarItemGroupControlRepresentation|int $controlRepresentation): static
    {
        ExtNSToolbarItemGroup::setControlRepresentation($this->handle, $controlRepresentation instanceof \BackedEnum ? $controlRepresentation->value : $controlRepresentation);

        return $this;
    }

    public function selectionMode(): NSToolbarItemGroupSelectionMode|int
    {
        return ExtNSToolbarItemGroup::selectionMode($this->handle);
    }

    public function setSelectionMode(NSToolbarItemGroupSelectionMode|int $selectionMode): static
    {
        ExtNSToolbarItemGroup::setSelectionMode($this->handle, $selectionMode instanceof \BackedEnum ? $selectionMode->value : $selectionMode);

        return $this;
    }

    public function selectedIndex(): int
    {
        return ExtNSToolbarItemGroup::selectedIndex($this->handle);
    }

    public function setSelectedIndex(int $selectedIndex): static
    {
        ExtNSToolbarItemGroup::setSelectedIndex($this->handle, $selectedIndex);

        return $this;
    }

    public function setSelectedAtIndex(bool $selected, int $index): static
    {
        ExtNSToolbarItemGroup::setSelectedAtIndex($this->handle, $selected, $index);

        return $this;
    }

    public function isSelectedAtIndex(int $index): bool
    {
        return ExtNSToolbarItemGroup::isSelectedAtIndex($this->handle, $index);
    }
}
