<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSURL\NSURL as ExtNSURL;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSURL extends ObjCObject
{
    public static function fileURLWithPath(string $path): ?ObjCObject
    {
        return ObjCObject::box(ExtNSURL::fileURLWithPath($path));
    }

    public static function URLWithString(string $URLString): ?ObjCObject
    {
        return ObjCObject::box(ExtNSURL::URLWithString($URLString));
    }

    public function absoluteString(): mixed
    {
        return ExtNSURL::absoluteString($this->handle);
    }

    public function path(): mixed
    {
        return ExtNSURL::path($this->handle);
    }

    public function isFileURL(): bool
    {
        return ExtNSURL::isFileURL($this->handle);
    }
}
