<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSViewController\NSViewController as ExtNSViewController;
use Jovian\Bindings\AppKit\Enums\NSPopoverBehavior;
use Jovian\Bindings\AppKit\Enums\NSRectEdge;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSViewController extends NSResponder
{
    public static function initWithNibNameBundle(int $nibNameOrNil, int $nibBundleOrNil): ?ObjCObject
    {
        return ObjCObject::box(ExtNSViewController::initWithNibNameBundle($nibNameOrNil, $nibBundleOrNil));
    }

    public function nibName(): mixed
    {
        return ExtNSViewController::nibName($this->handle);
    }

    public function nibBundle(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSViewController::nibBundle($this->handle));
    }

    public function representedObject(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSViewController::representedObject($this->handle));
    }

    public function setRepresentedObject(int $representedObject): static
    {
        ExtNSViewController::setRepresentedObject($this->handle, $representedObject);

        return $this;
    }

    public function title(): mixed
    {
        return ExtNSViewController::title($this->handle);
    }

    public function setTitle(string $title): static
    {
        ExtNSViewController::setTitle($this->handle, $title);

        return $this;
    }

    public function view(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSViewController::view($this->handle));
    }

    public function setView(int $view): static
    {
        ExtNSViewController::setView($this->handle, $view);

        return $this;
    }

    public function viewIfLoaded(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSViewController::viewIfLoaded($this->handle));
    }

    public function loadView(): static
    {
        ExtNSViewController::loadView($this->handle);

        return $this;
    }

    public function loadViewIfNeeded(): static
    {
        ExtNSViewController::loadViewIfNeeded($this->handle);

        return $this;
    }

    public function commitEditingWithDelegateDidCommitSelectorContextInfo(int $delegate, string $didCommitSelector, int $contextInfo): static
    {
        ExtNSViewController::commitEditingWithDelegateDidCommitSelectorContextInfo($this->handle, $delegate, $didCommitSelector, $contextInfo);

        return $this;
    }

    public function commitEditing(): bool
    {
        return ExtNSViewController::commitEditing($this->handle);
    }

    public function discardEditing(): static
    {
        ExtNSViewController::discardEditing($this->handle);

        return $this;
    }

    public function viewDidLoad(): static
    {
        ExtNSViewController::viewDidLoad($this->handle);

        return $this;
    }

    public function isViewLoaded(): bool
    {
        return ExtNSViewController::isViewLoaded($this->handle);
    }

    public function viewWillAppear(): static
    {
        ExtNSViewController::viewWillAppear($this->handle);

        return $this;
    }

    public function viewDidAppear(): static
    {
        ExtNSViewController::viewDidAppear($this->handle);

        return $this;
    }

    public function viewWillDisappear(): static
    {
        ExtNSViewController::viewWillDisappear($this->handle);

        return $this;
    }

    public function viewDidDisappear(): static
    {
        ExtNSViewController::viewDidDisappear($this->handle);

        return $this;
    }

    public function preferredContentSize(): NSSize
    {
        return NSSize::fromArray(ExtNSViewController::preferredContentSize($this->handle));
    }

    public function setPreferredContentSize(NSSize $preferredContentSize): static
    {
        ExtNSViewController::setPreferredContentSize(...[$this->handle, ...$preferredContentSize->toArgs()]);

        return $this;
    }

    public function updateViewConstraints(): static
    {
        ExtNSViewController::updateViewConstraints($this->handle);

        return $this;
    }

    public function viewWillLayout(): static
    {
        ExtNSViewController::viewWillLayout($this->handle);

        return $this;
    }

    public function viewDidLayout(): static
    {
        ExtNSViewController::viewDidLayout($this->handle);

        return $this;
    }

    public function presentViewControllerAnimator(int $viewController, int $animator): static
    {
        ExtNSViewController::presentViewControllerAnimator($this->handle, $viewController, $animator);

        return $this;
    }

    public function dismissViewController(int $viewController): static
    {
        ExtNSViewController::dismissViewController($this->handle, $viewController);

        return $this;
    }

    public function dismissController(int $sender): static
    {
        ExtNSViewController::dismissController($this->handle, $sender);

        return $this;
    }

    public function presentedViewControllers(): array
    {
        return ExtNSViewController::presentedViewControllers($this->handle);
    }

    public function presentingViewController(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSViewController::presentingViewController($this->handle));
    }

    public function presentViewControllerAsSheet(int $viewController): static
    {
        ExtNSViewController::presentViewControllerAsSheet($this->handle, $viewController);

        return $this;
    }

    public function presentViewControllerAsModalWindow(int $viewController): static
    {
        ExtNSViewController::presentViewControllerAsModalWindow($this->handle, $viewController);

        return $this;
    }

    public function presentViewControllerAsPopoverRelativeToRectOfViewPreferredEdgeBehavior(int $viewController, NSRect $positioningRect, int $positioningView, NSRectEdge|int $preferredEdge, NSPopoverBehavior|int $behavior): static
    {
        ExtNSViewController::presentViewControllerAsPopoverRelativeToRectOfViewPreferredEdgeBehavior(...[$this->handle, $viewController, ...$positioningRect->toArgs(), $positioningView, $preferredEdge instanceof \BackedEnum ? $preferredEdge->value : $preferredEdge, $behavior instanceof \BackedEnum ? $behavior->value : $behavior]);

        return $this;
    }

    public function presentViewControllerAsPopoverRelativeToRectOfViewPreferredEdgeBehaviorHasFullSizeContent(int $viewController, NSRect $positioningRect, int $positioningView, NSRectEdge|int $preferredEdge, NSPopoverBehavior|int $behavior, bool $hasFullSizeContent): static
    {
        ExtNSViewController::presentViewControllerAsPopoverRelativeToRectOfViewPreferredEdgeBehaviorHasFullSizeContent(...[$this->handle, $viewController, ...$positioningRect->toArgs(), $positioningView, $preferredEdge instanceof \BackedEnum ? $preferredEdge->value : $preferredEdge, $behavior instanceof \BackedEnum ? $behavior->value : $behavior, $hasFullSizeContent]);

        return $this;
    }

    public function parentViewController(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSViewController::parentViewController($this->handle));
    }

    public function childViewControllers(): array
    {
        return ExtNSViewController::childViewControllers($this->handle);
    }

    public function setChildViewControllers(array $childViewControllers): static
    {
        ExtNSViewController::setChildViewControllers($this->handle, $childViewControllers);

        return $this;
    }

    public function addChildViewController(int $childViewController): static
    {
        ExtNSViewController::addChildViewController($this->handle, $childViewController);

        return $this;
    }

    public function removeFromParentViewController(): static
    {
        ExtNSViewController::removeFromParentViewController($this->handle);

        return $this;
    }

    public function insertChildViewControllerAtIndex(int $childViewController, int $index): static
    {
        ExtNSViewController::insertChildViewControllerAtIndex($this->handle, $childViewController, $index);

        return $this;
    }

    public function removeChildViewControllerAtIndex(int $index): static
    {
        ExtNSViewController::removeChildViewControllerAtIndex($this->handle, $index);

        return $this;
    }

    public function preferredContentSizeDidChangeForViewController(int $viewController): static
    {
        ExtNSViewController::preferredContentSizeDidChangeForViewController($this->handle, $viewController);

        return $this;
    }

    public function viewWillTransitionToSize(NSSize $newSize): static
    {
        ExtNSViewController::viewWillTransitionToSize(...[$this->handle, ...$newSize->toArgs()]);

        return $this;
    }

    public function storyboard(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSViewController::storyboard($this->handle));
    }

    public function extensionContext(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSViewController::extensionContext($this->handle));
    }

    public function sourceItemView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSViewController::sourceItemView($this->handle));
    }

    public function setSourceItemView(int $sourceItemView): static
    {
        ExtNSViewController::setSourceItemView($this->handle, $sourceItemView);

        return $this;
    }

    public function preferredScreenOrigin(): NSPoint
    {
        return NSPoint::fromArray(ExtNSViewController::preferredScreenOrigin($this->handle));
    }

    public function setPreferredScreenOrigin(NSPoint $preferredScreenOrigin): static
    {
        ExtNSViewController::setPreferredScreenOrigin(...[$this->handle, ...$preferredScreenOrigin->toArgs()]);

        return $this;
    }

    public function preferredMinimumSize(): NSSize
    {
        return NSSize::fromArray(ExtNSViewController::preferredMinimumSize($this->handle));
    }

    public function preferredMaximumSize(): NSSize
    {
        return NSSize::fromArray(ExtNSViewController::preferredMaximumSize($this->handle));
    }
}
