<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSView\NSView as ExtNSView;
use Jovian\Bindings\AppKit\Enums\NSFocusRingType;
use Jovian\Bindings\AppKit\Enums\NSUserInterfaceLayoutDirection;
use Jovian\Bindings\AppKit\Enums\NSViewLayerContentsPlacement;
use Jovian\Bindings\AppKit\Enums\NSViewLayerContentsRedrawPolicy;
use Jovian\Bindings\AppKit\Enums\NSWindowOrderingMode;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSView extends NSResponder
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function window(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::window($this->handle));
    }

    public function superview(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::superview($this->handle));
    }

    public function subviews(): array
    {
        return ExtNSView::subviews($this->handle);
    }

    public function setSubviews(array $subviews): static
    {
        ExtNSView::setSubviews($this->handle, $subviews);

        return $this;
    }

    public function isDescendantOf(int $view): bool
    {
        return ExtNSView::isDescendantOf($this->handle, $view);
    }

    public function ancestorSharedWithView(int $view): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::ancestorSharedWithView($this->handle, $view));
    }

    public function opaqueAncestor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::opaqueAncestor($this->handle));
    }

    public function isHidden(): bool
    {
        return ExtNSView::isHidden($this->handle);
    }

    public function setHidden(bool $hidden): static
    {
        ExtNSView::setHidden($this->handle, $hidden);

        return $this;
    }

    public function isHiddenOrHasHiddenAncestor(): bool
    {
        return ExtNSView::isHiddenOrHasHiddenAncestor($this->handle);
    }

    public function getRectsBeingDrawnCount(): array
    {
        return ExtNSView::getRectsBeingDrawnCount($this->handle);
    }

    public function needsToDrawRect(NSRect $rect): bool
    {
        return ExtNSView::needsToDrawRect(...[$this->handle, ...$rect->toArgs()]);
    }

    public function wantsDefaultClipping(): bool
    {
        return ExtNSView::wantsDefaultClipping($this->handle);
    }

    public function viewDidHide(): static
    {
        ExtNSView::viewDidHide($this->handle);

        return $this;
    }

    public function viewDidUnhide(): static
    {
        ExtNSView::viewDidUnhide($this->handle);

        return $this;
    }

    public function addSubview(int $view): static
    {
        ExtNSView::addSubview($this->handle, $view);

        return $this;
    }

    public function addSubviewPositionedRelativeTo(int $view, NSWindowOrderingMode|int $place, int $otherView): static
    {
        ExtNSView::addSubviewPositionedRelativeTo($this->handle, $view, $place instanceof \BackedEnum ? $place->value : $place, $otherView);

        return $this;
    }

    public function viewWillMoveToWindow(int $newWindow): static
    {
        ExtNSView::viewWillMoveToWindow($this->handle, $newWindow);

        return $this;
    }

    public function viewDidMoveToWindow(): static
    {
        ExtNSView::viewDidMoveToWindow($this->handle);

        return $this;
    }

    public function viewWillMoveToSuperview(int $newSuperview): static
    {
        ExtNSView::viewWillMoveToSuperview($this->handle, $newSuperview);

        return $this;
    }

    public function viewDidMoveToSuperview(): static
    {
        ExtNSView::viewDidMoveToSuperview($this->handle);

        return $this;
    }

    public function didAddSubview(int $subview): static
    {
        ExtNSView::didAddSubview($this->handle, $subview);

        return $this;
    }

    public function willRemoveSubview(int $subview): static
    {
        ExtNSView::willRemoveSubview($this->handle, $subview);

        return $this;
    }

    public function removeFromSuperview(): static
    {
        ExtNSView::removeFromSuperview($this->handle);

        return $this;
    }

    public function replaceSubviewWith(int $oldView, int $newView): static
    {
        ExtNSView::replaceSubviewWith($this->handle, $oldView, $newView);

        return $this;
    }

    public function removeFromSuperviewWithoutNeedingDisplay(): static
    {
        ExtNSView::removeFromSuperviewWithoutNeedingDisplay($this->handle);

        return $this;
    }

    public function viewDidChangeBackingProperties(): static
    {
        ExtNSView::viewDidChangeBackingProperties($this->handle);

        return $this;
    }

    public function postsFrameChangedNotifications(): bool
    {
        return ExtNSView::postsFrameChangedNotifications($this->handle);
    }

    public function setPostsFrameChangedNotifications(bool $postsFrameChangedNotifications): static
    {
        ExtNSView::setPostsFrameChangedNotifications($this->handle, $postsFrameChangedNotifications);

        return $this;
    }

    public function resizeSubviewsWithOldSize(NSSize $oldSize): static
    {
        ExtNSView::resizeSubviewsWithOldSize(...[$this->handle, ...$oldSize->toArgs()]);

        return $this;
    }

    public function resizeWithOldSuperviewSize(NSSize $oldSize): static
    {
        ExtNSView::resizeWithOldSuperviewSize(...[$this->handle, ...$oldSize->toArgs()]);

        return $this;
    }

    public function autoresizesSubviews(): bool
    {
        return ExtNSView::autoresizesSubviews($this->handle);
    }

    public function setAutoresizesSubviews(bool $autoresizesSubviews): static
    {
        ExtNSView::setAutoresizesSubviews($this->handle, $autoresizesSubviews);

        return $this;
    }

    public function autoresizingMask(): int
    {
        return ExtNSView::autoresizingMask($this->handle);
    }

    public function setAutoresizingMask(int $autoresizingMask): static
    {
        ExtNSView::setAutoresizingMask($this->handle, $autoresizingMask);

        return $this;
    }

    public function setFrameOrigin(NSPoint $newOrigin): static
    {
        ExtNSView::setFrameOrigin(...[$this->handle, ...$newOrigin->toArgs()]);

        return $this;
    }

    public function setFrameSize(NSSize $newSize): static
    {
        ExtNSView::setFrameSize(...[$this->handle, ...$newSize->toArgs()]);

        return $this;
    }

    public function frame(): NSRect
    {
        return NSRect::fromArray(ExtNSView::frame($this->handle));
    }

    public function setFrame(NSRect $frame): static
    {
        ExtNSView::setFrame(...[$this->handle, ...$frame->toArgs()]);

        return $this;
    }

    public function frameRotation(): float
    {
        return ExtNSView::frameRotation($this->handle);
    }

    public function setFrameRotation(float $frameRotation): static
    {
        ExtNSView::setFrameRotation($this->handle, $frameRotation);

        return $this;
    }

    public function frameCenterRotation(): float
    {
        return ExtNSView::frameCenterRotation($this->handle);
    }

    public function setFrameCenterRotation(float $frameCenterRotation): static
    {
        ExtNSView::setFrameCenterRotation($this->handle, $frameCenterRotation);

        return $this;
    }

    public function setBoundsOrigin(NSPoint $newOrigin): static
    {
        ExtNSView::setBoundsOrigin(...[$this->handle, ...$newOrigin->toArgs()]);

        return $this;
    }

    public function setBoundsSize(NSSize $newSize): static
    {
        ExtNSView::setBoundsSize(...[$this->handle, ...$newSize->toArgs()]);

        return $this;
    }

    public function boundsRotation(): float
    {
        return ExtNSView::boundsRotation($this->handle);
    }

    public function setBoundsRotation(float $boundsRotation): static
    {
        ExtNSView::setBoundsRotation($this->handle, $boundsRotation);

        return $this;
    }

    public function translateOriginToPoint(NSPoint $translation): static
    {
        ExtNSView::translateOriginToPoint(...[$this->handle, ...$translation->toArgs()]);

        return $this;
    }

    public function scaleUnitSquareToSize(NSSize $newUnitSize): static
    {
        ExtNSView::scaleUnitSquareToSize(...[$this->handle, ...$newUnitSize->toArgs()]);

        return $this;
    }

    public function rotateByAngle(float $angle): static
    {
        ExtNSView::rotateByAngle($this->handle, $angle);

        return $this;
    }

    public function bounds(): NSRect
    {
        return NSRect::fromArray(ExtNSView::bounds($this->handle));
    }

    public function setBounds(NSRect $bounds): static
    {
        ExtNSView::setBounds(...[$this->handle, ...$bounds->toArgs()]);

        return $this;
    }

    public function isFlipped(): bool
    {
        return ExtNSView::isFlipped($this->handle);
    }

    public function isRotatedFromBase(): bool
    {
        return ExtNSView::isRotatedFromBase($this->handle);
    }

    public function isRotatedOrScaledFromBase(): bool
    {
        return ExtNSView::isRotatedOrScaledFromBase($this->handle);
    }

    public function isOpaque(): bool
    {
        return ExtNSView::isOpaque($this->handle);
    }

    public function convertPointFromView(NSPoint $point, int $view): NSPoint
    {
        return NSPoint::fromArray(ExtNSView::convertPointFromView(...[$this->handle, ...$point->toArgs(), $view]));
    }

    public function convertPointToView(NSPoint $point, int $view): NSPoint
    {
        return NSPoint::fromArray(ExtNSView::convertPointToView(...[$this->handle, ...$point->toArgs(), $view]));
    }

    public function convertSizeFromView(NSSize $size, int $view): NSSize
    {
        return NSSize::fromArray(ExtNSView::convertSizeFromView(...[$this->handle, ...$size->toArgs(), $view]));
    }

    public function convertSizeToView(NSSize $size, int $view): NSSize
    {
        return NSSize::fromArray(ExtNSView::convertSizeToView(...[$this->handle, ...$size->toArgs(), $view]));
    }

    public function convertRectFromView(NSRect $rect, int $view): NSRect
    {
        return NSRect::fromArray(ExtNSView::convertRectFromView(...[$this->handle, ...$rect->toArgs(), $view]));
    }

    public function convertRectToView(NSRect $rect, int $view): NSRect
    {
        return NSRect::fromArray(ExtNSView::convertRectToView(...[$this->handle, ...$rect->toArgs(), $view]));
    }

    public function backingAlignedRectOptions(NSRect $rect, int $options): NSRect
    {
        return NSRect::fromArray(ExtNSView::backingAlignedRectOptions(...[$this->handle, ...$rect->toArgs(), $options]));
    }

    public function centerScanRect(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSView::centerScanRect(...[$this->handle, ...$rect->toArgs()]));
    }

    public function convertPointToBacking(NSPoint $point): NSPoint
    {
        return NSPoint::fromArray(ExtNSView::convertPointToBacking(...[$this->handle, ...$point->toArgs()]));
    }

    public function convertPointFromBacking(NSPoint $point): NSPoint
    {
        return NSPoint::fromArray(ExtNSView::convertPointFromBacking(...[$this->handle, ...$point->toArgs()]));
    }

    public function convertSizeToBacking(NSSize $size): NSSize
    {
        return NSSize::fromArray(ExtNSView::convertSizeToBacking(...[$this->handle, ...$size->toArgs()]));
    }

    public function convertSizeFromBacking(NSSize $size): NSSize
    {
        return NSSize::fromArray(ExtNSView::convertSizeFromBacking(...[$this->handle, ...$size->toArgs()]));
    }

    public function convertRectToBacking(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSView::convertRectToBacking(...[$this->handle, ...$rect->toArgs()]));
    }

    public function convertRectFromBacking(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSView::convertRectFromBacking(...[$this->handle, ...$rect->toArgs()]));
    }

    public function convertPointToLayer(NSPoint $point): NSPoint
    {
        return NSPoint::fromArray(ExtNSView::convertPointToLayer(...[$this->handle, ...$point->toArgs()]));
    }

    public function convertPointFromLayer(NSPoint $point): NSPoint
    {
        return NSPoint::fromArray(ExtNSView::convertPointFromLayer(...[$this->handle, ...$point->toArgs()]));
    }

    public function convertSizeToLayer(NSSize $size): NSSize
    {
        return NSSize::fromArray(ExtNSView::convertSizeToLayer(...[$this->handle, ...$size->toArgs()]));
    }

    public function convertSizeFromLayer(NSSize $size): NSSize
    {
        return NSSize::fromArray(ExtNSView::convertSizeFromLayer(...[$this->handle, ...$size->toArgs()]));
    }

    public function convertRectToLayer(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSView::convertRectToLayer(...[$this->handle, ...$rect->toArgs()]));
    }

    public function convertRectFromLayer(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSView::convertRectFromLayer(...[$this->handle, ...$rect->toArgs()]));
    }

    public function canDrawConcurrently(): bool
    {
        return ExtNSView::canDrawConcurrently($this->handle);
    }

    public function setCanDrawConcurrently(bool $canDrawConcurrently): static
    {
        ExtNSView::setCanDrawConcurrently($this->handle, $canDrawConcurrently);

        return $this;
    }

    public function setNeedsDisplayInRect(NSRect $invalidRect): static
    {
        ExtNSView::setNeedsDisplayInRect(...[$this->handle, ...$invalidRect->toArgs()]);

        return $this;
    }

    public function needsDisplay(): bool
    {
        return ExtNSView::needsDisplay($this->handle);
    }

    public function setNeedsDisplay(bool $needsDisplay): static
    {
        ExtNSView::setNeedsDisplay($this->handle, $needsDisplay);

        return $this;
    }

    public static function focusView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::focusView());
    }

    public function visibleRect(): NSRect
    {
        return NSRect::fromArray(ExtNSView::visibleRect($this->handle));
    }

    public function display(): static
    {
        ExtNSView::display($this->handle);

        return $this;
    }

    public function displayIfNeeded(): static
    {
        ExtNSView::displayIfNeeded($this->handle);

        return $this;
    }

    public function displayIfNeededIgnoringOpacity(): static
    {
        ExtNSView::displayIfNeededIgnoringOpacity($this->handle);

        return $this;
    }

    public function displayRect(NSRect $rect): static
    {
        ExtNSView::displayRect(...[$this->handle, ...$rect->toArgs()]);

        return $this;
    }

    public function displayIfNeededInRect(NSRect $rect): static
    {
        ExtNSView::displayIfNeededInRect(...[$this->handle, ...$rect->toArgs()]);

        return $this;
    }

    public function displayRectIgnoringOpacity(NSRect $rect): static
    {
        ExtNSView::displayRectIgnoringOpacity(...[$this->handle, ...$rect->toArgs()]);

        return $this;
    }

    public function displayIfNeededInRectIgnoringOpacity(NSRect $rect): static
    {
        ExtNSView::displayIfNeededInRectIgnoringOpacity(...[$this->handle, ...$rect->toArgs()]);

        return $this;
    }

    public function drawRect(NSRect $dirtyRect): static
    {
        ExtNSView::drawRect(...[$this->handle, ...$dirtyRect->toArgs()]);

        return $this;
    }

    public function displayRectIgnoringOpacityInContext(NSRect $rect, int $context): static
    {
        ExtNSView::displayRectIgnoringOpacityInContext(...[$this->handle, ...$rect->toArgs(), $context]);

        return $this;
    }

    public function bitmapImageRepForCachingDisplayInRect(NSRect $rect): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::bitmapImageRepForCachingDisplayInRect(...[$this->handle, ...$rect->toArgs()]));
    }

    public function cacheDisplayInRectToBitmapImageRep(NSRect $rect, int $bitmapImageRep): static
    {
        ExtNSView::cacheDisplayInRectToBitmapImageRep(...[$this->handle, ...$rect->toArgs(), $bitmapImageRep]);

        return $this;
    }

    public function viewWillDraw(): static
    {
        ExtNSView::viewWillDraw($this->handle);

        return $this;
    }

    public function scrollPoint(NSPoint $point): static
    {
        ExtNSView::scrollPoint(...[$this->handle, ...$point->toArgs()]);

        return $this;
    }

    public function scrollRectToVisible(NSRect $rect): bool
    {
        return ExtNSView::scrollRectToVisible(...[$this->handle, ...$rect->toArgs()]);
    }

    public function autoscroll(int $event): bool
    {
        return ExtNSView::autoscroll($this->handle, $event);
    }

    public function adjustScroll(NSRect $newVisible): NSRect
    {
        return NSRect::fromArray(ExtNSView::adjustScroll(...[$this->handle, ...$newVisible->toArgs()]));
    }

    public function translateRectsNeedingDisplayInRectBy(NSRect $clipRect, NSSize $delta): static
    {
        ExtNSView::translateRectsNeedingDisplayInRectBy(...[$this->handle, ...$clipRect->toArgs(), ...$delta->toArgs()]);

        return $this;
    }

    public function hitTest(NSPoint $point): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::hitTest(...[$this->handle, ...$point->toArgs()]));
    }

    public function mouseInRect(NSPoint $point, NSRect $rect): bool
    {
        return ExtNSView::mouseInRect(...[$this->handle, ...$point->toArgs(), ...$rect->toArgs()]);
    }

    public function viewWithTag(int $tag): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::viewWithTag($this->handle, $tag));
    }

    public function tag(): int
    {
        return ExtNSView::tag($this->handle);
    }

    public function performKeyEquivalent(int $event): bool
    {
        return ExtNSView::performKeyEquivalent($this->handle, $event);
    }

    public function acceptsFirstMouse(int $event): bool
    {
        return ExtNSView::acceptsFirstMouse($this->handle, $event);
    }

    public function shouldDelayWindowOrderingForEvent(int $event): bool
    {
        return ExtNSView::shouldDelayWindowOrderingForEvent($this->handle, $event);
    }

    public function needsPanelToBecomeKey(): bool
    {
        return ExtNSView::needsPanelToBecomeKey($this->handle);
    }

    public function mouseDownCanMoveWindow(): bool
    {
        return ExtNSView::mouseDownCanMoveWindow($this->handle);
    }

    public function wantsRestingTouches(): bool
    {
        return ExtNSView::wantsRestingTouches($this->handle);
    }

    public function setWantsRestingTouches(bool $wantsRestingTouches): static
    {
        ExtNSView::setWantsRestingTouches($this->handle, $wantsRestingTouches);

        return $this;
    }

    public function makeBackingLayer(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::makeBackingLayer($this->handle));
    }

    public function layerContentsRedrawPolicy(): NSViewLayerContentsRedrawPolicy|int
    {
        return ExtNSView::layerContentsRedrawPolicy($this->handle);
    }

    public function setLayerContentsRedrawPolicy(NSViewLayerContentsRedrawPolicy|int $layerContentsRedrawPolicy): static
    {
        ExtNSView::setLayerContentsRedrawPolicy($this->handle, $layerContentsRedrawPolicy instanceof \BackedEnum ? $layerContentsRedrawPolicy->value : $layerContentsRedrawPolicy);

        return $this;
    }

    public function layerContentsPlacement(): NSViewLayerContentsPlacement|int
    {
        return ExtNSView::layerContentsPlacement($this->handle);
    }

    public function setLayerContentsPlacement(NSViewLayerContentsPlacement|int $layerContentsPlacement): static
    {
        ExtNSView::setLayerContentsPlacement($this->handle, $layerContentsPlacement instanceof \BackedEnum ? $layerContentsPlacement->value : $layerContentsPlacement);

        return $this;
    }

    public function wantsLayer(): bool
    {
        return ExtNSView::wantsLayer($this->handle);
    }

    public function setWantsLayer(bool $wantsLayer): static
    {
        ExtNSView::setWantsLayer($this->handle, $wantsLayer);

        return $this;
    }

    public function layer(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::layer($this->handle));
    }

    public function setLayer(int $layer): static
    {
        ExtNSView::setLayer($this->handle, $layer);

        return $this;
    }

    public function wantsUpdateLayer(): bool
    {
        return ExtNSView::wantsUpdateLayer($this->handle);
    }

    public function updateLayer(): static
    {
        ExtNSView::updateLayer($this->handle);

        return $this;
    }

    public function canDrawSubviewsIntoLayer(): bool
    {
        return ExtNSView::canDrawSubviewsIntoLayer($this->handle);
    }

    public function setCanDrawSubviewsIntoLayer(bool $canDrawSubviewsIntoLayer): static
    {
        ExtNSView::setCanDrawSubviewsIntoLayer($this->handle, $canDrawSubviewsIntoLayer);

        return $this;
    }

    public function layoutSubtreeIfNeeded(): static
    {
        ExtNSView::layoutSubtreeIfNeeded($this->handle);

        return $this;
    }

    public function layout(): static
    {
        ExtNSView::layout($this->handle);

        return $this;
    }

    public function needsLayout(): bool
    {
        return ExtNSView::needsLayout($this->handle);
    }

    public function setNeedsLayout(bool $needsLayout): static
    {
        ExtNSView::setNeedsLayout($this->handle, $needsLayout);

        return $this;
    }

    public function alphaValue(): float
    {
        return ExtNSView::alphaValue($this->handle);
    }

    public function setAlphaValue(float $alphaValue): static
    {
        ExtNSView::setAlphaValue($this->handle, $alphaValue);

        return $this;
    }

    public function layerUsesCoreImageFilters(): bool
    {
        return ExtNSView::layerUsesCoreImageFilters($this->handle);
    }

    public function setLayerUsesCoreImageFilters(bool $layerUsesCoreImageFilters): static
    {
        ExtNSView::setLayerUsesCoreImageFilters($this->handle, $layerUsesCoreImageFilters);

        return $this;
    }

    public function backgroundFilters(): array
    {
        return ExtNSView::backgroundFilters($this->handle);
    }

    public function setBackgroundFilters(array $backgroundFilters): static
    {
        ExtNSView::setBackgroundFilters($this->handle, $backgroundFilters);

        return $this;
    }

    public function compositingFilter(): int
    {
        return ExtNSView::compositingFilter($this->handle);
    }

    public function setCompositingFilter(int $compositingFilter): static
    {
        ExtNSView::setCompositingFilter($this->handle, $compositingFilter);

        return $this;
    }

    public function contentFilters(): array
    {
        return ExtNSView::contentFilters($this->handle);
    }

    public function setContentFilters(array $contentFilters): static
    {
        ExtNSView::setContentFilters($this->handle, $contentFilters);

        return $this;
    }

    public function shadow(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::shadow($this->handle));
    }

    public function setShadow(int $shadow): static
    {
        ExtNSView::setShadow($this->handle, $shadow);

        return $this;
    }

    public function clipsToBounds(): bool
    {
        return ExtNSView::clipsToBounds($this->handle);
    }

    public function setClipsToBounds(bool $clipsToBounds): static
    {
        ExtNSView::setClipsToBounds($this->handle, $clipsToBounds);

        return $this;
    }

    public function postsBoundsChangedNotifications(): bool
    {
        return ExtNSView::postsBoundsChangedNotifications($this->handle);
    }

    public function setPostsBoundsChangedNotifications(bool $postsBoundsChangedNotifications): static
    {
        ExtNSView::setPostsBoundsChangedNotifications($this->handle, $postsBoundsChangedNotifications);

        return $this;
    }

    public function enclosingScrollView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::enclosingScrollView($this->handle));
    }

    public function menuForEvent(int $event): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::menuForEvent($this->handle, $event));
    }

    public static function defaultMenu(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::defaultMenu());
    }

    public function willOpenMenuWithEvent(int $menu, int $event): static
    {
        ExtNSView::willOpenMenuWithEvent($this->handle, $menu, $event);

        return $this;
    }

    public function didCloseMenuWithEvent(int $menu, int $event): static
    {
        ExtNSView::didCloseMenuWithEvent($this->handle, $menu, $event);

        return $this;
    }

    public function toolTip(): mixed
    {
        return ExtNSView::toolTip($this->handle);
    }

    public function setToolTip(string $toolTip): static
    {
        ExtNSView::setToolTip($this->handle, $toolTip);

        return $this;
    }

    public function addToolTipRectOwnerUserData(NSRect $rect, int $owner, int $data): int
    {
        return ExtNSView::addToolTipRectOwnerUserData(...[$this->handle, ...$rect->toArgs(), $owner, $data]);
    }

    public function removeToolTip(int $tag): static
    {
        ExtNSView::removeToolTip($this->handle, $tag);

        return $this;
    }

    public function removeAllToolTips(): static
    {
        ExtNSView::removeAllToolTips($this->handle);

        return $this;
    }

    public function viewWillStartLiveResize(): static
    {
        ExtNSView::viewWillStartLiveResize($this->handle);

        return $this;
    }

    public function viewDidEndLiveResize(): static
    {
        ExtNSView::viewDidEndLiveResize($this->handle);

        return $this;
    }

    public function inLiveResize(): bool
    {
        return ExtNSView::inLiveResize($this->handle);
    }

    public function preservesContentDuringLiveResize(): bool
    {
        return ExtNSView::preservesContentDuringLiveResize($this->handle);
    }

    public function rectPreservedDuringLiveResize(): NSRect
    {
        return NSRect::fromArray(ExtNSView::rectPreservedDuringLiveResize($this->handle));
    }

    public function getRectsExposedDuringLiveResizeCount(): array
    {
        return ExtNSView::getRectsExposedDuringLiveResizeCount($this->handle);
    }

    public function inputContext(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::inputContext($this->handle));
    }

    public function rectForSmartMagnificationAtPointInRect(NSPoint $location, NSRect $visibleRect): NSRect
    {
        return NSRect::fromArray(ExtNSView::rectForSmartMagnificationAtPointInRect(...[$this->handle, ...$location->toArgs(), ...$visibleRect->toArgs()]));
    }

    public function userInterfaceLayoutDirection(): NSUserInterfaceLayoutDirection|int
    {
        return ExtNSView::userInterfaceLayoutDirection($this->handle);
    }

    public function setUserInterfaceLayoutDirection(NSUserInterfaceLayoutDirection|int $userInterfaceLayoutDirection): static
    {
        ExtNSView::setUserInterfaceLayoutDirection($this->handle, $userInterfaceLayoutDirection instanceof \BackedEnum ? $userInterfaceLayoutDirection->value : $userInterfaceLayoutDirection);

        return $this;
    }

    public function prepareForReuse(): static
    {
        ExtNSView::prepareForReuse($this->handle);

        return $this;
    }

    public static function isCompatibleWithResponsiveScrolling(): bool
    {
        return ExtNSView::isCompatibleWithResponsiveScrolling();
    }

    public function prepareContentInRect(NSRect $rect): static
    {
        ExtNSView::prepareContentInRect(...[$this->handle, ...$rect->toArgs()]);

        return $this;
    }

    public function preparedContentRect(): NSRect
    {
        return NSRect::fromArray(ExtNSView::preparedContentRect($this->handle));
    }

    public function setPreparedContentRect(NSRect $preparedContentRect): static
    {
        ExtNSView::setPreparedContentRect(...[$this->handle, ...$preparedContentRect->toArgs()]);

        return $this;
    }

    public function allowsVibrancy(): bool
    {
        return ExtNSView::allowsVibrancy($this->handle);
    }

    public function viewDidChangeEffectiveAppearance(): static
    {
        ExtNSView::viewDidChangeEffectiveAppearance($this->handle);

        return $this;
    }

    public function nextKeyView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::nextKeyView($this->handle));
    }

    public function setNextKeyView(int $nextKeyView): static
    {
        ExtNSView::setNextKeyView($this->handle, $nextKeyView);

        return $this;
    }

    public function previousKeyView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::previousKeyView($this->handle));
    }

    public function nextValidKeyView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::nextValidKeyView($this->handle));
    }

    public function previousValidKeyView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::previousValidKeyView($this->handle));
    }

    public function canBecomeKeyView(): bool
    {
        return ExtNSView::canBecomeKeyView($this->handle);
    }

    public function setKeyboardFocusRingNeedsDisplayInRect(NSRect $rect): static
    {
        ExtNSView::setKeyboardFocusRingNeedsDisplayInRect(...[$this->handle, ...$rect->toArgs()]);

        return $this;
    }

    public function focusRingType(): NSFocusRingType|int
    {
        return ExtNSView::focusRingType($this->handle);
    }

    public function setFocusRingType(NSFocusRingType|int $focusRingType): static
    {
        ExtNSView::setFocusRingType($this->handle, $focusRingType instanceof \BackedEnum ? $focusRingType->value : $focusRingType);

        return $this;
    }

    public static function defaultFocusRingType(): NSFocusRingType|int
    {
        return ExtNSView::defaultFocusRingType();
    }

    public function drawFocusRingMask(): static
    {
        ExtNSView::drawFocusRingMask($this->handle);

        return $this;
    }

    public function focusRingMaskBounds(): NSRect
    {
        return NSRect::fromArray(ExtNSView::focusRingMaskBounds($this->handle));
    }

    public function noteFocusRingMaskChanged(): static
    {
        ExtNSView::noteFocusRingMaskChanged($this->handle);

        return $this;
    }

    public function writeEPSInsideRectToPasteboard(NSRect $rect, int $pasteboard): static
    {
        ExtNSView::writeEPSInsideRectToPasteboard(...[$this->handle, ...$rect->toArgs(), $pasteboard]);

        return $this;
    }

    public function writePDFInsideRectToPasteboard(NSRect $rect, int $pasteboard): static
    {
        ExtNSView::writePDFInsideRectToPasteboard(...[$this->handle, ...$rect->toArgs(), $pasteboard]);

        return $this;
    }

    public function print_(int $sender): static
    {
        ExtNSView::print_($this->handle, $sender);

        return $this;
    }

    public function knowsPageRange(): array
    {
        return ExtNSView::knowsPageRange($this->handle);
    }

    public function heightAdjustLimit(): float
    {
        return ExtNSView::heightAdjustLimit($this->handle);
    }

    public function widthAdjustLimit(): float
    {
        return ExtNSView::widthAdjustLimit($this->handle);
    }

    public function adjustPageWidthNewLeftRightLimit(float $oldLeft, float $oldRight, float $rightLimit): array
    {
        return ExtNSView::adjustPageWidthNewLeftRightLimit($this->handle, $oldLeft, $oldRight, $rightLimit);
    }

    public function adjustPageHeightNewTopBottomLimit(float $oldTop, float $oldBottom, float $bottomLimit): array
    {
        return ExtNSView::adjustPageHeightNewTopBottomLimit($this->handle, $oldTop, $oldBottom, $bottomLimit);
    }

    public function rectForPage(int $page): NSRect
    {
        return NSRect::fromArray(ExtNSView::rectForPage($this->handle, $page));
    }

    public function locationOfPrintRect(NSRect $rect): NSPoint
    {
        return NSPoint::fromArray(ExtNSView::locationOfPrintRect(...[$this->handle, ...$rect->toArgs()]));
    }

    public function drawPageBorderWithSize(NSSize $borderSize): static
    {
        ExtNSView::drawPageBorderWithSize(...[$this->handle, ...$borderSize->toArgs()]);

        return $this;
    }

    public function printJobTitle(): ?string
    {
        return ExtNSView::printJobTitle($this->handle);
    }

    public function beginDocument(): static
    {
        ExtNSView::beginDocument($this->handle);

        return $this;
    }

    public function endDocument(): static
    {
        ExtNSView::endDocument($this->handle);

        return $this;
    }

    public function beginPageInRectAtPlacement(NSRect $rect, NSPoint $location): static
    {
        ExtNSView::beginPageInRectAtPlacement(...[$this->handle, ...$rect->toArgs(), ...$location->toArgs()]);

        return $this;
    }

    public function endPage(): static
    {
        ExtNSView::endPage($this->handle);

        return $this;
    }

    public function beginDraggingSessionWithItemsEventSource(array $items, int $event, int $source): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::beginDraggingSessionWithItemsEventSource($this->handle, $items, $event, $source));
    }

    public function registeredDraggedTypes(): array
    {
        return ExtNSView::registeredDraggedTypes($this->handle);
    }

    public function registerForDraggedTypes(array $newTypes): static
    {
        ExtNSView::registerForDraggedTypes($this->handle, $newTypes);

        return $this;
    }

    public function unregisterDraggedTypes(): static
    {
        ExtNSView::unregisterDraggedTypes($this->handle);

        return $this;
    }

    public function enterFullScreenModeWithOptions(int $screen, array $options): bool
    {
        return ExtNSView::enterFullScreenModeWithOptions($this->handle, $screen, $options);
    }

    public function exitFullScreenModeWithOptions(array $options): static
    {
        ExtNSView::exitFullScreenModeWithOptions($this->handle, $options);

        return $this;
    }

    public function isInFullScreenMode(): bool
    {
        return ExtNSView::isInFullScreenMode($this->handle);
    }

    public function isDrawingFindIndicator(): bool
    {
        return ExtNSView::isDrawingFindIndicator($this->handle);
    }

    public function gestureRecognizers(): array
    {
        return ExtNSView::gestureRecognizers($this->handle);
    }

    public function setGestureRecognizers(array $gestureRecognizers): static
    {
        ExtNSView::setGestureRecognizers($this->handle, $gestureRecognizers);

        return $this;
    }

    public function addGestureRecognizer(int $gestureRecognizer): static
    {
        ExtNSView::addGestureRecognizer($this->handle, $gestureRecognizer);

        return $this;
    }

    public function removeGestureRecognizer(int $gestureRecognizer): static
    {
        ExtNSView::removeGestureRecognizer($this->handle, $gestureRecognizer);

        return $this;
    }

    public function allowedTouchTypes(): int
    {
        return ExtNSView::allowedTouchTypes($this->handle);
    }

    public function setAllowedTouchTypes(int $allowedTouchTypes): static
    {
        ExtNSView::setAllowedTouchTypes($this->handle, $allowedTouchTypes);

        return $this;
    }

    public function safeAreaInsets(): NSEdgeInsets
    {
        return NSEdgeInsets::fromArray(ExtNSView::safeAreaInsets($this->handle));
    }

    public function additionalSafeAreaInsets(): NSEdgeInsets
    {
        return NSEdgeInsets::fromArray(ExtNSView::additionalSafeAreaInsets($this->handle));
    }

    public function setAdditionalSafeAreaInsets(NSEdgeInsets $additionalSafeAreaInsets): static
    {
        ExtNSView::setAdditionalSafeAreaInsets(...[$this->handle, ...$additionalSafeAreaInsets->toArgs()]);

        return $this;
    }

    public function safeAreaLayoutGuide(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::safeAreaLayoutGuide($this->handle));
    }

    public function safeAreaRect(): NSRect
    {
        return NSRect::fromArray(ExtNSView::safeAreaRect($this->handle));
    }

    public function layoutMarginsGuide(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::layoutMarginsGuide($this->handle));
    }

    public function addTrackingArea(int $trackingArea): static
    {
        ExtNSView::addTrackingArea($this->handle, $trackingArea);

        return $this;
    }

    public function removeTrackingArea(int $trackingArea): static
    {
        ExtNSView::removeTrackingArea($this->handle, $trackingArea);

        return $this;
    }

    public function trackingAreas(): array
    {
        return ExtNSView::trackingAreas($this->handle);
    }

    public function updateTrackingAreas(): static
    {
        ExtNSView::updateTrackingAreas($this->handle);

        return $this;
    }

    public function addCursorRectCursor(NSRect $rect, int $object): static
    {
        ExtNSView::addCursorRectCursor(...[$this->handle, ...$rect->toArgs(), $object]);

        return $this;
    }

    public function removeCursorRectCursor(NSRect $rect, int $object): static
    {
        ExtNSView::removeCursorRectCursor(...[$this->handle, ...$rect->toArgs(), $object]);

        return $this;
    }

    public function discardCursorRects(): static
    {
        ExtNSView::discardCursorRects($this->handle);

        return $this;
    }

    public function resetCursorRects(): static
    {
        ExtNSView::resetCursorRects($this->handle);

        return $this;
    }

    public function addTrackingRectOwnerUserDataAssumeInside(NSRect $rect, int $owner, int $data, bool $flag): int
    {
        return ExtNSView::addTrackingRectOwnerUserDataAssumeInside(...[$this->handle, ...$rect->toArgs(), $owner, $data, $flag]);
    }

    public function removeTrackingRect(int $tag): static
    {
        ExtNSView::removeTrackingRect($this->handle, $tag);

        return $this;
    }

    public function displayLinkWithTargetSelector(int $target, string $selector): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::displayLinkWithTargetSelector($this->handle, $target, $selector));
    }

    public function writingToolsCoordinator(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSView::writingToolsCoordinator($this->handle));
    }

    public function setWritingToolsCoordinator(int $writingToolsCoordinator): static
    {
        ExtNSView::setWritingToolsCoordinator($this->handle, $writingToolsCoordinator);

        return $this;
    }
}
