<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\NS;

use AppKit\NS\NSWindow\NSWindow as ExtNSWindow;
use Jovian\Bindings\AppKit\Enums\NSBackingStoreType;
use Jovian\Bindings\AppKit\Enums\NSDisplayGamut;
use Jovian\Bindings\AppKit\Enums\NSRectEdge;
use Jovian\Bindings\AppKit\Enums\NSSelectionDirection;
use Jovian\Bindings\AppKit\Enums\NSTitlebarSeparatorStyle;
use Jovian\Bindings\AppKit\Enums\NSUserInterfaceLayoutDirection;
use Jovian\Bindings\AppKit\Enums\NSWindowAnimationBehavior;
use Jovian\Bindings\AppKit\Enums\NSWindowButton;
use Jovian\Bindings\AppKit\Enums\NSWindowDepth;
use Jovian\Bindings\AppKit\Enums\NSWindowOrderingMode;
use Jovian\Bindings\AppKit\Enums\NSWindowSharingType;
use Jovian\Bindings\AppKit\Enums\NSWindowTabbingMode;
use Jovian\Bindings\AppKit\Enums\NSWindowTitleVisibility;
use Jovian\Bindings\AppKit\Enums\NSWindowToolbarStyle;
use Jovian\Bindings\AppKit\Enums\NSWindowUserTabbingPreference;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class NSWindow extends NSResponder
{
    public static function frameRectForContentRectStyleMask(NSRect $cRect, int $style): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::frameRectForContentRectStyleMask(...[...$cRect->toArgs(), $style]));
    }

    public static function contentRectForFrameRectStyleMask(NSRect $fRect, int $style): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::contentRectForFrameRectStyleMask(...[...$fRect->toArgs(), $style]));
    }

    public static function minFrameWidthWithTitleStyleMask(string $title, int $style): float
    {
        return ExtNSWindow::minFrameWidthWithTitleStyleMask($title, $style);
    }

    public static function defaultDepthLimit(): NSWindowDepth|int
    {
        return ExtNSWindow::defaultDepthLimit();
    }

    public function frameRectForContentRect(NSRect $contentRect): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::frameRectForContentRect(...[$this->handle, ...$contentRect->toArgs()]));
    }

    public function contentRectForFrameRect(NSRect $frameRect): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::contentRectForFrameRect(...[$this->handle, ...$frameRect->toArgs()]));
    }

    public static function initWithContentRectStyleMaskBackingDefer(NSRect $contentRect, int $style, NSBackingStoreType|int $backingStoreType, bool $flag): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::initWithContentRectStyleMaskBackingDefer(...[...$contentRect->toArgs(), $style, $backingStoreType instanceof \BackedEnum ? $backingStoreType->value : $backingStoreType, $flag]));
    }

    public static function initWithContentRectStyleMaskBackingDeferScreen(NSRect $contentRect, int $style, NSBackingStoreType|int $backingStoreType, bool $flag, int $screen): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::initWithContentRectStyleMaskBackingDeferScreen(...[...$contentRect->toArgs(), $style, $backingStoreType instanceof \BackedEnum ? $backingStoreType->value : $backingStoreType, $flag, $screen]));
    }

    public function title(): ?string
    {
        return ExtNSWindow::title($this->handle);
    }

    public function setTitle(string $title): static
    {
        ExtNSWindow::setTitle($this->handle, $title);

        return $this;
    }

    public function subtitle(): ?string
    {
        return ExtNSWindow::subtitle($this->handle);
    }

    public function setSubtitle(string $subtitle): static
    {
        ExtNSWindow::setSubtitle($this->handle, $subtitle);

        return $this;
    }

    public function titleVisibility(): NSWindowTitleVisibility|int
    {
        return ExtNSWindow::titleVisibility($this->handle);
    }

    public function setTitleVisibility(NSWindowTitleVisibility|int $titleVisibility): static
    {
        ExtNSWindow::setTitleVisibility($this->handle, $titleVisibility instanceof \BackedEnum ? $titleVisibility->value : $titleVisibility);

        return $this;
    }

    public function titlebarAppearsTransparent(): bool
    {
        return ExtNSWindow::titlebarAppearsTransparent($this->handle);
    }

    public function setTitlebarAppearsTransparent(bool $titlebarAppearsTransparent): static
    {
        ExtNSWindow::setTitlebarAppearsTransparent($this->handle, $titlebarAppearsTransparent);

        return $this;
    }

    public function toolbarStyle(): NSWindowToolbarStyle|int
    {
        return ExtNSWindow::toolbarStyle($this->handle);
    }

    public function setToolbarStyle(NSWindowToolbarStyle|int $toolbarStyle): static
    {
        ExtNSWindow::setToolbarStyle($this->handle, $toolbarStyle instanceof \BackedEnum ? $toolbarStyle->value : $toolbarStyle);

        return $this;
    }

    public function contentLayoutRect(): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::contentLayoutRect($this->handle));
    }

    public function contentLayoutGuide(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::contentLayoutGuide($this->handle));
    }

    public function titlebarAccessoryViewControllers(): array
    {
        return ExtNSWindow::titlebarAccessoryViewControllers($this->handle);
    }

    public function setTitlebarAccessoryViewControllers(array $titlebarAccessoryViewControllers): static
    {
        ExtNSWindow::setTitlebarAccessoryViewControllers($this->handle, $titlebarAccessoryViewControllers);

        return $this;
    }

    public function addTitlebarAccessoryViewController(int $childViewController): static
    {
        ExtNSWindow::addTitlebarAccessoryViewController($this->handle, $childViewController);

        return $this;
    }

    public function insertTitlebarAccessoryViewControllerAtIndex(int $childViewController, int $index): static
    {
        ExtNSWindow::insertTitlebarAccessoryViewControllerAtIndex($this->handle, $childViewController, $index);

        return $this;
    }

    public function removeTitlebarAccessoryViewControllerAtIndex(int $index): static
    {
        ExtNSWindow::removeTitlebarAccessoryViewControllerAtIndex($this->handle, $index);

        return $this;
    }

    public function representedURL(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::representedURL($this->handle));
    }

    public function setRepresentedURL(int $representedURL): static
    {
        ExtNSWindow::setRepresentedURL($this->handle, $representedURL);

        return $this;
    }

    public function representedFilename(): ?string
    {
        return ExtNSWindow::representedFilename($this->handle);
    }

    public function setRepresentedFilename(string $representedFilename): static
    {
        ExtNSWindow::setRepresentedFilename($this->handle, $representedFilename);

        return $this;
    }

    public function setTitleWithRepresentedFilename(string $filename): static
    {
        ExtNSWindow::setTitleWithRepresentedFilename($this->handle, $filename);

        return $this;
    }

    public function isExcludedFromWindowsMenu(): bool
    {
        return ExtNSWindow::isExcludedFromWindowsMenu($this->handle);
    }

    public function setExcludedFromWindowsMenu(bool $excludedFromWindowsMenu): static
    {
        ExtNSWindow::setExcludedFromWindowsMenu($this->handle, $excludedFromWindowsMenu);

        return $this;
    }

    public function contentView(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::contentView($this->handle));
    }

    public function setContentView(int $contentView): static
    {
        ExtNSWindow::setContentView($this->handle, $contentView);

        return $this;
    }

    public function delegate(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::delegate($this->handle));
    }

    public function setDelegate(int $delegate): static
    {
        ExtNSWindow::setDelegate($this->handle, $delegate);

        return $this;
    }

    public function windowNumber(): int
    {
        return ExtNSWindow::windowNumber($this->handle);
    }

    public function styleMask(): int
    {
        return ExtNSWindow::styleMask($this->handle);
    }

    public function setStyleMask(int $styleMask): static
    {
        ExtNSWindow::setStyleMask($this->handle, $styleMask);

        return $this;
    }

    public function fieldEditorForObject(bool $createFlag, int $object): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::fieldEditorForObject($this->handle, $createFlag, $object));
    }

    public function endEditingFor(int $object): static
    {
        ExtNSWindow::endEditingFor($this->handle, $object);

        return $this;
    }

    public function constrainFrameRectToScreen(NSRect $frameRect, int $screen): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::constrainFrameRectToScreen(...[$this->handle, ...$frameRect->toArgs(), $screen]));
    }

    public function setFrameDisplay(NSRect $frameRect, bool $flag): static
    {
        ExtNSWindow::setFrameDisplay(...[$this->handle, ...$frameRect->toArgs(), $flag]);

        return $this;
    }

    public function setContentSize(NSSize $size): static
    {
        ExtNSWindow::setContentSize(...[$this->handle, ...$size->toArgs()]);

        return $this;
    }

    public function setFrameOrigin(NSPoint $point): static
    {
        ExtNSWindow::setFrameOrigin(...[$this->handle, ...$point->toArgs()]);

        return $this;
    }

    public function setFrameTopLeftPoint(NSPoint $point): static
    {
        ExtNSWindow::setFrameTopLeftPoint(...[$this->handle, ...$point->toArgs()]);

        return $this;
    }

    public function cascadeTopLeftFromPoint(NSPoint $topLeftPoint): NSPoint
    {
        return NSPoint::fromArray(ExtNSWindow::cascadeTopLeftFromPoint(...[$this->handle, ...$topLeftPoint->toArgs()]));
    }

    public function cascadingReferenceFrame(): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::cascadingReferenceFrame($this->handle));
    }

    public function frame(): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::frame($this->handle));
    }

    public function animationResizeTime(NSRect $newFrame): float
    {
        return ExtNSWindow::animationResizeTime(...[$this->handle, ...$newFrame->toArgs()]);
    }

    public function setFrameDisplayAnimate(NSRect $frameRect, bool $displayFlag, bool $animateFlag): static
    {
        ExtNSWindow::setFrameDisplayAnimate(...[$this->handle, ...$frameRect->toArgs(), $displayFlag, $animateFlag]);

        return $this;
    }

    public function inLiveResize(): bool
    {
        return ExtNSWindow::inLiveResize($this->handle);
    }

    public function resizeIncrements(): NSSize
    {
        return NSSize::fromArray(ExtNSWindow::resizeIncrements($this->handle));
    }

    public function setResizeIncrements(NSSize $resizeIncrements): static
    {
        ExtNSWindow::setResizeIncrements(...[$this->handle, ...$resizeIncrements->toArgs()]);

        return $this;
    }

    public function aspectRatio(): NSSize
    {
        return NSSize::fromArray(ExtNSWindow::aspectRatio($this->handle));
    }

    public function setAspectRatio(NSSize $aspectRatio): static
    {
        ExtNSWindow::setAspectRatio(...[$this->handle, ...$aspectRatio->toArgs()]);

        return $this;
    }

    public function contentResizeIncrements(): NSSize
    {
        return NSSize::fromArray(ExtNSWindow::contentResizeIncrements($this->handle));
    }

    public function setContentResizeIncrements(NSSize $contentResizeIncrements): static
    {
        ExtNSWindow::setContentResizeIncrements(...[$this->handle, ...$contentResizeIncrements->toArgs()]);

        return $this;
    }

    public function contentAspectRatio(): NSSize
    {
        return NSSize::fromArray(ExtNSWindow::contentAspectRatio($this->handle));
    }

    public function setContentAspectRatio(NSSize $contentAspectRatio): static
    {
        ExtNSWindow::setContentAspectRatio(...[$this->handle, ...$contentAspectRatio->toArgs()]);

        return $this;
    }

    public function viewsNeedDisplay(): bool
    {
        return ExtNSWindow::viewsNeedDisplay($this->handle);
    }

    public function setViewsNeedDisplay(bool $viewsNeedDisplay): static
    {
        ExtNSWindow::setViewsNeedDisplay($this->handle, $viewsNeedDisplay);

        return $this;
    }

    public function displayIfNeeded(): static
    {
        ExtNSWindow::displayIfNeeded($this->handle);

        return $this;
    }

    public function display(): static
    {
        ExtNSWindow::display($this->handle);

        return $this;
    }

    public function preservesContentDuringLiveResize(): bool
    {
        return ExtNSWindow::preservesContentDuringLiveResize($this->handle);
    }

    public function setPreservesContentDuringLiveResize(bool $preservesContentDuringLiveResize): static
    {
        ExtNSWindow::setPreservesContentDuringLiveResize($this->handle, $preservesContentDuringLiveResize);

        return $this;
    }

    public function update(): static
    {
        ExtNSWindow::update($this->handle);

        return $this;
    }

    public function makeFirstResponder(int $responder): bool
    {
        return ExtNSWindow::makeFirstResponder($this->handle, $responder);
    }

    public function firstResponder(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::firstResponder($this->handle));
    }

    public function resizeFlags(): int
    {
        return ExtNSWindow::resizeFlags($this->handle);
    }

    public function close(): static
    {
        ExtNSWindow::close($this->handle);

        return $this;
    }

    public function isReleasedWhenClosed(): bool
    {
        return ExtNSWindow::isReleasedWhenClosed($this->handle);
    }

    public function setReleasedWhenClosed(bool $releasedWhenClosed): static
    {
        ExtNSWindow::setReleasedWhenClosed($this->handle, $releasedWhenClosed);

        return $this;
    }

    public function miniaturize(int $sender): static
    {
        ExtNSWindow::miniaturize($this->handle, $sender);

        return $this;
    }

    public function deminiaturize(int $sender): static
    {
        ExtNSWindow::deminiaturize($this->handle, $sender);

        return $this;
    }

    public function isZoomed(): bool
    {
        return ExtNSWindow::isZoomed($this->handle);
    }

    public function zoom(int $sender): static
    {
        ExtNSWindow::zoom($this->handle, $sender);

        return $this;
    }

    public function isMiniaturized(): bool
    {
        return ExtNSWindow::isMiniaturized($this->handle);
    }

    public function tryToPerformWith(string $action, int $object): bool
    {
        return ExtNSWindow::tryToPerformWith($this->handle, $action, $object);
    }

    public function validRequestorForSendTypeReturnType(string $sendType, string $returnType): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::validRequestorForSendTypeReturnType($this->handle, $sendType, $returnType));
    }

    public function backgroundColor(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::backgroundColor($this->handle));
    }

    public function setBackgroundColor(int $backgroundColor): static
    {
        ExtNSWindow::setBackgroundColor($this->handle, $backgroundColor);

        return $this;
    }

    public function setContentBorderThicknessForEdge(float $thickness, NSRectEdge|int $edge): static
    {
        ExtNSWindow::setContentBorderThicknessForEdge($this->handle, $thickness, $edge instanceof \BackedEnum ? $edge->value : $edge);

        return $this;
    }

    public function contentBorderThicknessForEdge(NSRectEdge|int $edge): float
    {
        return ExtNSWindow::contentBorderThicknessForEdge($this->handle, $edge instanceof \BackedEnum ? $edge->value : $edge);
    }

    public function setAutorecalculatesContentBorderThicknessForEdge(bool $flag, NSRectEdge|int $edge): static
    {
        ExtNSWindow::setAutorecalculatesContentBorderThicknessForEdge($this->handle, $flag, $edge instanceof \BackedEnum ? $edge->value : $edge);

        return $this;
    }

    public function autorecalculatesContentBorderThicknessForEdge(NSRectEdge|int $edge): bool
    {
        return ExtNSWindow::autorecalculatesContentBorderThicknessForEdge($this->handle, $edge instanceof \BackedEnum ? $edge->value : $edge);
    }

    public function isMovable(): bool
    {
        return ExtNSWindow::isMovable($this->handle);
    }

    public function setMovable(bool $movable): static
    {
        ExtNSWindow::setMovable($this->handle, $movable);

        return $this;
    }

    public function isMovableByWindowBackground(): bool
    {
        return ExtNSWindow::isMovableByWindowBackground($this->handle);
    }

    public function setMovableByWindowBackground(bool $movableByWindowBackground): static
    {
        ExtNSWindow::setMovableByWindowBackground($this->handle, $movableByWindowBackground);

        return $this;
    }

    public function hidesOnDeactivate(): bool
    {
        return ExtNSWindow::hidesOnDeactivate($this->handle);
    }

    public function setHidesOnDeactivate(bool $hidesOnDeactivate): static
    {
        ExtNSWindow::setHidesOnDeactivate($this->handle, $hidesOnDeactivate);

        return $this;
    }

    public function canHide(): bool
    {
        return ExtNSWindow::canHide($this->handle);
    }

    public function setCanHide(bool $canHide): static
    {
        ExtNSWindow::setCanHide($this->handle, $canHide);

        return $this;
    }

    public function center(): static
    {
        ExtNSWindow::center($this->handle);

        return $this;
    }

    public function makeKeyAndOrderFront(int $sender): static
    {
        ExtNSWindow::makeKeyAndOrderFront($this->handle, $sender);

        return $this;
    }

    public function orderFront(int $sender): static
    {
        ExtNSWindow::orderFront($this->handle, $sender);

        return $this;
    }

    public function orderBack(int $sender): static
    {
        ExtNSWindow::orderBack($this->handle, $sender);

        return $this;
    }

    public function orderOut(int $sender): static
    {
        ExtNSWindow::orderOut($this->handle, $sender);

        return $this;
    }

    public function orderWindowRelativeTo(NSWindowOrderingMode|int $place, int $otherWin): static
    {
        ExtNSWindow::orderWindowRelativeTo($this->handle, $place instanceof \BackedEnum ? $place->value : $place, $otherWin);

        return $this;
    }

    public function orderFrontRegardless(): static
    {
        ExtNSWindow::orderFrontRegardless($this->handle);

        return $this;
    }

    public function miniwindowImage(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::miniwindowImage($this->handle));
    }

    public function setMiniwindowImage(int $miniwindowImage): static
    {
        ExtNSWindow::setMiniwindowImage($this->handle, $miniwindowImage);

        return $this;
    }

    public function miniwindowTitle(): mixed
    {
        return ExtNSWindow::miniwindowTitle($this->handle);
    }

    public function setMiniwindowTitle(string $miniwindowTitle): static
    {
        ExtNSWindow::setMiniwindowTitle($this->handle, $miniwindowTitle);

        return $this;
    }

    public function dockTile(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::dockTile($this->handle));
    }

    public function isDocumentEdited(): bool
    {
        return ExtNSWindow::isDocumentEdited($this->handle);
    }

    public function setDocumentEdited(bool $documentEdited): static
    {
        ExtNSWindow::setDocumentEdited($this->handle, $documentEdited);

        return $this;
    }

    public function isVisible(): bool
    {
        return ExtNSWindow::isVisible($this->handle);
    }

    public function isKeyWindow(): bool
    {
        return ExtNSWindow::isKeyWindow($this->handle);
    }

    public function isMainWindow(): bool
    {
        return ExtNSWindow::isMainWindow($this->handle);
    }

    public function canBecomeKeyWindow(): bool
    {
        return ExtNSWindow::canBecomeKeyWindow($this->handle);
    }

    public function canBecomeMainWindow(): bool
    {
        return ExtNSWindow::canBecomeMainWindow($this->handle);
    }

    public function makeKeyWindow(): static
    {
        ExtNSWindow::makeKeyWindow($this->handle);

        return $this;
    }

    public function makeMainWindow(): static
    {
        ExtNSWindow::makeMainWindow($this->handle);

        return $this;
    }

    public function becomeKeyWindow(): static
    {
        ExtNSWindow::becomeKeyWindow($this->handle);

        return $this;
    }

    public function resignKeyWindow(): static
    {
        ExtNSWindow::resignKeyWindow($this->handle);

        return $this;
    }

    public function becomeMainWindow(): static
    {
        ExtNSWindow::becomeMainWindow($this->handle);

        return $this;
    }

    public function resignMainWindow(): static
    {
        ExtNSWindow::resignMainWindow($this->handle);

        return $this;
    }

    public function worksWhenModal(): bool
    {
        return ExtNSWindow::worksWhenModal($this->handle);
    }

    public function preventsApplicationTerminationWhenModal(): bool
    {
        return ExtNSWindow::preventsApplicationTerminationWhenModal($this->handle);
    }

    public function setPreventsApplicationTerminationWhenModal(bool $preventsApplicationTerminationWhenModal): static
    {
        ExtNSWindow::setPreventsApplicationTerminationWhenModal($this->handle, $preventsApplicationTerminationWhenModal);

        return $this;
    }

    public function convertRectToScreen(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::convertRectToScreen(...[$this->handle, ...$rect->toArgs()]));
    }

    public function convertRectFromScreen(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::convertRectFromScreen(...[$this->handle, ...$rect->toArgs()]));
    }

    public function convertPointToScreen(NSPoint $point): NSPoint
    {
        return NSPoint::fromArray(ExtNSWindow::convertPointToScreen(...[$this->handle, ...$point->toArgs()]));
    }

    public function convertPointFromScreen(NSPoint $point): NSPoint
    {
        return NSPoint::fromArray(ExtNSWindow::convertPointFromScreen(...[$this->handle, ...$point->toArgs()]));
    }

    public function convertRectToBacking(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::convertRectToBacking(...[$this->handle, ...$rect->toArgs()]));
    }

    public function convertRectFromBacking(NSRect $rect): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::convertRectFromBacking(...[$this->handle, ...$rect->toArgs()]));
    }

    public function convertPointToBacking(NSPoint $point): NSPoint
    {
        return NSPoint::fromArray(ExtNSWindow::convertPointToBacking(...[$this->handle, ...$point->toArgs()]));
    }

    public function convertPointFromBacking(NSPoint $point): NSPoint
    {
        return NSPoint::fromArray(ExtNSWindow::convertPointFromBacking(...[$this->handle, ...$point->toArgs()]));
    }

    public function backingAlignedRectOptions(NSRect $rect, int $options): NSRect
    {
        return NSRect::fromArray(ExtNSWindow::backingAlignedRectOptions(...[$this->handle, ...$rect->toArgs(), $options]));
    }

    public function backingScaleFactor(): float
    {
        return ExtNSWindow::backingScaleFactor($this->handle);
    }

    public function performClose(int $sender): static
    {
        ExtNSWindow::performClose($this->handle, $sender);

        return $this;
    }

    public function performMiniaturize(int $sender): static
    {
        ExtNSWindow::performMiniaturize($this->handle, $sender);

        return $this;
    }

    public function performZoom(int $sender): static
    {
        ExtNSWindow::performZoom($this->handle, $sender);

        return $this;
    }

    public function print(int $sender): static
    {
        ExtNSWindow::print($this->handle, $sender);

        return $this;
    }

    public function allowsToolTipsWhenApplicationIsInactive(): bool
    {
        return ExtNSWindow::allowsToolTipsWhenApplicationIsInactive($this->handle);
    }

    public function setAllowsToolTipsWhenApplicationIsInactive(bool $allowsToolTipsWhenApplicationIsInactive): static
    {
        ExtNSWindow::setAllowsToolTipsWhenApplicationIsInactive($this->handle, $allowsToolTipsWhenApplicationIsInactive);

        return $this;
    }

    public function backingType(): NSBackingStoreType|int
    {
        return ExtNSWindow::backingType($this->handle);
    }

    public function setBackingType(NSBackingStoreType|int $backingType): static
    {
        ExtNSWindow::setBackingType($this->handle, $backingType instanceof \BackedEnum ? $backingType->value : $backingType);

        return $this;
    }

    public function level(): int
    {
        return ExtNSWindow::level($this->handle);
    }

    public function setLevel(int $level): static
    {
        ExtNSWindow::setLevel($this->handle, $level);

        return $this;
    }

    public function depthLimit(): NSWindowDepth|int
    {
        return ExtNSWindow::depthLimit($this->handle);
    }

    public function setDepthLimit(NSWindowDepth|int $depthLimit): static
    {
        ExtNSWindow::setDepthLimit($this->handle, $depthLimit instanceof \BackedEnum ? $depthLimit->value : $depthLimit);

        return $this;
    }

    public function setDynamicDepthLimit(bool $flag): static
    {
        ExtNSWindow::setDynamicDepthLimit($this->handle, $flag);

        return $this;
    }

    public function hasDynamicDepthLimit(): bool
    {
        return ExtNSWindow::hasDynamicDepthLimit($this->handle);
    }

    public function screen(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::screen($this->handle));
    }

    public function deepestScreen(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::deepestScreen($this->handle));
    }

    public function hasShadow(): bool
    {
        return ExtNSWindow::hasShadow($this->handle);
    }

    public function setHasShadow(bool $hasShadow): static
    {
        ExtNSWindow::setHasShadow($this->handle, $hasShadow);

        return $this;
    }

    public function invalidateShadow(): static
    {
        ExtNSWindow::invalidateShadow($this->handle);

        return $this;
    }

    public function alphaValue(): float
    {
        return ExtNSWindow::alphaValue($this->handle);
    }

    public function setAlphaValue(float $alphaValue): static
    {
        ExtNSWindow::setAlphaValue($this->handle, $alphaValue);

        return $this;
    }

    public function isOpaque(): bool
    {
        return ExtNSWindow::isOpaque($this->handle);
    }

    public function setOpaque(bool $opaque): static
    {
        ExtNSWindow::setOpaque($this->handle, $opaque);

        return $this;
    }

    public function sharingType(): NSWindowSharingType|int
    {
        return ExtNSWindow::sharingType($this->handle);
    }

    public function setSharingType(NSWindowSharingType|int $sharingType): static
    {
        ExtNSWindow::setSharingType($this->handle, $sharingType instanceof \BackedEnum ? $sharingType->value : $sharingType);

        return $this;
    }

    public function allowsConcurrentViewDrawing(): bool
    {
        return ExtNSWindow::allowsConcurrentViewDrawing($this->handle);
    }

    public function setAllowsConcurrentViewDrawing(bool $allowsConcurrentViewDrawing): static
    {
        ExtNSWindow::setAllowsConcurrentViewDrawing($this->handle, $allowsConcurrentViewDrawing);

        return $this;
    }

    public function displaysWhenScreenProfileChanges(): bool
    {
        return ExtNSWindow::displaysWhenScreenProfileChanges($this->handle);
    }

    public function setDisplaysWhenScreenProfileChanges(bool $displaysWhenScreenProfileChanges): static
    {
        ExtNSWindow::setDisplaysWhenScreenProfileChanges($this->handle, $displaysWhenScreenProfileChanges);

        return $this;
    }

    public function canBecomeVisibleWithoutLogin(): bool
    {
        return ExtNSWindow::canBecomeVisibleWithoutLogin($this->handle);
    }

    public function setCanBecomeVisibleWithoutLogin(bool $canBecomeVisibleWithoutLogin): static
    {
        ExtNSWindow::setCanBecomeVisibleWithoutLogin($this->handle, $canBecomeVisibleWithoutLogin);

        return $this;
    }

    public function collectionBehavior(): int
    {
        return ExtNSWindow::collectionBehavior($this->handle);
    }

    public function setCollectionBehavior(int $collectionBehavior): static
    {
        ExtNSWindow::setCollectionBehavior($this->handle, $collectionBehavior);

        return $this;
    }

    public function animationBehavior(): NSWindowAnimationBehavior|int
    {
        return ExtNSWindow::animationBehavior($this->handle);
    }

    public function setAnimationBehavior(NSWindowAnimationBehavior|int $animationBehavior): static
    {
        ExtNSWindow::setAnimationBehavior($this->handle, $animationBehavior instanceof \BackedEnum ? $animationBehavior->value : $animationBehavior);

        return $this;
    }

    public function isOnActiveSpace(): bool
    {
        return ExtNSWindow::isOnActiveSpace($this->handle);
    }

    public function toggleFullScreen(int $sender): static
    {
        ExtNSWindow::toggleFullScreen($this->handle, $sender);

        return $this;
    }

    public function stringWithSavedFrame(): ?string
    {
        return ExtNSWindow::stringWithSavedFrame($this->handle);
    }

    public function setFrameFromString(string $string): static
    {
        ExtNSWindow::setFrameFromString($this->handle, $string);

        return $this;
    }

    public function saveFrameUsingName(string $name): static
    {
        ExtNSWindow::saveFrameUsingName($this->handle, $name);

        return $this;
    }

    public function setFrameUsingNameForce(string $name, bool $force): bool
    {
        return ExtNSWindow::setFrameUsingNameForce($this->handle, $name, $force);
    }

    public function setFrameUsingName(string $name): bool
    {
        return ExtNSWindow::setFrameUsingName($this->handle, $name);
    }

    public function setFrameAutosaveName(string $name): bool
    {
        return ExtNSWindow::setFrameAutosaveName($this->handle, $name);
    }

    public function frameAutosaveName(): ?string
    {
        return ExtNSWindow::frameAutosaveName($this->handle);
    }

    public static function removeFrameUsingName(string $name): void
    {
        ExtNSWindow::removeFrameUsingName($name);
    }

    public function minSize(): NSSize
    {
        return NSSize::fromArray(ExtNSWindow::minSize($this->handle));
    }

    public function setMinSize(NSSize $minSize): static
    {
        ExtNSWindow::setMinSize(...[$this->handle, ...$minSize->toArgs()]);

        return $this;
    }

    public function maxSize(): NSSize
    {
        return NSSize::fromArray(ExtNSWindow::maxSize($this->handle));
    }

    public function setMaxSize(NSSize $maxSize): static
    {
        ExtNSWindow::setMaxSize(...[$this->handle, ...$maxSize->toArgs()]);

        return $this;
    }

    public function contentMinSize(): NSSize
    {
        return NSSize::fromArray(ExtNSWindow::contentMinSize($this->handle));
    }

    public function setContentMinSize(NSSize $contentMinSize): static
    {
        ExtNSWindow::setContentMinSize(...[$this->handle, ...$contentMinSize->toArgs()]);

        return $this;
    }

    public function contentMaxSize(): NSSize
    {
        return NSSize::fromArray(ExtNSWindow::contentMaxSize($this->handle));
    }

    public function setContentMaxSize(NSSize $contentMaxSize): static
    {
        ExtNSWindow::setContentMaxSize(...[$this->handle, ...$contentMaxSize->toArgs()]);

        return $this;
    }

    public function minFullScreenContentSize(): NSSize
    {
        return NSSize::fromArray(ExtNSWindow::minFullScreenContentSize($this->handle));
    }

    public function setMinFullScreenContentSize(NSSize $minFullScreenContentSize): static
    {
        ExtNSWindow::setMinFullScreenContentSize(...[$this->handle, ...$minFullScreenContentSize->toArgs()]);

        return $this;
    }

    public function maxFullScreenContentSize(): NSSize
    {
        return NSSize::fromArray(ExtNSWindow::maxFullScreenContentSize($this->handle));
    }

    public function setMaxFullScreenContentSize(NSSize $maxFullScreenContentSize): static
    {
        ExtNSWindow::setMaxFullScreenContentSize(...[$this->handle, ...$maxFullScreenContentSize->toArgs()]);

        return $this;
    }

    public function deviceDescription(): int
    {
        return ExtNSWindow::deviceDescription($this->handle);
    }

    public function windowController(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::windowController($this->handle));
    }

    public function setWindowController(int $windowController): static
    {
        ExtNSWindow::setWindowController($this->handle, $windowController);

        return $this;
    }

    public function endSheet(int $sheetWindow): static
    {
        ExtNSWindow::endSheet($this->handle, $sheetWindow);

        return $this;
    }

    public function endSheetReturnCode(int $sheetWindow, int $returnCode): static
    {
        ExtNSWindow::endSheetReturnCode($this->handle, $sheetWindow, $returnCode);

        return $this;
    }

    public function sheets(): array
    {
        return ExtNSWindow::sheets($this->handle);
    }

    public function attachedSheet(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::attachedSheet($this->handle));
    }

    public function isSheet(): bool
    {
        return ExtNSWindow::isSheet($this->handle);
    }

    public function sheetParent(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::sheetParent($this->handle));
    }

    public static function standardWindowButtonForStyleMask(NSWindowButton|int $b, int $styleMask): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::standardWindowButtonForStyleMask($b instanceof \BackedEnum ? $b->value : $b, $styleMask));
    }

    public function standardWindowButton(NSWindowButton|int $b): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::standardWindowButton($this->handle, $b instanceof \BackedEnum ? $b->value : $b));
    }

    public function addChildWindowOrdered(int $childWin, NSWindowOrderingMode|int $place): static
    {
        ExtNSWindow::addChildWindowOrdered($this->handle, $childWin, $place instanceof \BackedEnum ? $place->value : $place);

        return $this;
    }

    public function removeChildWindow(int $childWin): static
    {
        ExtNSWindow::removeChildWindow($this->handle, $childWin);

        return $this;
    }

    public function childWindows(): array
    {
        return ExtNSWindow::childWindows($this->handle);
    }

    public function parentWindow(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::parentWindow($this->handle));
    }

    public function setParentWindow(int $parentWindow): static
    {
        ExtNSWindow::setParentWindow($this->handle, $parentWindow);

        return $this;
    }

    public function appearanceSource(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::appearanceSource($this->handle));
    }

    public function setAppearanceSource(int $appearanceSource): static
    {
        ExtNSWindow::setAppearanceSource($this->handle, $appearanceSource);

        return $this;
    }

    public function colorSpace(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::colorSpace($this->handle));
    }

    public function setColorSpace(int $colorSpace): static
    {
        ExtNSWindow::setColorSpace($this->handle, $colorSpace);

        return $this;
    }

    public function canRepresentDisplayGamut(NSDisplayGamut|int $displayGamut): bool
    {
        return ExtNSWindow::canRepresentDisplayGamut($this->handle, $displayGamut instanceof \BackedEnum ? $displayGamut->value : $displayGamut);
    }

    public static function windowNumbersWithOptions(int $options): array
    {
        return ExtNSWindow::windowNumbersWithOptions($options);
    }

    public static function windowNumberAtPointBelowWindowWithWindowNumber(NSPoint $point, int $windowNumber): int
    {
        return ExtNSWindow::windowNumberAtPointBelowWindowWithWindowNumber(...[...$point->toArgs(), $windowNumber]);
    }

    public function occlusionState(): int
    {
        return ExtNSWindow::occlusionState($this->handle);
    }

    public function titlebarSeparatorStyle(): NSTitlebarSeparatorStyle|int
    {
        return ExtNSWindow::titlebarSeparatorStyle($this->handle);
    }

    public function setTitlebarSeparatorStyle(NSTitlebarSeparatorStyle|int $titlebarSeparatorStyle): static
    {
        ExtNSWindow::setTitlebarSeparatorStyle($this->handle, $titlebarSeparatorStyle instanceof \BackedEnum ? $titlebarSeparatorStyle->value : $titlebarSeparatorStyle);

        return $this;
    }

    public function contentViewController(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::contentViewController($this->handle));
    }

    public function setContentViewController(int $contentViewController): static
    {
        ExtNSWindow::setContentViewController($this->handle, $contentViewController);

        return $this;
    }

    public static function windowWithContentViewController(int $contentViewController): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::windowWithContentViewController($contentViewController));
    }

    public function performWindowDragWithEvent(int $event): static
    {
        ExtNSWindow::performWindowDragWithEvent($this->handle, $event);

        return $this;
    }

    public function initialFirstResponder(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::initialFirstResponder($this->handle));
    }

    public function setInitialFirstResponder(int $initialFirstResponder): static
    {
        ExtNSWindow::setInitialFirstResponder($this->handle, $initialFirstResponder);

        return $this;
    }

    public function selectNextKeyView(int $sender): static
    {
        ExtNSWindow::selectNextKeyView($this->handle, $sender);

        return $this;
    }

    public function selectPreviousKeyView(int $sender): static
    {
        ExtNSWindow::selectPreviousKeyView($this->handle, $sender);

        return $this;
    }

    public function selectKeyViewFollowingView(int $view): static
    {
        ExtNSWindow::selectKeyViewFollowingView($this->handle, $view);

        return $this;
    }

    public function selectKeyViewPrecedingView(int $view): static
    {
        ExtNSWindow::selectKeyViewPrecedingView($this->handle, $view);

        return $this;
    }

    public function keyViewSelectionDirection(): NSSelectionDirection|int
    {
        return ExtNSWindow::keyViewSelectionDirection($this->handle);
    }

    public function defaultButtonCell(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::defaultButtonCell($this->handle));
    }

    public function setDefaultButtonCell(int $defaultButtonCell): static
    {
        ExtNSWindow::setDefaultButtonCell($this->handle, $defaultButtonCell);

        return $this;
    }

    public function disableKeyEquivalentForDefaultButtonCell(): static
    {
        ExtNSWindow::disableKeyEquivalentForDefaultButtonCell($this->handle);

        return $this;
    }

    public function enableKeyEquivalentForDefaultButtonCell(): static
    {
        ExtNSWindow::enableKeyEquivalentForDefaultButtonCell($this->handle);

        return $this;
    }

    public function autorecalculatesKeyViewLoop(): bool
    {
        return ExtNSWindow::autorecalculatesKeyViewLoop($this->handle);
    }

    public function setAutorecalculatesKeyViewLoop(bool $autorecalculatesKeyViewLoop): static
    {
        ExtNSWindow::setAutorecalculatesKeyViewLoop($this->handle, $autorecalculatesKeyViewLoop);

        return $this;
    }

    public function recalculateKeyViewLoop(): static
    {
        ExtNSWindow::recalculateKeyViewLoop($this->handle);

        return $this;
    }

    public function toolbar(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::toolbar($this->handle));
    }

    public function setToolbar(int $toolbar): static
    {
        ExtNSWindow::setToolbar($this->handle, $toolbar);

        return $this;
    }

    public function toggleToolbarShown(int $sender): static
    {
        ExtNSWindow::toggleToolbarShown($this->handle, $sender);

        return $this;
    }

    public function runToolbarCustomizationPalette(int $sender): static
    {
        ExtNSWindow::runToolbarCustomizationPalette($this->handle, $sender);

        return $this;
    }

    public static function allowsAutomaticWindowTabbing(): bool
    {
        return ExtNSWindow::allowsAutomaticWindowTabbing();
    }

    public static function setAllowsAutomaticWindowTabbing(bool $allowsAutomaticWindowTabbing): void
    {
        ExtNSWindow::setAllowsAutomaticWindowTabbing($allowsAutomaticWindowTabbing);
    }

    public static function userTabbingPreference(): NSWindowUserTabbingPreference|int
    {
        return ExtNSWindow::userTabbingPreference();
    }

    public function tabbingMode(): NSWindowTabbingMode|int
    {
        return ExtNSWindow::tabbingMode($this->handle);
    }

    public function setTabbingMode(NSWindowTabbingMode|int $tabbingMode): static
    {
        ExtNSWindow::setTabbingMode($this->handle, $tabbingMode instanceof \BackedEnum ? $tabbingMode->value : $tabbingMode);

        return $this;
    }

    public function tabbingIdentifier(): ?string
    {
        return ExtNSWindow::tabbingIdentifier($this->handle);
    }

    public function setTabbingIdentifier(string $tabbingIdentifier): static
    {
        ExtNSWindow::setTabbingIdentifier($this->handle, $tabbingIdentifier);

        return $this;
    }

    public function selectNextTab(int $sender): static
    {
        ExtNSWindow::selectNextTab($this->handle, $sender);

        return $this;
    }

    public function selectPreviousTab(int $sender): static
    {
        ExtNSWindow::selectPreviousTab($this->handle, $sender);

        return $this;
    }

    public function moveTabToNewWindow(int $sender): static
    {
        ExtNSWindow::moveTabToNewWindow($this->handle, $sender);

        return $this;
    }

    public function mergeAllWindows(int $sender): static
    {
        ExtNSWindow::mergeAllWindows($this->handle, $sender);

        return $this;
    }

    public function toggleTabBar(int $sender): static
    {
        ExtNSWindow::toggleTabBar($this->handle, $sender);

        return $this;
    }

    public function toggleTabOverview(int $sender): static
    {
        ExtNSWindow::toggleTabOverview($this->handle, $sender);

        return $this;
    }

    public function tabbedWindows(): array
    {
        return ExtNSWindow::tabbedWindows($this->handle);
    }

    public function addTabbedWindowOrdered(int $window, NSWindowOrderingMode|int $ordered): static
    {
        ExtNSWindow::addTabbedWindowOrdered($this->handle, $window, $ordered instanceof \BackedEnum ? $ordered->value : $ordered);

        return $this;
    }

    public function tab(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::tab($this->handle));
    }

    public function tabGroup(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::tabGroup($this->handle));
    }

    public function hasActiveWindowSharingSession(): bool
    {
        return ExtNSWindow::hasActiveWindowSharingSession($this->handle);
    }

    public function windowTitlebarLayoutDirection(): NSUserInterfaceLayoutDirection|int
    {
        return ExtNSWindow::windowTitlebarLayoutDirection($this->handle);
    }

    public function nextEventMatchingMask(int $mask): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::nextEventMatchingMask($this->handle, $mask));
    }

    public function nextEventMatchingMaskUntilDateInModeDequeue(int $mask, int $expiration, string $mode, bool $deqFlag): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::nextEventMatchingMaskUntilDateInModeDequeue($this->handle, $mask, $expiration, $mode, $deqFlag));
    }

    public function discardEventsMatchingMaskBeforeEvent(int $mask, int $lastEvent): static
    {
        ExtNSWindow::discardEventsMatchingMaskBeforeEvent($this->handle, $mask, $lastEvent);

        return $this;
    }

    public function postEventAtStart(int $event, bool $flag): static
    {
        ExtNSWindow::postEventAtStart($this->handle, $event, $flag);

        return $this;
    }

    public function sendEvent(int $event): static
    {
        ExtNSWindow::sendEvent($this->handle, $event);

        return $this;
    }

    public function currentEvent(): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::currentEvent($this->handle));
    }

    public function acceptsMouseMovedEvents(): bool
    {
        return ExtNSWindow::acceptsMouseMovedEvents($this->handle);
    }

    public function setAcceptsMouseMovedEvents(bool $acceptsMouseMovedEvents): static
    {
        ExtNSWindow::setAcceptsMouseMovedEvents($this->handle, $acceptsMouseMovedEvents);

        return $this;
    }

    public function ignoresMouseEvents(): bool
    {
        return ExtNSWindow::ignoresMouseEvents($this->handle);
    }

    public function setIgnoresMouseEvents(bool $ignoresMouseEvents): static
    {
        ExtNSWindow::setIgnoresMouseEvents($this->handle, $ignoresMouseEvents);

        return $this;
    }

    public function mouseLocationOutsideOfEventStream(): NSPoint
    {
        return NSPoint::fromArray(ExtNSWindow::mouseLocationOutsideOfEventStream($this->handle));
    }

    public function disableCursorRects(): static
    {
        ExtNSWindow::disableCursorRects($this->handle);

        return $this;
    }

    public function enableCursorRects(): static
    {
        ExtNSWindow::enableCursorRects($this->handle);

        return $this;
    }

    public function discardCursorRects(): static
    {
        ExtNSWindow::discardCursorRects($this->handle);

        return $this;
    }

    public function areCursorRectsEnabled(): bool
    {
        return ExtNSWindow::areCursorRectsEnabled($this->handle);
    }

    public function invalidateCursorRectsForView(int $view): static
    {
        ExtNSWindow::invalidateCursorRectsForView($this->handle, $view);

        return $this;
    }

    public function resetCursorRects(): static
    {
        ExtNSWindow::resetCursorRects($this->handle);

        return $this;
    }

    public function beginDraggingSessionWithItemsEventSource(array $items, int $event, int $source): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::beginDraggingSessionWithItemsEventSource($this->handle, $items, $event, $source));
    }

    public function registerForDraggedTypes(array $newTypes): static
    {
        ExtNSWindow::registerForDraggedTypes($this->handle, $newTypes);

        return $this;
    }

    public function unregisterDraggedTypes(): static
    {
        ExtNSWindow::unregisterDraggedTypes($this->handle);

        return $this;
    }

    public function displayLinkWithTargetSelector(int $target, string $selector): ?ObjCObject
    {
        return ObjCObject::box(ExtNSWindow::displayLinkWithTargetSelector($this->handle, $target, $selector));
    }
}
