<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\GC;

use AppKit\GC\GCControllerDirectionPad\GCControllerDirectionPad as ExtGCControllerDirectionPad;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class GCControllerDirectionPad extends ObjCObject
{
    public function xAxis(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCControllerDirectionPad::xAxis($this->handle));
    }

    public function yAxis(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCControllerDirectionPad::yAxis($this->handle));
    }

    public function up(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCControllerDirectionPad::up($this->handle));
    }

    public function down(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCControllerDirectionPad::down($this->handle));
    }

    public function left(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCControllerDirectionPad::left($this->handle));
    }

    public function right(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCControllerDirectionPad::right($this->handle));
    }
}
