<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\GC;

use AppKit\GC\GCExtendedGamepad\GCExtendedGamepad as ExtGCExtendedGamepad;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class GCExtendedGamepad extends ObjCObject
{
    public function controller(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::controller($this->handle));
    }

    public function dpad(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::dpad($this->handle));
    }

    public function buttonA(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::buttonA($this->handle));
    }

    public function buttonB(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::buttonB($this->handle));
    }

    public function buttonX(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::buttonX($this->handle));
    }

    public function buttonY(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::buttonY($this->handle));
    }

    public function buttonMenu(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::buttonMenu($this->handle));
    }

    public function buttonOptions(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::buttonOptions($this->handle));
    }

    public function buttonHome(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::buttonHome($this->handle));
    }

    public function leftThumbstick(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::leftThumbstick($this->handle));
    }

    public function rightThumbstick(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::rightThumbstick($this->handle));
    }

    public function leftShoulder(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::leftShoulder($this->handle));
    }

    public function rightShoulder(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::rightShoulder($this->handle));
    }

    public function leftTrigger(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::leftTrigger($this->handle));
    }

    public function rightTrigger(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::rightTrigger($this->handle));
    }

    public function leftThumbstickButton(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::leftThumbstickButton($this->handle));
    }

    public function rightThumbstickButton(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCExtendedGamepad::rightThumbstickButton($this->handle));
    }
}
