<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\GC;

use AppKit\GC\GCMicroGamepad\GCMicroGamepad as ExtGCMicroGamepad;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class GCMicroGamepad extends ObjCObject
{
    public function dpad(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCMicroGamepad::dpad($this->handle));
    }

    public function buttonA(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCMicroGamepad::buttonA($this->handle));
    }

    public function buttonX(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCMicroGamepad::buttonX($this->handle));
    }

    public function buttonMenu(): ?ObjCObject
    {
        return ObjCObject::box(ExtGCMicroGamepad::buttonMenu($this->handle));
    }
}
