<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\QuartzCore;

use AppKit\QuartzCore\CALayer\CALayer as ExtCALayer;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class CALayer extends ObjCObject
{
    public static function init(): ?ObjCObject
    {
        return ObjCObject::box(ExtCALayer::init());
    }

    public function backgroundColor(): int
    {
        return ExtCALayer::backgroundColor($this->handle);
    }

    public function setBackgroundColor(int $backgroundColor): static
    {
        ExtCALayer::setBackgroundColor($this->handle, $backgroundColor);

        return $this;
    }

    public function contentsGravity(): ?string
    {
        return ExtCALayer::contentsGravity($this->handle);
    }

    public function setContentsGravity(int $contentsGravity): static
    {
        ExtCALayer::setContentsGravity($this->handle, $contentsGravity);

        return $this;
    }

    public function cornerRadius(): float
    {
        return ExtCALayer::cornerRadius($this->handle);
    }

    public function setCornerRadius(float $cornerRadius): static
    {
        ExtCALayer::setCornerRadius($this->handle, $cornerRadius);

        return $this;
    }

    public function masksToBounds(): bool
    {
        return ExtCALayer::masksToBounds($this->handle);
    }

    public function setMasksToBounds(bool $masksToBounds): static
    {
        ExtCALayer::setMasksToBounds($this->handle, $masksToBounds);

        return $this;
    }
}
