<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum AVPlayerTimeControlStatus: int
{
    case PAUSED = 0;
    case WAITING_TO_PLAY_AT_SPECIFIED_RATE = 1;
    case PLAYING = 2;
}
