<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum AVPlayerStatus: int
{
    case UNKNOWN = 0;
    case READY_TO_PLAY = 1;
    case FAILED = 2;
}
