<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum AVPlayerViewControlsStyle: int
{
    case NONE = 0;
    case INLINE = 1;
    case FLOATING = 2;
    case MINIMAL = 3;
}
