<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSAlertStyle: int
{
    case WARNING = 0;
    case INFORMATIONAL = 1;
    case CRITICAL = 2;
}
