<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSAlignmentOptions: int
{
    case NS_ALIGN_MIN_X_INWARD = 1;
    case NS_ALIGN_MIN_Y_INWARD = 2;
    case NS_ALIGN_MAX_X_INWARD = 4;
    case NS_ALIGN_MAX_Y_INWARD = 8;
    case NS_ALIGN_WIDTH_INWARD = 16;
    case NS_ALIGN_HEIGHT_INWARD = 32;
    case NS_ALIGN_MIN_X_OUTWARD = 256;
    case NS_ALIGN_MIN_Y_OUTWARD = 512;
    case NS_ALIGN_MAX_X_OUTWARD = 1024;
    case NS_ALIGN_MAX_Y_OUTWARD = 2048;
    case NS_ALIGN_WIDTH_OUTWARD = 4096;
    case NS_ALIGN_HEIGHT_OUTWARD = 8192;
    case NS_ALIGN_MIN_X_NEAREST = 65536;
    case NS_ALIGN_MIN_Y_NEAREST = 131072;
    case NS_ALIGN_MAX_X_NEAREST = 262144;
    case NS_ALIGN_MAX_Y_NEAREST = 524288;
    case NS_ALIGN_WIDTH_NEAREST = 1048576;
    case NS_ALIGN_HEIGHT_NEAREST = 2097152;
    case NS_ALIGN_RECT_FLIPPED = -9223372036854775808;
    case NS_ALIGN_ALL_EDGES_INWARD = 15;
    case NS_ALIGN_ALL_EDGES_OUTWARD = 3840;
    case NS_ALIGN_ALL_EDGES_NEAREST = 983040;
}
