<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSApplicationDelegateReply: int
{
    case SUCCESS = 0;
    case CANCEL = 1;
    case FAILURE = 2;
}
