<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSAutoresizingMaskOptions: int
{
    case NS_VIEW_NOT_SIZABLE = 0;
    case NS_VIEW_MIN_X_MARGIN = 1;
    case NS_VIEW_WIDTH_SIZABLE = 2;
    case NS_VIEW_MAX_X_MARGIN = 4;
    case NS_VIEW_MIN_Y_MARGIN = 8;
    case NS_VIEW_HEIGHT_SIZABLE = 16;
    case NS_VIEW_MAX_Y_MARGIN = 32;
}
