<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSBackingStoreType: int
{
    case NS_BACKING_STORE_RETAINED = 0;
    case NS_BACKING_STORE_NONRETAINED = 1;
    case NS_BACKING_STORE_BUFFERED = 2;
}
