<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSBoxType: int
{
    case NS_BOX_PRIMARY = 0;
    case NS_BOX_SEPARATOR = 2;
    case NS_BOX_CUSTOM = 4;
}
