<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSBorderType: int
{
    case NS_NO_BORDER = 0;
    case NS_LINE_BORDER = 1;
    case NS_BEZEL_BORDER = 2;
    case NS_GROOVE_BORDER = 3;
}
