<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSCellHitResult: int
{
    case NS_CELL_HIT_NONE = 0;
    case NS_CELL_HIT_CONTENT_AREA = 1;
    case NS_CELL_HIT_EDITABLE_TEXT_AREA = 2;
    case NS_CELL_HIT_TRACKABLE_AREA = 4;
}
