<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSCellType: int
{
    case NS_NULL_CELL_TYPE = 0;
    case NS_TEXT_CELL_TYPE = 1;
    case NS_IMAGE_CELL_TYPE = 2;
}
