<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSComparisonResult: int
{
    case NS_ORDERED_ASCENDING = -1;
    case NS_ORDERED_SAME = 0;
    case NS_ORDERED_DESCENDING = 1;
}
