<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSControlTint: int
{
    case NS_DEFAULT_CONTROL_TINT = 0;
    case NS_BLUE_CONTROL_TINT = 1;
    case NS_GRAPHITE_CONTROL_TINT = 6;
    case NS_CLEAR_CONTROL_TINT = 7;
}
