<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSColorWellStyle: int
{
    case DEFAULT = 0;
    case MINIMAL = 1;
    case EXPANDED = 2;
}
