<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSColorType: int
{
    case COMPONENT_BASED = 0;
    case PATTERN = 1;
    case CATALOG = 2;
}
