<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSDatePickerStyle: int
{
    case TEXT_FIELD_AND_STEPPER = 0;
    case CLOCK_AND_CALENDAR = 1;
    case TEXT_FIELD = 2;
}
