<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSDatePickerMode: int
{
    case SINGLE = 0;
    case RANGE = 1;
}
