<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSDateFormatterBehavior: int
{
    case DEFAULT = 0;
    case CASE_10_0 = 1000;
    case CASE_10_4 = 1040;
}
