<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSDateFormatterStyle: int
{
    case NS_DATE_FORMATTER_NO_STYLE = 0;
    case NS_DATE_FORMATTER_SHORT_STYLE = 1;
    case NS_DATE_FORMATTER_MEDIUM_STYLE = 2;
    case NS_DATE_FORMATTER_LONG_STYLE = 3;
    case NS_DATE_FORMATTER_FULL_STYLE = 4;
}
