<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSEventPhase: int
{
    case NONE = 0;
    case BEGAN = 1;
    case STATIONARY = 2;
    case CHANGED = 4;
    case ENDED = 8;
    case CANCELLED = 16;
    case MAY_BEGIN = 32;
}
