<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSEventMask: int
{
    case LEFT_MOUSE_DOWN = 2;
    case LEFT_MOUSE_UP = 4;
    case RIGHT_MOUSE_DOWN = 8;
    case RIGHT_MOUSE_UP = 16;
    case MOUSE_MOVED = 32;
    case LEFT_MOUSE_DRAGGED = 64;
    case RIGHT_MOUSE_DRAGGED = 128;
    case MOUSE_ENTERED = 256;
    case MOUSE_EXITED = 512;
    case KEY_DOWN = 1024;
    case KEY_UP = 2048;
    case FLAGS_CHANGED = 4096;
    case APP_KIT_DEFINED = 8192;
    case SYSTEM_DEFINED = 16384;
    case APPLICATION_DEFINED = 32768;
    case PERIODIC = 65536;
    case CURSOR_UPDATE = 131072;
    case SCROLL_WHEEL = 4194304;
    case TABLET_POINT = 8388608;
    case TABLET_PROXIMITY = 16777216;
    case OTHER_MOUSE_DOWN = 33554432;
    case OTHER_MOUSE_UP = 67108864;
    case OTHER_MOUSE_DRAGGED = 134217728;
    case GESTURE = 536870912;
    case MAGNIFY = 1073741824;
    case SWIPE = 2147483648;
    case ROTATE = 262144;
    case BEGIN_GESTURE = 524288;
    case END_GESTURE = 1048576;
    case SMART_MAGNIFY = 4294967296;
    case PRESSURE = 17179869184;
    case DIRECT_TOUCH = 137438953472;
    case CHANGE_MODE = 274877906944;
    case ANY = -1;
}
