<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSEventGestureAxis: int
{
    case NONE = 0;
    case HORIZONTAL = 1;
    case VERTICAL = 2;
}
