<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSFontRenderingMode: int
{
    case NS_FONT_DEFAULT_RENDERING_MODE = 0;
    case NS_FONT_ANTIALIASED_RENDERING_MODE = 1;
    case NS_FONT_INTEGER_ADVANCEMENTS_RENDERING_MODE = 2;
    case NS_FONT_ANTIALIASED_INTEGER_ADVANCEMENTS_RENDERING_MODE = 3;
}
