<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSGlyphProperty: int
{
    case NULL = 1;
    case CONTROL_CHARACTER = 2;
    case ELASTIC = 4;
    case NON_BASE_CHARACTER = 8;
}
