<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSGridRowAlignment: int
{
    case INHERITED = 0;
    case NONE = 1;
    case FIRST_BASELINE = 2;
    case LAST_BASELINE = 3;
}
