<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSImageCacheMode: int
{
    case NS_IMAGE_CACHE_DEFAULT = 0;
    case NS_IMAGE_CACHE_ALWAYS = 1;
    case NS_IMAGE_CACHE_BY_SIZE = 2;
    case NS_IMAGE_CACHE_NEVER = 3;
}
