<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSImageDynamicRange: int
{
    case UNSPECIFIED = -1;
    case STANDARD = 0;
    case CONSTRAINED_HIGH = 1;
    case HIGH = 2;
}
