<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSImageResizingMode: int
{
    case STRETCH = 1;
    case TILE = 0;
}
