<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSImageFrameStyle: int
{
    case NS_IMAGE_FRAME_NONE = 0;
    case NS_IMAGE_FRAME_PHOTO = 1;
    case NS_IMAGE_FRAME_GRAY_BEZEL = 2;
    case NS_IMAGE_FRAME_GROOVE = 3;
    case NS_IMAGE_FRAME_BUTTON = 4;
}
