<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSImageSymbolScale: int
{
    case SMALL = 1;
    case MEDIUM = 2;
    case LARGE = 3;
}
