<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSImageScaling: int
{
    case NS_IMAGE_SCALE_PROPORTIONALLY_DOWN = 0;
    case NS_IMAGE_SCALE_AXES_INDEPENDENTLY = 1;
    case NS_IMAGE_SCALE_NONE = 2;
    case NS_IMAGE_SCALE_PROPORTIONALLY_UP_OR_DOWN = 3;
}
