<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSImageAlignment: int
{
    case NS_IMAGE_ALIGN_CENTER = 0;
    case NS_IMAGE_ALIGN_TOP = 1;
    case NS_IMAGE_ALIGN_TOP_LEFT = 2;
    case NS_IMAGE_ALIGN_TOP_RIGHT = 3;
    case NS_IMAGE_ALIGN_LEFT = 4;
    case NS_IMAGE_ALIGN_BOTTOM = 5;
    case NS_IMAGE_ALIGN_BOTTOM_LEFT = 6;
    case NS_IMAGE_ALIGN_BOTTOM_RIGHT = 7;
    case NS_IMAGE_ALIGN_RIGHT = 8;
}
