<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSImageLayoutDirection: int
{
    case UNSPECIFIED = -1;
    case LEFT_TO_RIGHT = 2;
    case RIGHT_TO_LEFT = 3;
}
