<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSLayoutAttribute: int
{
    case LEFT = 1;
    case RIGHT = 2;
    case TOP = 3;
    case BOTTOM = 4;
    case LEADING = 5;
    case TRAILING = 6;
    case WIDTH = 7;
    case HEIGHT = 8;
    case CENTER_X = 9;
    case CENTER_Y = 10;
    case LAST_BASELINE = 11;
    case FIRST_BASELINE = 12;
    case LEFT_MARGIN = 13;
    case RIGHT_MARGIN = 14;
    case TOP_MARGIN = 15;
    case BOTTOM_MARGIN = 16;
    case LEADING_MARGIN = 17;
    case TRAILING_MARGIN = 18;
    case CENTER_X_WITHIN_MARGINS = 19;
    case CENTER_Y_WITHIN_MARGINS = 20;
    case NOT_AN_ATTRIBUTE = 0;
}
