<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSLayoutConstraintOrientation: int
{
    case HORIZONTAL = 0;
    case VERTICAL = 1;
}
