<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSLineBreakMode: int
{
    case NS_LINE_BREAK_BY_WORD_WRAPPING = 0;
    case NS_LINE_BREAK_BY_CHAR_WRAPPING = 1;
    case NS_LINE_BREAK_BY_CLIPPING = 2;
    case NS_LINE_BREAK_BY_TRUNCATING_HEAD = 3;
    case NS_LINE_BREAK_BY_TRUNCATING_TAIL = 4;
    case NS_LINE_BREAK_BY_TRUNCATING_MIDDLE = 5;
}
