<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSLineBreakStrategy: int
{
    case NONE = 0;
    case PUSH_OUT = 1;
    case HANGUL_WORD_PRIORITY = 2;
    case STANDARD = 65535;
}
