<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSLineMovementDirection: int
{
    case NS_LINE_DOESNT_MOVE = 0;
    case NS_LINE_MOVES_LEFT = 1;
    case NS_LINE_MOVES_RIGHT = 2;
    case NS_LINE_MOVES_DOWN = 3;
    case NS_LINE_MOVES_UP = 4;
}
