<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSLineSweepDirection: int
{
    case NS_LINE_SWEEP_LEFT = 0;
    case NS_LINE_SWEEP_RIGHT = 1;
    case NS_LINE_SWEEP_DOWN = 2;
    case NS_LINE_SWEEP_UP = 3;
}
