<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSMenuSelectionMode: int
{
    case AUTOMATIC = 0;
    case SELECT_ONE = 1;
    case SELECT_ANY = 2;
}
