<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSOpenGLContextParameter: int
{
    case SWAP_INTERVAL = 222;
    case SURFACE_ORDER = 235;
    case SURFACE_OPACITY = 236;
    case SURFACE_BACKING_SIZE = 304;
    case RECLAIM_RESOURCES = 308;
    case CURRENT_RENDERER_ID = 309;
    case GPU_VERTEX_PROCESSING = 310;
    case GPU_FRAGMENT_PROCESSING = 311;
    case HAS_DRAWABLE = 314;
    case MP_SWAPS_IN_FLIGHT = 315;
    case SWAP_RECTANGLE = 200;
    case SWAP_RECTANGLE_ENABLE = 201;
    case RASTERIZATION_ENABLE = 221;
    case STATE_VALIDATION = 301;
    case SURFACE_SURFACE_VOLATILE = 306;
}
