<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSPathStyle: int
{
    case STANDARD = 0;
    case POP_UP = 2;
    case NAVIGATION_BAR = 1;
}
