<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSPointingDeviceType: int
{
    case UNKNOWN = 0;
    case PEN = 1;
    case CURSOR = 2;
    case ERASER = 3;
}
