<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSProgressIndicatorStyle: int
{
    case BAR = 0;
    case SPINNING = 1;
}
