<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSRectEdge: int
{
    case MIN_X = 0;
    case MIN_Y = 1;
    case MAX_X = 2;
    case MAX_Y = 3;
}
