<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSScrollerKnobStyle: int
{
    case DEFAULT = 0;
    case DARK = 1;
    case LIGHT = 2;
}
