<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSScrollElasticity: int
{
    case AUTOMATIC = 0;
    case NONE = 1;
    case ALLOWED = 2;
}
