<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSScrollViewFindBarPosition: int
{
    case ABOVE_HORIZONTAL_RULER = 0;
    case ABOVE_CONTENT = 1;
    case BELOW_CONTENT = 2;
}
