<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSSelectionDirection: int
{
    case NS_DIRECT_SELECTION = 0;
    case NS_SELECTING_NEXT = 1;
    case NS_SELECTING_PREVIOUS = 2;
}
