<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSSliderType: int
{
    case LINEAR = 0;
    case CIRCULAR = 1;
}
