<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSStackViewDistribution: int
{
    case GRAVITY_AREAS = -1;
    case FILL = 0;
    case FILL_EQUALLY = 1;
    case FILL_PROPORTIONALLY = 2;
    case EQUAL_SPACING = 3;
    case EQUAL_CENTERING = 4;
}
