<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSStatusItemBehavior: int
{
    case REMOVAL_ALLOWED = 2;
    case TERMINATION_ON_REMOVAL = 4;
}
