<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTableViewAnimationOptions: int
{
    case NS_TABLE_VIEW_ANIMATION_EFFECT_NONE = 0;
    case NS_TABLE_VIEW_ANIMATION_EFFECT_FADE = 1;
    case NS_TABLE_VIEW_ANIMATION_EFFECT_GAP = 2;
    case NS_TABLE_VIEW_ANIMATION_SLIDE_UP = 16;
    case NS_TABLE_VIEW_ANIMATION_SLIDE_DOWN = 32;
    case NS_TABLE_VIEW_ANIMATION_SLIDE_LEFT = 48;
    case NS_TABLE_VIEW_ANIMATION_SLIDE_RIGHT = 64;
}
