<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTableViewDraggingDestinationFeedbackStyle: int
{
    case NONE = -1;
    case REGULAR = 0;
    case SOURCE_LIST = 1;
    case GAP = 2;
}
