<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTableViewColumnAutoresizingStyle: int
{
    case NS_TABLE_VIEW_NO_COLUMN_AUTORESIZING = 0;
    case NS_TABLE_VIEW_UNIFORM_COLUMN_AUTORESIZING_STYLE = 1;
    case NS_TABLE_VIEW_SEQUENTIAL_COLUMN_AUTORESIZING_STYLE = 2;
    case NS_TABLE_VIEW_REVERSE_SEQUENTIAL_COLUMN_AUTORESIZING_STYLE = 3;
    case NS_TABLE_VIEW_LAST_COLUMN_ONLY_AUTORESIZING_STYLE = 4;
    case NS_TABLE_VIEW_FIRST_COLUMN_ONLY_AUTORESIZING_STYLE = 5;
}
