<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTabViewType: int
{
    case NS_TOP_TABS_BEZEL_BORDER = 0;
    case NS_LEFT_TABS_BEZEL_BORDER = 1;
    case NS_BOTTOM_TABS_BEZEL_BORDER = 2;
    case NS_RIGHT_TABS_BEZEL_BORDER = 3;
    case NS_NO_TABS_BEZEL_BORDER = 4;
    case NS_NO_TABS_LINE_BORDER = 5;
    case NS_NO_TABS_NO_BORDER = 6;
}
