<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTableColumnResizingOptions: int
{
    case NS_TABLE_COLUMN_NO_RESIZING = 0;
    case NS_TABLE_COLUMN_AUTORESIZING_MASK = 1;
    case NS_TABLE_COLUMN_USER_RESIZING_MASK = 2;
}
