<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTableViewDropOperation: int
{
    case NS_TABLE_VIEW_DROP_ON = 0;
    case NS_TABLE_VIEW_DROP_ABOVE = 1;
}
