<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTabViewBorderType: int
{
    case NONE = 0;
    case LINE = 1;
    case BEZEL = 2;
}
