<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTextInputTraitType: int
{
    case DEFAULT = 0;
    case NO = 1;
    case YES = 2;
}
