<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTextAlignment: int
{
    case LEFT = 0;
    case CENTER = 2;
    case RIGHT = 1;
    case JUSTIFIED = 3;
    case NATURAL = 4;
}
