<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTextStorageEditActions: int
{
    case NS_TEXT_STORAGE_EDITED_ATTRIBUTES = 1;
    case NS_TEXT_STORAGE_EDITED_CHARACTERS = 2;
}
