<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTitlePosition: int
{
    case NS_NO_TITLE = 0;
    case NS_ABOVE_TOP = 1;
    case NS_AT_TOP = 2;
    case NS_BELOW_TOP = 3;
    case NS_ABOVE_BOTTOM = 4;
    case NS_AT_BOTTOM = 5;
    case NS_BELOW_BOTTOM = 6;
}
