<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTouchTypeMask: int
{
    case DIRECT = 1;
    case INDIRECT = 2;
}
