<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSToolbarDisplayMode: int
{
    case DEFAULT = 0;
    case ICON_AND_LABEL = 1;
    case ICON_ONLY = 2;
    case LABEL_ONLY = 3;
}
