<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSToolbarItemGroupSelectionMode: int
{
    case SELECT_ONE = 0;
    case SELECT_ANY = 1;
    case MOMENTARY = 2;
}
