<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSToolbarItemGroupControlRepresentation: int
{
    case AUTOMATIC = 0;
    case EXPANDED = 1;
    case COLLAPSED = 2;
}
