<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSTypesetterBehavior: int
{
    case NS_TYPESETTER_LATEST_BEHAVIOR = -1;
    case NS_TYPESETTER_ORIGINAL_BEHAVIOR = 0;
    case CASE_10_2_WITH_COMPATIBILITY = 1;
    case CASE_10_2 = 2;
    case CASE_10_3 = 3;
    case CASE_10_4 = 4;
}
