<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSUnderlineStyle: int
{
    case NONE = 0;
    case SINGLE = 1;
    case THICK = 2;
    case DOUBLE = 9;
    case PATTERN_DOT = 256;
    case PATTERN_DASH = 512;
    case PATTERN_DASH_DOT = 768;
    case PATTERN_DASH_DOT_DOT = 1024;
    case BY_WORD = 32768;
}
