<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSVisualEffectBlendingMode: int
{
    case BEHIND_WINDOW = 0;
    case WITHIN_WINDOW = 1;
}
