<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSWindowOrderingMode: int
{
    case NS_WINDOW_ABOVE = 1;
    case NS_WINDOW_BELOW = -1;
    case NS_WINDOW_OUT = 0;
}
