<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSWindowNumberListOptions: int
{
    case NS_WINDOW_NUMBER_LIST_ALL_APPLICATIONS = 1;
    case NS_WINDOW_NUMBER_LIST_ALL_SPACES = 16;
}
