<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSWindowToolbarStyle: int
{
    case AUTOMATIC = 0;
    case EXPANDED = 1;
    case PREFERENCE = 2;
    case UNIFIED = 3;
    case UNIFIED_COMPACT = 4;
}
