<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSWritingDirection: int
{
    case NATURAL = -1;
    case LEFT_TO_RIGHT = 0;
    case RIGHT_TO_LEFT = 1;
}
