<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
enum NSWritingToolsBehavior: int
{
    case NONE = -1;
    case DEFAULT = 0;
    case COMPLETE = 1;
    case LIMITED = 2;
}
