<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\AV;

use AppKit\AV\AVPlayer\AVPlayer as ExtAVPlayer;
use Jovian\Bindings\AppKit\Enums\AVPlayerStatus;
use Jovian\Bindings\AppKit\Enums\AVPlayerTimeControlStatus;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class AVPlayer extends ObjCObject
{
    public static function playerWithURL(int $URL): ?ObjCObject
    {
        return ObjCObject::box(ExtAVPlayer::playerWithURL($URL));
    }

    public function play(): static
    {
        ExtAVPlayer::play($this->handle);

        return $this;
    }

    public function pause(): static
    {
        ExtAVPlayer::pause($this->handle);

        return $this;
    }

    public function rate(): float
    {
        return ExtAVPlayer::rate($this->handle);
    }

    public function setRate(float $rate): static
    {
        ExtAVPlayer::setRate($this->handle, $rate);

        return $this;
    }

    public function volume(): float
    {
        return ExtAVPlayer::volume($this->handle);
    }

    public function setVolume(float $volume): static
    {
        ExtAVPlayer::setVolume($this->handle, $volume);

        return $this;
    }

    public function isMuted(): bool
    {
        return ExtAVPlayer::isMuted($this->handle);
    }

    public function setMuted(bool $muted): static
    {
        ExtAVPlayer::setMuted($this->handle, $muted);

        return $this;
    }

    public function status(): AVPlayerStatus|int
    {
        return ExtAVPlayer::status($this->handle);
    }

    public function timeControlStatus(): AVPlayerTimeControlStatus|int
    {
        return ExtAVPlayer::timeControlStatus($this->handle);
    }
}
