<?php

declare(strict_types=1);

namespace Jovian\Bindings\AppKit\AV;

use AppKit\AV\AVPlayerView\AVPlayerView as ExtAVPlayerView;
use Jovian\Bindings\AppKit\Enums\AVPlayerViewControlsStyle;
use Jovian\Bindings\AppKit\NS\NSView;
use Jovian\Bindings\AppKit\Runtime\ObjCObject;
use Jovian\Bindings\AppKit\Values\NSEdgeInsets;
use Jovian\Bindings\AppKit\Values\NSPoint;
use Jovian\Bindings\AppKit\Values\NSRange;
use Jovian\Bindings\AppKit\Values\NSRect;
use Jovian\Bindings\AppKit\Values\NSSize;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
class AVPlayerView extends NSView
{
    public static function initWithFrame(NSRect $frameRect): ?ObjCObject
    {
        return ObjCObject::box(ExtAVPlayerView::initWithFrame(...[...$frameRect->toArgs()]));
    }

    public function player(): int
    {
        return ExtAVPlayerView::player($this->handle);
    }

    public function setPlayer(int $player): static
    {
        ExtAVPlayerView::setPlayer($this->handle, $player);

        return $this;
    }

    public function controlsStyle(): AVPlayerViewControlsStyle|int
    {
        return ExtAVPlayerView::controlsStyle($this->handle);
    }

    public function setControlsStyle(AVPlayerViewControlsStyle|int $controlsStyle): static
    {
        ExtAVPlayerView::setControlsStyle($this->handle, $controlsStyle instanceof \BackedEnum ? $controlsStyle->value : $controlsStyle);

        return $this;
    }

    public function videoGravity(): mixed
    {
        return ExtAVPlayerView::videoGravity($this->handle);
    }

    public function setVideoGravity(int $videoGravity): static
    {
        ExtAVPlayerView::setVideoGravity($this->handle, $videoGravity);

        return $this;
    }

    public function showsFullScreenToggleButton(): bool
    {
        return ExtAVPlayerView::showsFullScreenToggleButton($this->handle);
    }

    public function setShowsFullScreenToggleButton(bool $showsFullScreenToggleButton): static
    {
        ExtAVPlayerView::setShowsFullScreenToggleButton($this->handle, $showsFullScreenToggleButton);

        return $this;
    }
}
