<?php

declare(strict_types=1);

it('emits int-backed enums with FULLY UPPERCASE cases and no class constants', function () {
    $files = glob(dirname(__DIR__, 2) . '/src/Enums/*.php') ?: [];
    expect($files)->not->toBeEmpty();

    foreach ($files as $file) {
        $source = (string) file_get_contents($file);
        expect($source)->toContain('GENERATED by scripts/generate.php')
            ->and($source)->toMatch('/enum\s+\w+\s*:\s*int/')
            ->and($source)->not->toMatch('/\bconst\s+/');

        preg_match_all('/case\s+([A-Za-z_][A-Za-z0-9_]*)\s*=/', $source, $matches);
        expect($matches[1])->not->toBeEmpty($file);
        foreach ($matches[1] as $case) {
            expect($case)->toMatch('/^[A-Z][A-Z0-9_]*$/');
        }
    }
});

it('projects NSWindowTitleVisibility from the SDK members Visible and Hidden', function () {
    expect(class_exists(\Jovian\Bindings\AppKit\Enums\NSWindowTitleVisibility::class))->toBeTrue()
        ->and(\Jovian\Bindings\AppKit\Enums\NSWindowTitleVisibility::NS_WINDOW_TITLE_VISIBLE->value)->toBe(0)
        ->and(\Jovian\Bindings\AppKit\Enums\NSWindowTitleVisibility::NS_WINDOW_TITLE_HIDDEN->value)->toBe(1);
});

it('skips later aliases that would duplicate a backed value', function () {
    $path = dirname(__DIR__, 2) . '/src/Enums/NSEventSubtype.php';
    expect(is_file($path))->toBeTrue();

    $cases = \Jovian\Bindings\AppKit\Enums\NSEventSubtype::cases();
    $values = array_map(static fn (\Jovian\Bindings\AppKit\Enums\NSEventSubtype $case): int => $case->value, $cases);
    expect($values)->toHaveCount(count(array_unique($values)));
});
